#!/usr/bin/env python3
#
# GlobalChemExtensions - Tainted Sexual Products
#
# --------------------------------------------------

class TaintedSexualProducts(object):

    '''

    Flask Application to run SMARTS Patterns.

    '''

    def __init__(self):

        self.name = 'tainted_products'

    def fetch_brands(self):


        tainted_products = [
            'kingdom honey royal honey vip',
            'cougar secret_honey vip',
            'medcare golden royal honey',
            'honey gizer',
            'etumax vip royal honey for him',
            'erkexin',
            'royal honey vip',
            'secret miracle honey',
            'vital honey',
            'wonderful honey',
            'avaphinal',
            'brahma_male',
            'go_on_red',
            'hard af',
            'helmis honey',
            'jaguar power',
            'kangaroo intense alpha',
            'magnum xxl 9800',
            'pink pussycat',
            'themra epimedyumlu bitkisel karisimli macun',
            'xrated honey',
            'adams secret extra strength 2000',
            'enerup premium',
            'erect max',
            'vital sex',
            'yin-yang essence men power',
            'furious x 1350',
            'zing plus',
            '2 own the knight silver',
            'rhino se7en',
            'stiff rox',
            'titanium 18k',
            'alpha male plus',
            'adams secret extra strength 1500',
            'adams secret extra strength 3000 platinum',
            'white panther',
            'triple wicked platinum',
            'super panther 77k',
            'premier zen gold 7000',
            'premier zen platinum 8000',
            'premier maxxzen platinum 12000',
            'poseidon platinum 10000',
            'poseidon platinum 3500',
            'mero macho',
            'gold lion',
            'blue panther extreme 75k',
            'black stallion 9000',
            'triple supreme zen plus 3500',
            'triple supreme zen gold 3500',
            'triple supreme zen extreme 3500',
            'thumbs up 7 white 11k',
            'thumbs up 7 red 70k',
            'thumbs up 7 blue 69k',
            'thumbs up 7 black 25k',
            'shogun x platinum 7000',
            'rock steady 72 hours',
            'red spartan 3000',
            'premium orgazen 7000',
            'premier platinum 5000',
            'premier zen extreme 3000',
            'premier zen black 5000',
            'original white dragon',
            'krazy night',
            'kopi jantan tradisional natural herbs coffee',
            'imperial platinum 2000',
            'imperial gold 2000',
            'imperial extreme 2000',
            'hot rod',
            'ginseng powder 5000',
            'burro en primavera 60000',
            '69 blue mode 69',
            '3ko gold xt',
            'v8 super energy',
            'usa viagra',
            'stree overlord',
            'rhinozen 69 platinum 25000',
            'rhino 99 extreme 90000',
            'rhino 96 extreme 77000',
            'rhino 69 power 500k',
            'rhino 69 platinum 75000',
            'rhino 8 platinum 80000',
            'magnum xxl 50k',
            'herb viagra',
            'bigger longer more time more sperms',
            'vigorous man',
            'black mamba premium 18000',
            'orgazen gold 5800',
            'alpha-male',
            'xxx platinum woodie',
            'super platinum 30000 bull',
            'super platinum 30000 panther',
            'power khan',
            'man erect',
            'shengda',
            'up2',
            'chu dietary supplement',
            'green lumber',
            'anaconda strong formula',
            'lung leader',
            'lobo',
            'black storm',
            'big penis',
            'boss lion 9000',
            'de guo heijin gang',
            'la pepa negra',
            'odimafo powerful',
            'plant viagra',
            'shengjingpian',
            'vigour 800',
            'peru maca',
            'germany black gorilla',
            'man fuel extreme condition',
            'man fuel enhancement male shooter',
            'red stallion extra strong',
            'natural v=gra',
            'yong gang',
            'golden ant',
            'instinct best sexual enjoyment',
            'nectar del amor',
            'the silver bullet',
            'on demand',
            'willy go wild',
            'mob candy',
            'america treasure',
            'leopard secret miracle of honey',
            'best leopard miracle of honey',
            'gold max blue',
            'pro solution',
            'v-max',
            'strong horses',
            'usa for women',
            'fx 75000',
            'premier zen gold 4000',
            'extenze plus',
            'extenze nutritional supplement',
            'xxxplosion ultra',
            'panther power',
            '5k',
            'ding ji wei ge',
            'platinum rhino 25000',
            'krazzy rhino 25000',
            'gold rhino 25000',
            'boss rhino 15000',
            'dale mas',
            'c.u. plus',
            'grakcu capsule',
            'maximum powerful',
            'chong cao qiang shen wang',
            'maxidus',
            'gold viagra',
            'xxxplosion',
            'black stallion 35000',
            'best candy',
            'rhino 69 extreme 50000',
            'red zone extreme 3000',
            'black lion pill',
            'chao jimengnan ',
            'tyrannosaurus',
            'v9 male sexual enhancement',
            'swag II platinum 33k',
            'rhino 69 premium 8000',
            'rhino 25k 15000',
            'rhino 12 titanium 6000',
            'rhino 11 titanium 6000',
            'qibianli',
            'new stiff nights platinum 10k',
            'men xtrong',
            'blue diamond pill',
            'control capsules',
            'blue pearl all natural male enhancments',
            'hard times for men',
            'tiger 5000',
            'rhino 7 platinum 5000',
        ]

        return tainted_products
