
class EuropeanUnionPsychoactiveSubstancesDrugReport(object):
    
    def __init__(self):
        self.name = 'european_union_psychoactive_substances_drug_report'

    @staticmethod
    def get_smiles():
        smiles = {
            "1-Aminoindan": "C1=CC2=C(C=C1)C(CC2)N.C1=CC2=C(C=C1)C(CC2)N",
            "2-Aminoindan": "C1=CC2=C(C=C1)CC(C2)N",
            "5-IAI": "C1=C2CC(CC2=CC(=C1)I)N",
            "5-MeO-AI": "COC1=CC=C2CC(CC2=C1)N",
            "MDAI": "C1C2=C(CC1N)C=C3C(=C2)OCO3",
            "N-methyl-2AI": "CNC1CC2=C(C=CC=C2)C1",
            "1-(4-Bromo-2,5-dimethoxyphenyl)ethanamine": "CC(C1=C(C=C(C(=C1)OC)Br)OC)N",
            "1-PEA": "CC(C1=CC=CC=C1)N.CC(C1=CC=CC=C1)N",
            "1-phenyl-1-propanamine": "CCC(C1=CC=CC=C1)N.CCC(C1=CC=CC=C1)N",
            "2-APB": "CC(CC1=CC2=C(C=CC=C2)O1)N",
            "2C-B-Fly": "C(CN)C1=C2C(=C(C3=C1CCO3)Br)CCO2",
            "2-EAPB": "CCNC(C)CC1=CC2=C(C=CC=C2)O1",
            "2-MABB": "CCC(CC1=CC2=C(C=CC=C2)O1)NC",
            "2-MAPB": "CC(CC1=CC2=C(C=CC=C2)O1)NC",
            "3-amino-1-phenyl-butane": "CC(CCC1=CC=CC=C1)N.CC(CCC1=CC=CC=C1)N",
            "4-APB": "CC(CC1=CC=CC2=C1C=CO2)N",
            "4-EAPB": "CCNC(C)CC1=CC=CC2=C1C=CO2",
            "5-APB": "CC(CC1=CC2=C(C=C1)OC=C2)N",
            "5-APB NBOMe": "CC(CC1=CC2=C(C=C1)OC=C2)NCC3=C(C=CC=C3)OC",
            "5-APDB": "CC(CC1=CC=C2C(=C1)CCO2)N",
            "5-APDI": "CC(CC1=CC=C2CCCC2=C1)N",
            "5Cl-bk-MPA": "CC(C(=O)C1=CC=C(Cl)S1)NC",
            "5-EAPB": "CCNC(C)CC1=CC2=C(C=C1)OC=C2",
            "5-IT": "CC(CC1=CC2=C(C=C1)NC=C2)N",
            "5-MABB": "CCC(CC1=CC2=C(C=C1)OC=C2)NC",
            "5-MAPB": "CC(CC1=CC2=C(C=C1)OC=C2)NC",
            "5-MAPDB": "CC(CC1=CC=C2C(=C1)CCO2)NC",
            "5-MAPDI": "CC(CC1=CC=C2CCCC2=C1)NC",
            "5-MeO-DIBF": "CC(C)N(CCC1=COC2=C1C=C(C=C2)OC)C(C)C",
            "5-Methylthiopropamine": "CCC1=CC=C(CC(C)N)S1",
            "6-APB": "CC(CC1=CC2=C(C=C1)C=CO2)N",
            "6-APDB": "CC(CC1=CC=C2CCOC2=C1)N",
            "6-EAPB": "CCNC(C)CC1=CC2=C(C=C1)C=CO2",
            "6-IT": "CCN(C)C(C)C1=CC2=C(C=C1)C=CN2",
            "6-MAPB": "CC(CC1=CC2=C(C=C1)C=CO2)NC",
            "Atomoxetine": "CC1=C(C=CC=C1)O[C@H](CCNC)C2=CC=CC=C2",
            "bk-MPA": "CC(C(=O)C1=CC=CS1)NC",
            "BOH-2C-B": "COC1=C(C=C(C(=C1)Br)OC)C(CN)O",
            "BOH-PHP": "CCCCC(C(C1=CC=CC=C1)O)N2CCCC2",
            "Bromo-Dragonfly": "CC(CC1=C2C(=C(C3=C1C=CO3)Br)C=CO2)N",
            "DPIA": "CC(CC1=CC=CC=C1)NC(C)CC2=CC=CC=C2",
            "M-ALPHA": "CCC(C1=CC=C2C(=C1)OCO2)NC",
            "M-ALPHA-HCMA": "CC(C(C1=CC=C2C(=C1)OCO2)NC)(C(=O)NC)O",
            "Mephedrene": "CC1=CC=C(CC(C)NC)S1",
            "Methamnetamine": "CC(CC1=CC2=C(C=CC=C2)C=C1)NC",
            "Methylthienylpropamine (MPA)": "CC(CC1=CC=CS1)NC",
            "N-benzyl-1- phenethylamine": "CC(C1=CC=CC=C1)NCC2=CC=CC=C2",
            "Thiopropamine": "CC(CC1=CC=CS1)N",
            "2-fluorodeschloroketamine": "CNC1(CCCCC1=O)C2=C(C=CC=C2)F",
            "2-Fluoro-deschloro-N-ethylketamine": "CCNC1(CCCCC1=O)C2=C(C=CC=C2)F",
            "2-MeO-Ketamine": "CNC1(CCCCC1=O)C2=C(C=CC=C2)OC",
            "3-Chloro-PCP": "C1CCC(CC1)(C2=CC(=CC=C2)Cl)N3CCCCC3",
            "3-Fluoro-PCP": "C1CCC(CC1)(C2=CC(=CC=C2)F)N3CCCCC3",
            "3-HO-PCE": "CCNC1(CCCCC1)C2=CC=CC(=C2)O",
            "3-HO-PCP": "C1CCC(CC1)(C2=CC=CC(=C2)O)N3CCCCC3",
            "3-MeO-PCE": "CCNC1(CCCCC1)C2=CC=CC(=C2)OC",
            "3-MeO-PCMMo": "COC1=CC(=CC=C1)C2(CCCCC2)CN3CCOCC3",
            "3MeO-PCMo": "COC1=CC(=CC=C1)C2(CCCCC2)N3CCOCC3",
            "3-MeO-PCP": "COC1=CC(=CC=C1)C2(CCCCC2)N3CCCCC3",
            "3-Me-PCP": "CC1=CC=CC(=C1)C2(CCCCC2)N3CCCCC3",
            "3-Me-PCPy": "CC1=CC=CC(=C1)C2(CCCCC2)N3CCCC3",
            "4-MeO-PCP": "COC1=CC=C(C=C1)C2(CCCCC2)N3CCCCC3",
            "Benocyclidine": "C1CCC(CC1)(C2=CC3=C(C=CC=C3)S2)N4CCCCC4",
            "Deoxymethoxetamine": "CCNC1(CCCCC1=O)C2=CC(=CC=C2)C",
            "Deschloroketamine": "CNC1(CCCCC1=O)C2=CC=CC=C2",
            "deschloro-N-ethyl-ketamine (O-PCE)": "CCNC1(CCCCC1=O)C2=CC=CC=C2",
            "Fluorexetamine": "CCNC1(CCCCC1=O)C2=CC=CC(=C2)F",
            "Hydroxetamine": "CCNC1(CCCCC1=O)C2=CC=CC(=C2)O",
            "Ketamine": "CNC1(CCCCC1=O)C2=C(C=CC=C2)Cl",
            "Memantine": "CC12CC3CC(C)(C1)CC(C3)(C2)N",
            "Methoxetamine": "CCNC1(CCCCC1=O)C2=CC=CC(=C2)OC",
            "Methoxetamine brominated derivative": "CCNC1(CCCCC1=O)C2=CC(=CC=C2Br)OC",
            "Methoxisopropamine": "CCCNC1(CCCCC1=O)C2=CC=CC(=C2)OC",
            "Methoxpropamine": "CCCNC1(CCCCC1=O)C2=CC=CC(=C2)OC",
            "N-ethylnorketamine": "CCNC1(CCCCC1=O)C2=C(C=CC=C2)Cl",
            "PCP": "C1=CC=C(C=C1)C2(CCCCC2)N3CCCCC3",
            "Tiletamine": "CCNC1(CCCCC1=O)C2=C(C=CS2)C",
            "3-hydroxyphenazepam": "C1=CC(=C(C=C1)Cl)C2=NC(C(=O)NC3=C2C=C(C=C3)Br)O",
            "4-chlorodiazepam": "CN1C2=C(C=C(C=C2)Cl)C(=NCC1=O)C3=CC=C(C=C3)Cl",
            "Adinazolam": "CN(C)CC1=NN=C2CN=C(C3=CC=CC=C3)C4=C(C=CC(=C4)Cl)N21",
            "Bentazepam": "C1=CC=C(C=C1)C2=NCC(=O)NC3=C2C4=C(CCCC4)S3",
            "Bretazenil": "CC(C)(C)OC(=O)C1=NC=C2C=NC3=CC(=C(C(=O)N3CCN21)Br)Br",
            "Bromazolam": "CC1=NN=C2CN=C(C3=CC=CC=C3)C4=C(C=CC(=C4)Br)N12",
            "Cinazepam": "C1=CC(=C(C=C1)Cl)C2=NC(C(=O)NC3=C2C=C(C=C3)Br)OC(=O)CCC(=O)O",
            "Clobromazolam": "CC1=NN=C2CN=C(C3=C(C=CC=C3)Cl)C4=C(C=CC(=C4)Br)N12",
            "Clonazolam (Clonitrazolam)": "CC1=NN=C2CN=C(C3=C(C=CC=C3)Cl)C4=C(C=CC(=C4)[N+](=O)[O-])N12",
            "Cloniprazepam": "C1=CC(=C(C=C1)Cl)C2=NCC(=O)N(CC3CC3)C4=C2C=C(C=C4)[N+](=O)[O-]",
            "Desalkylgidazepam": "C1=CC=C(C=C1)C2=NCC(=O)NC3=C2C=C(C=C3)Br",
            "Deschloroclotizolam": "CC1=NC=CCN2C=N(Cl)N=C12",
            "Deschloroetizolam": "CCC1=CC2=C(S1)N3C(=NN=C3CN=C2C4=CC=CC=C4)C",
            "Diclazepam": "CN1C2=C(C=C(C=C2)Cl)C(=NCC1=O)C3=C(C=CC=C3)Cl",
            "Etizolam": "CCN1C=C2C(=NC=CCN2C(=N1)C3=C(C=CC=C3)Cl)C",
            "Flualprazolam": "CC1=NN=C2CN=C(C3=C(C=CC=C3)F)C4=C(C=CC(=C4)Cl)N12",
            "Flubromazepam": "C1=CC(=C(C=C1)F)C2=NCC(=O)NC3=C2C=C(C=C3)Br",
            "Flubromazolam": "CC1=NN=C2N1C3=C(C=C(C=C3)Br)C(=NC2)C4=CC=CC=C4F",
            "Flubrotizolam": "CC1=NC=CCN2C=N(Br)N=C12",
            "Fluclotizolam": "CC1=NC=CCN2C=N(Cl)N=C12",
            "Fluetizolam": "CCN1C=C2C(=NC=CCN2N=N1)C3=C(C=CC=C3)F",
            "Flunitrazolam": "CC1=NN=C2CN=C(C3=C(C=CC=C3)F)C4=C(C=CC(=C4)[N+](=O)[O-])N12",
            "Fonazepam": "C1=CC(=C(C=C1)F)C2=NCC(=O)NC3=C2C=C(C=C3)[N+](=O)[O-]",
            "Meclonazepam": "CC1C(=O)NC2=C(C=C(C=C2)[N+](=O)[O-])C(=N1)C3=C(C=CC=C3)Cl",
            "Methyl clonazepam": "CN1C2=C(C=C(C=C2)[N+](=O)[O-])C(=NCC1=O)C3=C(C=CC=C3)Cl",
            "Metizolam": "CCN1C=C2C(=CCC=NC=C2N=N1)C3=C(C=CC=C3)Cl",
            "Nifoxipam": "C1=CC(=C(C=C1)F)C2=NC(C(=O)NC3=C2C=C(C=C3)[N+](=O)[O-])O",
            "Nitrazolam": "CC1=NN=C2CN=C(C3=CC=CC=C3)C4=C(C=CC(=C4)[N+](=O)[O-])N12",
            "Norfludiazepam": "C1=CC(=C(C=C1)F)C2=NCC(=O)NC3=C2C=C(C=C3)Cl",
            "Phenazepam": "C1=CC(=C(C=C1)Cl)C2=NCC(=O)NC3=C2C=C(C=C3)Br",
            "Pyrazolam": "CC1=NN=C2CN=C(C3=C(C=CC(=C3)Br)N12)C4=NC=CC=C4",
            "Ro 07-4065": "CN1C2=C(C=C(C=C2)Cl)C(=NCC1=O)C3=C(C=CC=C3F)F",
            "Thionordazepam": "C1=CC=C(C=C1)C2=NCC(=S)NC3=C2C=C(C=C3)Cl",
            "Tofisopam": "CCC1C(=NN=C(C2=CC(=C(C=C2)OC)OC)C3=C1C=C(C(=C3)OC)OC)C",
            "1-(Cyclohexylmethyl)-2-[(4-ethoxyphenyl)methyl]-N,N-diethyl-1H-benzimidazol-5-carboxamide": "CCN(CC)C(=O)C1=CC2=C(C=C1)N(CC3CCCCC3)C(=N2)CC4=CC=C(C=C4)OCC",
            "2F-QMPSB": "CC1=CC=C(C=C1S(=O)(=O)N2CCC(CC2)(F)F)C(=O)OC3=C4C(=CC=C3)C=CC=N4",
            "3-(4-hydroxymethylbenzoyl)-1-pentylindole": "CCCCCN1C=C(C2=C1C=CC=C2)C(=O)C3=CC=C(C=C3)CO",
            "3-(p-Methoxybenzoyl)-N-methylindole": "CN1C=C(C2=C1C=CC=C2)C(=O)C3=CC=C(C=C3)OC",
            "3,5-ADB-4en-PFUPPYCA": "C=CCCCN1C(=CC(=N1)C2=CC=C(C=C2)F)C(=O)NC(C(=O)N)C(C)(C)C",
            "4en-PDMB-4en-PINACA": "C=CCCCN1C2=C(C=CC=C2)C(=N1C(CCC=C)CC)C(=O)NC(C)CC(=O)OC(CCC=C)C",
            "4F-ABINACA": "C1=CC2=C(C=C1)N(CCCCF)N=C2C(=O)NC34CC5CC(CC(C5)C3)C4",
            "4F-MDMB-BICA": "CC(C)(C)C(C(=O)OC)NC(=O)C1=CN(C2=CC=CC=C21)CCCCF",
            "4F-MDMB-BINACA": "CC(C)(C)C(C(=O)OC)NC(=O)C1=NN(CCCCF)C2=C1C=CC=C2",
            "4-HTMPIPO": "CCCCCN1C=C(C2=C1C=CC=C2)C(=O)CC(C)(C)C(C)(C)O",
            "5,3-AB-CHMFUPPYCA": "CC(C)C(C(=O)N)NC(=O)C1=NN(CC2CCCCC2)C(=C1)C3=CC=C(C=C3)F",
            "5,3-ADB-4en-PFUPPYCA": "C=CCCCN1C(=CC(=N1)C(=O)NC(C(=O)N)C(C)(C)C)C2=CC=C(C=C2)F",
            "5B-AKB48": "C(CCBr)CCN1C2=C(C=CC=C2)C(=N1)C(=O)NC34CC5CC(CC(C5)C3)C4",
            "5C-AKB48": "C(CCCl)CCN1C2=C(C=CC=C2)C(=N1)C(=O)NC34CC5CC(CC(C5)C3)C4",
            "5-chloropentyl JWH-018 indazole analogue (5Cl-THJ-018)": "C(CCCl)CCN1C2=C(C=CC=C2)C(=N1)C(=O)C3=CC=CC4=C3C=CC=C4",
            "5Cl-AB-PINACA": "CCCNC(=O)C1=NN(CCCCCCl)C2=C1C=CC=C2",
            "5Cl-MDMB-PINACA": "CC(C)(C)C(C(=O)OC)NC(=O)C1=NN(CCCCCCl)C2=C1C=CC=C2",
            "5F NNEI 2'-naphthylisomer": "C(CCF)CCN1C=C(C2=C1C=CC=C2)C(=O)NC3=CC4=C(C=CC=C4)C=C3",
            "5F-3,5-AB-PFUPPYCA": "CCCNC(=O)C1=CC(=NN1CCCCCF)C2=CC=C(C=C2)F",
            "5F-AB-FUPPYCA (5F-5,3-AB-PFUPPYCA)": "CC(C)C(C(=O)N)NC=O",
            "5F-AB-P7AICA": "CC(C)C(C(=O)N)NC(=O)C1=CN(CCCCCF)C2=C1C=CC=N2",
            "5F-AB-PINACA": "CCCNC(=O)C1=NN(CCCCCF)C2=C1C=CC=C2",
            "5F-ADBICA": "CC(C)(C)C(C(=O)N)NC(=O)C1=CN(CCCCCF)C2=C1C=CC=C2",
            "5F-ADB-PINACA": "CC(C)(C)C(C(=O)N)NC(=O)C1=NN(CCCCCF)C2=C1C=CC=C2",
            "5F-AKB48": "C(CCF)CCN1C2=C(C=CC=C2)C(=N1)C(=O)NC34CC5CC(CC(C5)C3)C4",
            "5F-AKB57": "C(CCF)CCN1C2=C(C=CC=C2)C(=N1)C(=O)OC34CC5CC(CC(C5)C3)C4",
            "5F-AMB": "CC(C)C(C(=O)OC)NC(=O)C1=NN(C2=CC=CC=C21)CCCCCF",
            "5F-AMBICA": "CCCNC(=O)C1=CN(CCCCCF)C2=C1C=CC=C2",
            "5F-AMB-PICA": "CC(C)C(C(=O)OC)NC(=O)C1=CN(CCCCCF)C2=C1C=CC=C2",
            "5F-A-P7AICA": "C(CCF)CCN1C=C(C2=C1N=CC=C2)C(=O)NC34CC5CC(CC(C5)C3)C4",
            "5F-APP-PICA": "C1=CC=C(C=C1)CC(C(=O)N)NC(=O)C2=CN(CCCCCF)C3=C2C=CC=C3",
            "5F-APP-PINACA": "CCN(C(CC1=CC=CC=C1)C(=O)N)C(=O)C2=NN(CCCCCF)C3=C2C=CC=C3",
            "5F-Cumyl-PeGaClone": "CCC(C)(C1=CC=CC=C1)N2C=CC3=C(C4=C(C=CC=C4)N3CCCCCF)C2=O",
            "5F-EDMB-PICA": "CCOC(=O)C(C(C)(C)C)NC(=O)C1=CN(CCCCCF)C2=C1C=CC=C2",
            "5F-EDMB-PINACA": "CCOC(=O)C(C(C)(C)C)NC(=O)C1=NN(CCCCCF)C2=C1C=CC=C2",
            "5F-EMB-PICA": "CCOC(=O)C(C(C)C)NC(=O)C1=CN(CCCCCF)C2=C1C=CC=C2",
            "5F-EMB-PINACA": "CCOC(=O)C(C(C)C)NC(=O)C1=NN(CCCCCF)C2=C1C=CC=C2",
            "5F-JWH-398 (CL-2201)": "C(CCF)CCN1C=C(C2=C1C=CC=C2)C(=O)C3=C4C=CC=CC4=NC=C3",
            "5-fluoropentyl-3-pyridinoylindole": "C(CCF)CCN1C=C(C2=C1C=CC=C2)C(=O)C3=CC=CN=C3",
            "5F-MDMB-P4AICA": "CC(C)(C)C(C(=O)OC)NC(=O)C1=CN(CCCCCF)C2=CC=CN=C12",
            "5F-MDMB-P7AICA": "CC(C)(C)C(C(=O)OC)NC(=O)C1=CN(C2=C1C=CC=N2)CCCCCF",
            "5F-MDMB-PICA": "CC(C)(C)C(C(=O)OC)NC(=O)C1=CN(CCCCCF)C2=C1C=CC=C2",
            "5F-MDMB-PINACA (5F-ADB)": "CC(C)(C)C(C(=O)OC)NC(=O)C1=NN(CCCCCF)C2=C1C=CC=C2",
            "5F-PB-22 indazole analogue": "C(CCF)CCN1C2=C(C=CC=C2)C(=N1)C(=O)OC3=C4C(=CC=C3)C=CC=N4",
            "5F-PCN": "C(CCF)CCN1C=C(C2=C1C=CN=C2)C(=O)NC3=CC=CC4=C3C=CC=C4",
            "5F-PY-PICA": "C(CCF)CCN1C=C(C2=C1C=CC=C2)C(=O)N3CCCC3",
            "5F-PY-PINACA": "C(CCF)CCN1C2=C(C=CC=C2)C(=N1)C(=O)N3CCCC3",
            "5F-SDB-005": "C(CCF)CCN1C2=C(C=CC=C2)C(=N1)C(=O)OC3=CC=CC4=C3C=CC=C4",
            "5F-SDB-006": "C1=CC=C(C=C1)CNC(=O)C2=CN(CCCCCF)C3=C2C=CC=C3",
            "5FUR-144 (XLR-11)": "CC1(C)C(C(=O)C2=CN(CCCCCF)C3=C2C=CC=C3)C1(C)C",
            "A-796,260": "CC1(C(C1(C)C)C(=O)C2=CN(C3=CC=CC=C32)CCN4CCOCC4)C",
            "A-796,260 isomer": "C/C(=C\C(=O)C1=CN(CCN2CCOCC2)C3=C1C=CC=C3)/C(C)(C)C",
            "A-834,735": "CC1(C(C1(C)C)C(=O)C2=CN(C3=CC=CC=C32)CC4CCOCC4)C",
            "A-836,339": "CC1=C(C)S/C(=N\C(=O)C2C(C)(C)C2(C)C)/N1CCOC",
            "AB-005": "CC1(C)C(C(=O)C2=CN(CN3CCCCC3CCCCC2)C4=C2C=CC=C4)C1(C)C",
            "AB-005 azepane isomer": "CC1(C)C(C(=O)C2=CN(C3=C2C=CC=C3)C4CCCCCN4C)C1(C)C",
            "AB-CHMFUPPYCA (3,5-AB-CHMFUPPYCA)": "CC(C)C(C(=O)N)NC(=O)C1=CC(=NN1CC2CCCCC2)C3=CC=C(C=C3)F",
            "AB-CHMINACA": "CC(C)C(C(=O)N)NC(=O)C1=NN(CC2CCCCC2)C3=C1C=CC=C3",
            "AB-FUBINACA": "CC(C)C(C(=O)N)NC(=O)C1=NN(CC2=CC=C(C=C2)F)C3=C1C=CC=C3",
            "AB-FUBINACA 2-fluorobenzyl isomer": "CCCNC(=O)C1=NN(CC2=C(C=CC=C2)F)C3=C1C=CC=C3",
            "ABO-4en-PINACA": "C=CCCC(C)N1C2=C(C=CC=C2)C(=N1)C(=O)NC(CC)C(=O)N",
            "AB-PINACA": "CCCCCN1C2=C(C=CC=C2)C(=N1)C(=O)NC(C(C)C)C(=O)N",
            "AB-PINACA N-(2-fluoropentyl) isomer": "CCCC(CN1C2=C(C=CC=C2)C(=N1)C(=O)NC(C(C)C)C(=O)N)F",
            "A-CHMINACA": "C1CCC(CC1)CN2C3=C(C=CC=C3)C(=N2)C(=O)NC45CC6CC(CC(C6)C4)C5",
            "ADAMANTYL-THPINACA": "C1=CC2=C(C=C1)N(CC3C=COC=C3)N=C2C(=O)NC45CC6CC(CC(C6)C4)C5",
            "ADB-4en-P-5Br-INACA": "C=CCCCN1C2=C(C=C(C=C2)Br)C(=N1)C(=O)NC(C(=N)C)C(C)(C)C",
            "ADB-4en-PINACA": "C=CCCCN1C2=C(C=CC=C2)C(=N1)C(=O)NC(C(=O)N)C(C)(C)C",
            "ADB-5Br-INACA": "CC(C)(C)C(C(=O)N)NC(=O)C1=NNC2=C1C=C(C=C2)Br",
            "ADB-B-5Br-INACA": "CCCCN1C2=C(C=C(C=C2)Br)C(=N1)C(=O)NC(C(=O)N)C(C)(C)C",
            "ADB-BUTINACA": "CCCCN1C2=C(C=CC=C2)C(=N1)C(=O)NC(C(=O)N)C(C)(C)C",
            "ADB-CHMICA": "CC(C)(C)C(C(=O)N)NC(=O)C1=CN(CC2CCCCC2)C3=C1C=CC=C3",
            "ADB-CHMINACA": "CC(C)(C)C(C(=O)N)NC(=O)C1=NN(CC2CCCCC2)C3=C1C=CC=C3",
            "ADB-D-5Br-INACA": "CCCCCCCCCCN1C2=C(C=C(C=C2)Br)C(=N1)C(=O)NC(C(=N)C)C(C)(C)C",
            "ADB-FUBHQUCA": "CC(C)(C)C(C(=O)N)NC(=O)C1=CN(CC2=CC=C(C=C2)F)C3=C(C=CC=C3)C1",
            "ADB-FUBIACA": "CC(=O)NC(C(=O)N)C(C)(C)C",
            "ADB-FUBINACA": "CCCN(C(=O)N)C(=O)C1=NN(CC2=CC=C(C=C2)F)C3=C1C=CC=C3",
            "ADB-HEXINACA": "CCCCCCN1C2=C(C=CC=C2)C(=N1)C(=O)NC(C(=O)N)C(C)(C)C",
            "ADB-IACA": "CC(C)(C)C(C(=O)N)NC(=O)CC1=CNC2=C1C=CC=C2",
            "ADBICA": "CCCCCN1C=C(C2=C1C=CC=C2)C(=O)NC(C(=O)N)C(C)(C)C",
            "ADB-P-5Br-INACA": "CCCCCN1C2=C(C=C(C=C2)Br)C(=N1)C(=O)NC(C(=N)C)C(C)(C)C",
            "ADB-PINACA": "CCCCCN1C2=C(C=CC=C2)C(=N1)C(=O)NC(C(=O)N)C(C)(C)C",
            "ADMB-INACA (ADB-INACA)": "CC(C)(C)C(C(=O)N)NC(=O)C1=NNC2=C1C=CC=C2",
            "A-FUBIACA": "C1=CC2=C(C=C1)N(CC3=CC=C(C=C3)F)C=C2CC(=O)NC45CC6CC(CC(C6)C4)C5",
            "AKB-57": "CCCCCN1C2=C(C=CC=C2)C(=N1)C(=O)OC34CC5CC(CC(C5)C3)C4",
            "AM-1220": "CN1CCCCC1CN2C=C(C3=CC=CC=C32)C(=O)C4=CC=CC5=CC=CC=C54",
            "AM-1220 Azepane Isomer": "CN1CCCCC(C1)N2C=C(C3=CC=CC=C32)C(=O)C4=CC=CC5=CC=CC=C54",
            "AM-1248": "CN1CCCCC1CN2C=C(C3=C2C=CC=C3)C(=O)C45CC6CC(CC(C6)C4)C5",
            "AM-1248 Azepane isomer": "CN1CCCCC(C1)N2C=C(C3=C2C=CC=C3)C(=O)C45CC6CC(CC(C6)C4)C5",
            "AM-2201": "C(CCF)CCN1C=C(C2=C1C=CC=C2)C(=O)C3=CC=CC4=C3C=CC=C4",
            "AM-2201 benzimidazole analogue (FUBIMINA)": "C(CCF)CCN1C2=C(C=CC=C2)N=C1C(=O)C3=CC=CC4=C3C=CC=C4",
            "AM-2201 carboxylate analogue quinolinyl derivative (5F-PB-22)": "C1=CC=C2C(=C1)C(=CN2CCCCCF)C(=O)OC3=CC=CC4=C3N=CC=C4",
            "AM-2201 indazole analogue": "C(CCF)CCN1C2=C(C=CC=C2)C(=N1)C(=O)C3=CC=CC4=C3C=CC=C4",
            "AM-2201 indazolecarboxamide analogue": "O=C(C1=NN(CCCCCF)C2=C1C=CC=C2)NC3=C4C=CC=CC4=CC=C3",
            "AM-2232": "C(CC#N)CCN1C=C(C2=C1C=CC=C2)C(=O)C3=CC=CC4=C3C=CC=C4",
            "AM-2233": "CN1CCCCC1CN2C=C(C3=CC=CC=C32)C(=O)C4=CC=CC=C4I",
            "AM-6527": "CCCCCN1C=C(C2=C1C=CC=C2)C(=O)NC3=CC=CC4=C3C=CC=C4",
            "AM-6527 5-fluoropentyl derivative": "C(NC=1C2=C(C=CC1)C=CC=C2)(=O)C=3C=4C(N(CCCCCF)C3)=CC=CC4",
            "AM-679": "CCCCCN1C=C(C2=C1C=CC=C2)C(=O)C3=C(C=CC=C3)I",
            "AM-694": "C(CCF)CCN1C=C(C2=C1C=CC=C2)C(=O)C3=C(C=CC=C3)I",
            "AM-694 (Chloro)": "C1=CC=C2C(=C1)C(=CN2CCCCCCl)C(=O)C3=CC=CC=C3I",
            "AM-694 ethyl substituted for iodine": "CCC1=C(C=CC=C1)C(=O)C2=CN(CCCCCF)C3=C2C=CC=C3",
            "AM-694 methyl substituted for iodine": "CC1=C(C=CC=C1)C(=O)C2=CN(CCCCCF)C3=C2C=CC=C3",
            "AMB-4en-PICA": "C=CCCC(C)N1C=C(C2=C1C=CC=C2)C(=O)NC(C(C)C)C(=O)OC",
            "AMB-CHMICA": "CC(C)C(C(=O)OC)NC(=O)C1=CN(CC2CCCCC2)C3=C1C=CC=C3",
            "AMB-CHMINACA": "CC(C)C(C(=O)OC)NC(=O)C1=NN(CC2CCCCC2)C3=C1C=CC=C3",
            "AMB-FUBICA": "CC(C)C(C(=O)OC)NC(=O)C1=CN(CC2=CC=C(C=C2)F)C3=C1C=CC=C3",
            "AMB-FUBINACA": "CC(C)C(C(=O)OC)NC(=O)C1=NN(CC2=CC=C(C=C2)F)C3=C1C=CC=C3",
            "Apinaca": "CCCCCN1C2=C(C=CC=C2)C(=N1)C(=O)NC34CC5CC(CC(C5)C3)C4",
            "A-PONASA": "CCCCCOC1=C2C=CC=CC2=C(C=C1)S(=O)(=O)NC3CC4CC(CC(C4)C3)C5",
            "APP-BINACA": "CCCCN1C2=C(C=CC=C2)C(=N1)C(=O)NC(CC3=CC=CC=C3)C(=O)N",
            "APP-CHMINACA": "CCN(C(CC1=CC=CC=C1)C(=O)N)C(=O)C2=NN(CC3CCCCC3)C4=C2C=CC=C4",
            "APP-FUBINACA": "CCN(C(CC1=CC=CC=C1)C(=O)N)C(=O)C2=NN(CC3=CC=C(C=C3)F)C4=C2C=CC=C4",
            "BENZYL-4CN-BINACA": "C1=CC=C(C=C1)CNC(=O)C2=NN(CCCCC#N)C3=C2C=CC=C3",
            "CBL-018": "CCCCCN1C=C(C2=C1C=CC=C2)C(=O)OC3=CC=CC4=C3C=CC=C4",
            "CH-FUBBMPDORA": "FC1=CC=C(CN2C(C(NC(C3CCCCC3)=O)=C(C)C(Br)=C2)=O)C=C1",
            "CH-FUBIACA": "C1CCC(CC1)NC(=O)CC2=CN(CC3=CC=C(C=C3)F)C4=C2C=CC=C4",
            "CH-IACA": "C1CCC(CC1)NC(=O)CC2=CNC3=C2C=CC=C3",
            "CHM-MDA-19 (BZO-CHMOXIZID)": "C1CCC(CC1)CN2C3=C(C=CC=C3)/C(=N/NC(=O)C4=CC=CC=C4)/C2=O",
            "CHM-MDMB-CHMINACA": "CC(C)(C)C(C(=O)OCC1CCCCC1)NC(=O)C2=NN(CC3CCCCC3)C4=C2C=CC=C4",
            "CH-PIACA": "CCCCCN1C=C(CC(=O)NC2CCCCC2)C3=C1C=CC=C3",
            "CP 47,497": "CCCCCCC(C)(CCCCCC)C1=CC=C([C@@H]2CCC[C@@H](C2)O)C(=C1)O",
            "CRA-13": "CCCCCOC1=C2C=CC=CC2=C(C=C1)C(=O)C3=CC=CC4=C3C=CC=C4",
            "CUMYL-1Cl-CHSINACA": "CCC(C)(C1=CC=CC=C1)NC(=O)C2=NN(C3=C2C=CC=C3)S(=O)(=O)C4(CCCCC4)Cl",
            "CUMYL-4CN-B7AICA": "CCC(C)(C1=CC=CC=C1)NC(=O)C2=CN(CCCCC#N)C3=C2C=CC=N3",
            "CUMYL-4CN-BINACA": "CCC(C)(C1=CC=CC=C1)NC(=O)C2=NN(CCCCC#N)C3=C2C=CC=C3",
            "CUMYL-5F-P7AICA": "CC(C)(C1=CC=CC=C1)NC(=O)C2=CN(CCCCCF)C3=C2C=CC=N3",
            "CUMYL-5FPICA": "CC(C)(C1=CC=CC=C1)NC(=O)C2=CN(CCCCCF)C3=C2C=CC=C3",
            "CUMYL-5FPINACA": "CC(C)(C1=CC=CC=C1)NC(=O)C2=NN(CCCCCF)C3=C2C=CC=C3",
            "Cumyl-BC-HpMeGaClone-221": "CC(C)(C1=CC=CC=C1)N2C=CC3=C(C4=C(C=CC=C4)N3)C2=O",
            "CUMYL-BICA": "CCCCN1C=C(C2=C1C=CC=C2)C(=O)NC(C)(C)C3=CC=CC=C3",
            "Cumyl-CB-MeGaClone": "CCC(C)(C1=CC=CC=C1)N2C=CC3=C(C4=C(C=CC=C4)N3CC5CCC5)C2=O",
            "CUMYL-CBMICA": "CC(C)(C1=CC=CC=C1)NC(=O)C2=CN(CC3CCC3)C4=C2C=CC=C4",
            "CUMYL-CBMINACA": "CC(C)(C1=CC=CC=C1)NC(=O)C2=NN(CC3CCC3)C4=C2C=CC=C4",
            "Cumyl-CH-MeGaClone": "CCC(C)(C1=CC=CC=C1)N2C=CC3=C(C4=C(C=CC=C4)N3CC5CCCCC5)C2=O",
            "CUMYL-CHSINACA": "CC(C)(C1=CC=CC=C1)NC(=O)C2=NN(C3=C2C=CC=C3)S(=O)(=O)C4CCCCC4",
            "CUMYL-INACA": "C[C@@](C)(C1=CC=CC=C1)NC(=O)C2=NNC3=C2C=CC=C3",
            "CUMYL-NBMICA": "CC(C)(C=S)NC(=O)C1=CN(CB(B)O)C2=C1C=CC=C2",
            "CUMYL-NBMINACA": "CC(C)(C1=CC=CC=C1)NC(=O)C2=NNC3=C2C=CC=C3",
            "CUMYL-PeGACLONE": "CCCCCN1C2=C(C=CC=C2)C3=C1C=CN(C3=O)C(C)(CC)C4=CC=CC=C4",
            "CUMYL-PICA": "CCCCCN1C=C(C2=C1C=CC=C2)C(=O)NC(C)(C)C3=CC=CC=C3",
            "CUMYL-PINACA": "CCCCCN1C2=C(C=CC=C2)C(=N1)C(=O)NC(C)(C)C3=CC=CC=C3",
            "CUMYL-THPINACA": "CC(C)(C1=CC=CC=C1)NC(=O)C2=NN(C3=CC=CC=C32)CC4CCOCC4",
            "CUMYL-TsINACA": "CC(C)(C1=CC=CC=C1)NC(=O)C2=NNC3=C2C=CC=C3",
            "DMBA-CHMINACA": "CC(C)(C)C(C(=O)O)NC(=O)C1=NN(CC2CCCCC2)C3=C1C=CC=C3",
            "EAM-2201": "CCC1=CC=C(C2=C1C=CC=C2)C(=O)C3=CN(CCCCCF)C4=C3C=CC=C4",
            "EDMB-PINACA": "CCCCCN1C2=C(C=CC=C2)C(=N1)C(=O)NC(C(=O)OCC)C(C)(C)C",
            "EG-018": "CCCCCN1C2=C(C=CC=C2)C3=CC(=CC=C31)C(=O)C4=CC=CC5=C4C=CC=C5",
            "EG-2201": "C(CCF)CCN1C2=C(C=CC=C2)C3=CC(=CC=C31)C(=O)C4=CC=CC5=C4C=CC=C5",
            "EMB-FUBINACA": "CCOC(=O)C(C(C)C)NC(=O)C1=NN(CC2=CC=C(C=C2)F)C3=C1C=CC=C3",
            "FDU-PB-22": "C1=CC2=C(C=C1)C(=CC=C2)OC(=O)C3=CN(CC4=CC=C(C=C4)F)C5=C3C=CC=C5",
            "FUB-144": "CC1(C)C(C(=O)C2=CN(CC3=CC=C(C=C3)F)C4=C2C=CC=C4)C1(C)C",
            "FUB-AKB48": "C1=CC2=C(C=C1)N(CC3=CC=C(C=C3)F)N=C2C(=O)NC45CC6CC(CC(C6)C4)C5",
            "FUBIAT": "CC(=O)O",
            "FUB-JWH-018": "C1=CC2=C(C=C1)C(=CC=C2)C(=O)C3=CN(CC4=CC=C(C=C4)F)C5=C3C=CC=C5",
            "FUB-NPB-22": "C1=CC2=C(C=C1)N=CC=C2",
            "FUB-PB-22": "C1=CC=C2C(=C1)C(=CN2CC3=CC=C(C=C3)F)C(=O)OC4=CC=CC5=C4N=CC=C5",
            "Hexahydrocannabinol (HHC)": "CCCCCC1=CC2=CC(C)(C)C3CCC(C)CC3C2=C(O)O1",
            "Hexahydrocannabinol acetate (HHC acetate)": "CCCCCC1=CC2=C(C3CC(C)CCC3C(C)(C)O2)C(=C1)OC(=O)C",
            "Hexahydrocannabiphorol (HHC-P)": "CCCCCCCC1=CC2=CC(C)(C)C3CCC(C)CC3C2=C(O)O1",
            "HU-210": "CCCCCCC(C)(C)C1=CC2=C([C@@H]3CC(=CC[C@H]3C(C)(C)O2)CO)C(=C1)O",
            "HU-331": "CCCCCC1=CC=CC2=NC(=C(C(=C12)C3=C(C=CC=C3)N=C4C=CC=C(CCCCC)C4=C3)O)C5C=C(C)CCC5CC=C",
            "JTE-907": "CCCCCOC1=C(C=CC2=CC(=C(N=C21)O)C(=O)NCC3=CC=C4C(=C3)OCO4)OC",
            "JWH-007": "CCCCCN1C(=C(C2=C1C=CC=C2)C(=O)C3=CC=CC4=C3C=CC=C4)C",
            "JWH-015": "CCCN1C(=C(C2=C1C=CC=C2)C(=O)C3=CC=CC4=C3C=CC=C4)C",
            "JWH-018": "CCCCCN1C=C(C2=C1C=CC=C2)C(=O)C3=CC=CC4=C3C=CC=C4",
            "JWH-018 adamantoyl derivative (AB-001)": "CCCCCN1C=C(C2=C1C=CC=C2)C(=O)C34CC5CC(CC(C5)C3)C4",
            "JWH-018 adamantyl carboxamide (Apica)": "CCCCCN1C=C(C2=C1C=CC=C2)C(=NC34CC5CC(CC(C5)C3)C4)O",
            "JWH-018 cyclohexymethyl derivative": "C1CCC(CC1)CN2C=C(C3=C2C=CC=C3)C(=O)C4=CC=CC5=C4C=CC=C5",
            "JWH-018 indazole analogue": "CCCCCN1C2=C(C=CC=C2)C(=N1)C(=O)C3=CC=CC4=C3C=CC=C4",
            "JWH-018 N-(5-bromopentyl) derivative": "C(CCBr)CCN1C=C(C2=C1C=CC=C2)C(=O)C3=CC=CC4=C3C=CC=C4",
            "JWH-018 N-(5-chloropentyl) derivative": "C(CCCl)CCN1C=C(C2=C1C=CC=C2)C(=O)C3=CC=CC4=C3C=CC=C4",
            "JWH-018 quinolinecarboxylate analogue (PB-22)": "CCCCCN1C=C(C2=C1C=CC=C2)C(=O)OC3=C4C(=CC=C3)C=CC=N4",
            "JWH-019": "CCCCCCN1C=C(C2=C1C=CC=C2)C(=O)C3=CC=CC4=C3C=CC=C4",
            "JWH-022": "C=CCCCN1C=C(C2=C1C=CC=C2)C(=O)C3=CC4=C(C=CC=C4)C=C3",
            "JWH-030": "CCCCCN1C=CC(=C1)C(=O)C2=CC=CC3=C2C=CC=C3",
            "JWH-071": "CCN1C=C(C2=C1C=CC=C2)C(=O)C3=CC=CC4=C3C=CC=C4",
            "JWH-073": "CCCCN1C=C(C2=C1C=CC=C2)C(=O)C3=CC=CC4=C3C=CC=C4",
            "JWH-073 methyl derivative": "CCCCN1C=C(C2=CC=CC=C21)C(=O)C3=CC=C(C4=CC=CC=C43)OC",
            "JWH-081": "CCCCCN1C=C(C2=C1C=CC=C2)C(=O)C3=C4C=CC=CC4=C(C=C3)OC",
            "JWH-122": "CCCCCN1C=C(C2=C1C=CC=C2)C(=O)C3=CC=C(C)C4=C3C=CC=C4",
            "JWH-122 pentenyl 2-methylindole derivative": "C=CCCCN1C(=C(C2=C1C=CC=C2)C(=O)C3=CC=C(C)C4=C3C=CC=C4)C",
            "JWH-122 pentenyl derivative": "C=CCCC(C)N1C=C(C2=C1C=CC=C2)C(=O)C3=CC=C(C)C4=C3C=CC=C4",
            "JWH-145": "CCCCCN1C=C(C=C1C2=CC=CC=C2)C(=O)C3=CC4=C(C=CC=C4)C=C3",
            "JWH-182": "CCCCCN1C=C(C2=C1C=CC=C2)C(=O)C3=CC=C(CCC)C4=C3C=CC=C4",
            "JWH-200": "C1COCCN1CCN2C=C(C3=CC=CC=C32)C(=O)C4=CC=CC5=CC=CC=C54",
            "JWH-203": "CCCCCN1C=C(C2=C1C=CC=C2)C(=O)CC3=C(C=CC=C3)Cl",
            "JWH-210": "CCCCCN1C=C(C2=C1C=CC=C2)C(=O)C3=CC=C(CC)C4=C3C=CC=C4",
            "JWH-250": "CCCCCN1C=C(C2=C1C=CC=C2)C(=O)CC3=C(C=CC=C3)OC",
            "JWH-250 1-(2-methylene-N-methyl-piperidyl) derivative": "CN1CCCCC1CN2C=C(C3=C2C=CC=C3)C(=O)CC4=C(C=CC=C4)OC",
            "JWH-251": "CCCCCN1C=C(C2=C1C=CC=C2)C(=O)C[13CH2][18OH]",
            "JWH-302": "CCCCCN1C=C(C2=C1C=CC=C2)C(=O)CC3=CC=CC(=C3)OC",
            "JWH-307": "CCCCCN1C=C(C=C1C2=C(C=CC=C2)F)C(=O)C3=CC=CC4=C3C=CC=C4",
            "JWH-307 brominated analogue": "CCCCCN1C=C(C=C1C2=C(C=CC=C2)Br)C(=O)C3=CC=CC4=C3C=CC=C4",
            "JWH-368": "CCCCCN1C=C(C=C1C2=CC(=CC=C2)F)C(=O)C3=CC=CC4=C3C=CC=C4",
            "JWH-370": "CCCCCN1C=C(C=C1[14C](=O)C2=CC=CC=C2)C(=O)C3=CC4=C(C=CC=C4)C=C3",
            "JWH-387": "CCCCCN1C=C(C2=C1C=CC=C2)C(=O)C3=C4C=CC=CC4=C(C=C3)Br",
            "JWH-398": "CCCCCN1C=C(C2=C1C=CC=C2)C(=O)C3=C4C=CC=CC4=C(C=C3)Cl",
            "JWH-412": "CCCCCN1C=C(C2=C1C=CC=C2)C(=O)C3=C4C=CC=CC4=C(C=C3)F",
            "JWH-412 5-fluoropentyl derivative": "C(CCF)CCN1C=C(C2=C1C=CC=C2)C(=O)C3=C4C=CC=CC4=C(C=C3)F",
            "JWH-methylcyclohexane-8quinolinol (BB-22)": "C(N1C=2C(C(C(OC=3C4=C(C=CC3)C=CC=N4)=O)=C1)=CC=CC2)C5CCCCC5",
            "LTI-701": "C1=CC=C(C=C1)NC(=O)C2=CN(CCCCCF)C3=C2C=CC=C3",
            "LY2183240": "CN(C)C(=O)N1C(=NN=N1)CC2=CC=C(C=C2)C3=CC=CC=C3",
            "M5FPIC": "COC(=O)C1=CN(CCCCCF)C2=C1C=CC=C2",
            "MAM-2201": "CC1=CC=NC2=C1C=CC=C2",
            "MAM-2201 chloropentyl derivative": "CC1=CC=NC2=C1C=CC=C2",
            "MBA-CHMINACA": "CC(C)C(C(=O)O)NC(=O)C1=NN(CC2CCCCC2)C3=C1C=CC=C3",
            "M-CHMIC": "COC(=O)C1=CN(CC2CCCCC2)C3=C1C=CC=C3",
            "MDA 19 (BZO-HEXOXIZID)": "CCCCCCN1C2=C(C=CC=C2)/C(=N/NC(=O)C3=CC=CC=C3)/C1=O",
            "MDA-19 4en-pentyl analogue (BZO-4en-POXIZID)": "C=CCCCN1C2=C(C=CC=C2)/C(=N/NC(=O)C3=CC=CC=C3)/C1=O",
            "MDA-19 5-fluoropentyl analogue (5F-BZO-POXIZID)": "C1=CC=C(C=C1)C(=O)N/N=C\2/C3=C(C=CC=C3)N(CCCCCF)C2=O",
            "MDA-19 pentyl analogue (BZO-POXIZID)": "CCCCCN1C2=C(C=CC=C2)/C(=N/NC(=O)C3=CC=CC=C3)/C1=O",
            "MDMB-4en-PINACA": "C=CCCC(C(=O)OC)NC(=O)C1=NNC2=C1C=CC=C2",
            "MDMB-5Br-INACA": "CCOC(=O)C(C(C)(C)C)NC(=O)C1=NNC2=C1C=C(C=C2)Br",
            "MDMB-7Br-INACA": "CCOC(=O)C(C(C)(C)C)NC(=O)C1=NNC2=C1C=CC=C2Br",
            "MDMB-CHMCZCA": "CCCN=C(C1=CC=C2C(=C1)C3=C(C=CC=C3)N2CC4CCCCC4)O",
            "MDMB-CHMICA": "CC(C)(C)C(C(=O)OC)NC(=O)C1=CN(CC2CCCCC2)C3=C1C=CC=C3",
            "MDMB-CHMINACA": "CC(C)(C)C(C(=O)OC)NC(=O)C1=NN(C2=CC=CC=C21)CC3CCCCC3",
            "MDMB-FUBICA": "CC(C)(C)C(C(=O)OC)NC(=O)C1=CN(CC2=CC=C(C=C2)F)C3=C1C=CC=C3",
            "MDMB-FUBINACA": "CC(C)(C)C(C(=O)OC)NC(=O)C1=NN(CC2=CC=C(C=C2)F)C3=C1C=CC=C3",
            "MDMB-INACA": "CCOC(=O)C(C(C)(C)C)NC(=O)C1=NNC2=C1C=CC=C2",
            "MDMB-PCZCA": "CCCCCN1C2=C(C=CC=C2)C3=CC(=CC=C31)C(=O)NC(C(=O)OC)C(C)(C)C",
            "Mepirapim": "CCCCCN1C=C(C2=C1C=CC=C2)C(=O)N3CCN(C)CC3",
            "Methanandamide": "CCCCC/C=C\C/C=C\C/C=C\C/C=C\CCCC(=O)NC(C)C(C)O",
            "MN-18": "CCCCCN1C2=C(C=CC=C2)C(=N1)C(=O)NC3=CC=CC4=C3C=CC=C4",
            "MO-CHMINACA": "CC(C)(C)C(C(=O)OC)OC(=O)C1=NN(CC2CCCCC2)C3=C1C=CC=C3",
            "MPhP-2201": "COC(=O)C(CC1=CC=CC=C1)NC(=O)C2=CN(C3=CC=CC=C32)CCCCCF",
            "NM-2201": "C(CCF)CCN1C=C(C2=C1C=CC=C2)C(=O)OC3=CC=CC4=C3C=CC=C4",
            "Org 27569": "CCC1=C(NC2=C1C=C(C=C2)Cl)C(=O)NCCC3=CC=C(C=C3)N4CCCCC4",
            "Org 27759": "CCC1=C(NC2=C1C=C(C=C2)F)C(=O)NCCC3=CC=C(C=C3)N(C)C",
            "Org 29647": "CCC1=C(C(=O)NC2CCN(CC3=CC=CC=C3)C2)NC4=C1C=C(C=C4)Cl",
            "PB-22 indazole analogue": "CCCCCN1C2=C(C=CC=C2)C(=N1)C(=O)OC3=C4C(=CC=C3)C=CC=N4",
            "PTI-1": "CCCCCN1C=C(C2=C1C=CC=C2)N3C=C(CN(CC)CC)C=S3",
            "PTI-2": "CCCCCN1C=C(C2=C1C=CC=C2)N3C=C(CN(CCOC)C(C)C)C=S3",
            "PTI-3": "CN(CCOC)CC1=CSC(=N1)C2=CN(C3=CC=CC=C32)CCCCCF",
            "RCS-4": "CCCCCN1C=C(C2=C1C=CC=C2)C(=O)C3=CC=C(C=C3)OC",
            "RCS-4 ortho isomer": "CCCCCN1C=C(C2=C1C=CC=C2)C(=O)C3=C(C=CC=C3)OC",
            "RCS-4(C4)": "CCCCN1C=C(C2=C1C=CC=C2)C(=O)C3=CC=C(C=C3)OC",
            "SDB-005": "CCCCCN1C2=C(C=CC=C2)C(=N1)C(=O)OC3=CC=CC4=C3C=CC=C4",
            "SDB-006": "CCCCCN1C=C(C2=C1C=CC=C2)C(=O)NCC3=CC=CC=C3",
            "SDB-006 N-phenyl analogue": "CCCCCN1C=C(C2=C1C=CC=C2)C(=O)NC3=CC=CC=C3",
            "Spice": "CC(C)C12CCC(=C)C1C2",
            "STS-135": "C(CCF)CCN1C=C(C2=C1C=CC=C2)C(=NC34CC5CC(CC(C5)C3)C4)O",
            "trans-CP 47,497-C8": "CCCCCCCC(C)(C)C1=CC=C([C@H]2CCC[C@@H](C2)O)C(=C1)O",
            "UR -144 (-2H)": "C=CCCC(C=O)N1C=C(C2=C1C=CC=C2)C(=O)C3C(C)(C)C3(C)C",
            "UR-144": "CCCCCN1C=C(C2=C1C=CC=C2)C(=O)C3C(C)(C)C3(C)C",
            "UR-144 degradant": "CCCCCN1C=C(C2=C1C=CC=C2)C(=O)CC(C)(C)C(=C)C",
            "UR-144 heptyl derivative": "CCCCCCCN1C=C(C2=C1C=CC=C2)C(=O)C3C(C)(C)C3(C)C",
            "UR-144 N-(5-chloropentyl) derivative": "CC1(C)C(C(=O)C2=CN(CCCCCCl)C3=C2C=CC=C3)C1(C)C",
            "URB-597": "C1CCC(CC1)OC(=O)N",
            "URB-754": "CC1=CC=C(C=C1)NC2=NC3=C(C=C(C=C3)C)C(=O)O2",
            "WIN 48,098 (Pravadoline)": "CC1=C(C2=C(C=CC=C2)N1CCN3CCOCC3)C(=O)C4=CC=C(C=C4)OC",
            "WIN 55212-2": "CC1=C(C2=C3N1C(COC3=CC=C2)CN4CCOCC4)C(=O)C5=CC=CC6=CC=CC=C65",
            "1-(2,3-dihydro-1H-inden-5-yl)-2-phenyl-2-(pyrrolidinyl-1-yl)ethan-1-one": "C1=CC=C(C=C1)C(C(=O)C2=CC=C3CCCC3=C2)N4CCCC4",
            "1-(4-fluorophenyl)-2-(piperidin-1-yl)pentan-1-one": "CCCC(C(=O)C1=CC=C(C=C1)F)N2CCCCC2",
            "1-naphyrone": "CCCC(C(=O)C1=CC=CC2=C1C=CC=C2)N3CCCC3",
            "2-(4-Methylpiperazin-1-yl)-1-phenylpropan-1-one": "CC(C(=O)C1=CC=CC=C1)N2CCN(C)CC2",
            "2,4,5-Trimethylmethcathinone (2,4,5-TMMC)": "CC1=C(C)C=C(C(=C1)C)C(=O)C(C)NC",
            "2,4-DMEC": "CCNC(C)C(=O)C1=CC=C(C)C=C1C",
            "2,4-DMMC": "CC1=CC=C(C(=C1)C)C(=O)C(C)NC",
            "2,4-DMPPP": "CC1=CC=C(C(=C1)C)C(=O)C(C)N2CCCC2",
            "2-Benzylamino-1-(3,4-methylenedioxyphenyl)butan-1-one (BMDB)": "CCC(C(=O)C1=CC=C2C(=C1)OCO2)NCC3=CC=CC=C3",
            "2-Benzylamino-1-(3,4-methylenedioxyphenyl)propan-1-one (BMDP)": "CC(C(=O)C1=CC=C2C(=C1)OCO2)NCC3=CC=CC=C3",
            "2-fluoromethcathinone (2-FMC)": "CC(C(=O)C1=C(C=CC=C1)F)NC",
            "2-MEC": "CCNC(C)C(=O)C1=C(C)C=CC=C1",
            "2'-Me-PVP": "CCCC(C(=O)C1=C(C)C=CC=C1)N2CCCC2",
            "2-methylethylbuphedrone (2-MEB)": "CCC(C(=O)C1=C(C)C=CC=C1)NCC",
            "2-methylmethcathinone (2-MMC)": "CC1=C(C=CC=C1)C(=O)C(C)NC",
            "2-Methyl-α-PHiP": "CCC(C)CC(C(=O)C1=C(C)C=CC=C1)N2CCCC2",
            "3',4'- Methylenedioxy-α-methylPPP (MDMPP)": "CC(C)(C(=O)C1=CC=C2C(=C1)OCO2)N3CCCC3",
            "3,4-dichloroethcathinone (3,4-DCEC)": "CCNC(C)C(=O)C1=CC=C(C(=C1)Cl)Cl",
            "3,4-Dichloro-N,N-cyclohexylmethylmethcathinone": "CC(C(=O)C1=CC=C(C(=C1)Cl)Cl)N(C)C2CCCCC2",
            "3,4-Dimethylethcathinone (3,4-DMEC)": "CCNC(C)C(=O)C1=CC=C(C)C(=C1)C",
            "3,4-dimethylmethcathinone (3,4-DMMC)": "CC1=CC=C(C=C1C)C(=O)C(C)NC",
            "3,4-DMeO-α-PHP": "CCCCC(C(=O)C1=CC=C(C(=C1)OC)OC)N2CCCC2",
            "3,4-DMeO-α-PVP": "CCCC(C(=O)C1=CC=C(C(=C1)OC)OC)N2CCCC2",
            "3,4-Methylenedioxypyrovalerone (MDPV)": "CCCC(C(=O)C1=CC2=C(C=C1)OCO2)N3CCCC3.Cl",
            "3',4'-Methylenedioxy-α-pyrrolidinobutyrophenone (MDPBP)": "CCC(C(=O)C1=CC=C2C(=C1)OCO2)N3CCCC3",
            "3,4-Pr-PipVP": "CCCC(C(=O)C1=CC2=C(CC=C2)C=C1)N3CCCCC3",
            "3’,4'-Methylenedioxy-α-PPP (MDPPP)": "CC(C(=O)C1=CC=C2C(=C1)OCO2)N3CCCC3",
            "3-bromomethcathinone (3-BMC)": "CC(C(=O)C1=CC=CC(=C1)Br)NC",
            "3-CEC": "CCNC(C)C(=O)C1=CC=CC(=C1)Cl",
            "3-Chlorocathinone": "CC(=N)C(=O)C1=CC=CC(=C1)Cl",
            "3-CMC (3-chloromethcathinone)": "CC(C(=O)C1=CC=CC(=C1)Cl)NC",
            "3-fluoromethcathinone (3-FMC)": "CC(C(=O)C1=CC=CC(=C1)F)NC",
            "3F-NEB": "CCC(C(=O)C1=CC=CC(=C1)F)NCC",
            "3F-N-ethylhexedrone": "CCCCC(C(=O)C1=CC=CC(=C1)F)NCC",
            "3F-α-PHiP": "CC(C)CC(C(=O)C1=CC=CC(=C1)F)N2CCCC2",
            "3F-α-PHP": "CCCCC(C(=O)C1=CC=CC(=C1)F)N2CCCC2",
            "3F-α-PVP": "CCCC(C(=O)C1=CC=CC(=C1)F)N2CCCC2",
            "3-MEC": "CCNC(C)C(=O)C1=CC(=CC=C1)C",
            "3-methoxymethcathinone (3-MeOMC)": "CC(C(=O)C1=CC=CC(=C1)OC)NC",
            "3-methylflephedrone": "CC1=CC(=CC=C1F)C(=O)C(C)NC",
            "3-Methylmethcathinone (3-MMC)": "CC1=CC=CC(=C1)C(=O)C(C)NC",
            "3-Methyl-N-propyl-cathinone": "CCCNC(C)C(=O)C1=CC(=CC=C1)C",
            "4’-chloro-α-PPP": "CC(C(=O)C1=CC=C(C=C1)Cl)N2CCCC2",
            "4’-ethyl-α-PVP": "CCCC(C(=O)C1=CC=C(CC)C=C1)N2CCCC2",
            "4’-methylhexedrone": "CCCCC(C(=O)C1=CC=C(C)C=C1)NC",
            "4’-methyl-α-PPP (MPPP)": "CCC[13C](=O)C(C)N1CCCC1",
            "4’-Methyl-α-pyrrolidinobutyrophenone (MPBP)": "CCC(C(=O)C1=CC=C(C)C=C1)N2CCCC2",
            "4-BEC": "CCNC(C)C(=O)C1=CC=C(C=C1)Br",
            "4Br-α-PPP": "CC(C(=O)C1=CC=C(C=C1)Br)N2CCCC2",
            "4Br-α-PVP": "CCCC(C(=O)C1=CC=C(C=C1)Br)N2CCCC2",
            "4-CEC": "CCNC(C)C(=O)C1=CC=C(C=C1)Cl",
            "4-chloro-N,N-dimethylcathinone": "CC(C(=O)C1=CC=C(C=C1)Cl)N(C)C",
            "4-chloro-N-butylcathinone": "CCCCNC(C)C(=O)C1=CC=C(C=C1)Cl",
            "4-chloropentedrone": "CCCC(C(=O)C1=CC=C(C=C1)Cl)NC",
            "4-CIC": "CCCNC(C)C(=O)C1=CC=C(C=C1)Cl",
            "4-Cl-3-MMC": "CC1=CC(=CC=C1Cl)C(=O)C(C)NC",
            "4-Cl-α-PVP": "CCCC(C(=O)C1=CC=C(C=C1)Cl)N2CCCC2",
            "4-ethylethcathinone (4-EEC)": "CCC1=CC=C(C=C1)C(=O)C(C)NCC",
            "4-Ethylmethcathinone (4-EMC)": "CCC1=CC=C(C=C1)C(=O)C(C)NC",
            "4F-3-methyl-α-PHP": "CCCCC(C(=O)C1=CC=C(C(=C1)C)F)N2CCCC2",
            "4F-3-methyl-α-PVP": "CCCC(C(=O)C1=CC=C(C(=C1)C)F)N2CCCC2",
            "4F-buphedrone": "CCC(C(=O)C1=CC=C(C=C1)F)NC",
            "4-Fluorocathinone": "CC(C(=O)C1=CC=C(C=C1)F)N",
            "4-fluoroethcathinone (4-FEC)": "CCNC(C)C(=O)C1=CC=C(C=C1)F",
            "4-fluoro-N-ethylpentedrone": "CCCC(C(=O)C1=CC=C(C=C1)F)NCC",
            "4-fluoro-N-isopropylnorpentedrone": "CCCC(C(=O)C1=CC=C(C=C1)F)NC(C)C",
            "4-Fluoropentedrone": "CCCC(C(=O)C1=CC=C(C=C1)F)NC",
            "4F-NEB": "CCC(C(=O)C1=CC=C(C=C1)F)NCC",
            "4F-PBP": "CCC(C(=O)C1=CC=C(C=C1)F)N2CCCC2",
            "4F-α-PEP (4F-PV8)": "CCCCCC(C(=O)C1=CC=C(C=C1)F)N2CCCC2",
            "4F-α-PHiP": "CC(C)CC(C(=O)C1=CC=C(C=C1)F)N2CCCC2",
            "4-F-α-PHP": "CCCCC(C(=O)C1=CC=C(C=C1)F)N2CCCC2",
            "4F-α-POP (4F-PV9)": "CCCCCCC(C(=O)C1=CC=C(C=C1)F)N2CCCC2",
            "4F-α-PVP": "CCCC(C(=O)C1=CC=C(C=C1)F)N2CCCC2",
            "4-MeO-alpha-PVP": "CCCC(C(=O)C1=CC=C(C=C1)OC)N2CCCC2",
            "4-MeO-α-PBP": "CCC(C(=O)C1=CC=C(C=C1)OC)N2CCCC2",
            "4-MeO-α-PEP (4-MeO-α-PV8)": "CCCCCC(C(=O)C1=CC=C(C=C1)OC)N2CCCC2",
            "4-MeO-α-PV9": "CCCCCCC(C(=O)C1=CC=C(C=C1)OC)N2CCCC2",
            "4'-Methoxy-α-PPP (MOPPP)": "CC(C(=O)C1=CC=C(C=C1)OC)N2CCCC2",
            "4-Methylbuphedrone (4-Me-MABP)": "CCC(C(=O)C1=CC=C(C)C=C1)NC",
            "4-methylbuphedrone, N-benzyl derivative": "CCC(C(=O)C1=CC=C(C)C=C1)NCC2=CC=CC=C2",
            "4-methylethcathinone (4-MEC)": "CCNC(C)C(=O)C1=CC=C(C)C=C1",
            "4-methyl-N,N-diethylcathinone": "CCN(CC)C(C)C(=O)C1=CC=C(C)C=C1",
            "4-Methyl-N,N-dimethylcathinone": "CC1=CC=C(C=C1)C(=O)C(C)N(C)C",
            "4-Methyl-N-ethylnorpentedrone": "CCCC(C(=O)C1=CC=C(C)C=C1)NCC",
            "4'-methyl-NiPP": "CCCC(C(=O)C1=CC=C(C)C=C1)NC(C)C",
            "4-methylpentedrone": "CCCC(C(=O)C1=CC=C(C)C=C1)NC",
            "4'-methyl-α-PiHP": "CC(C)CC(C(=O)C1=CC=C(C)C=C1)N2CCCC2",
            "4'-Methyl-α-pyrrolidinohexanophenone (MPHP)": "CCCCC(C(=O)C1=CC=C(C=C1)C)N2CCCC2",
            "5-BPDi": "CCCCC(C(=O)C1=CC=C2CCCC2=C1)N3CCCC3",
            "5-DBFPV": "CCCC(C(=O)C1=CC=C2C(=C1)CCO2)N3CCCC3",
            "5-PPDi": "CCC(C(=O)C1=CC=C2CCCC2=C1)N3CCCC3",
            "alpha-pyrrolidinononaphenone (α-PNP)": "CCCCCCCC(C(=O)C1=CC=CC=C1)N2CCCC2",
            "AMAPN": "CC(C(=O)C1=CC=CC2=C1C=CC=C2)NC",
            "Benzedrone (4-MBC)": "CC1=CC=C(C=C1)C(=O)C(C)NCC2=CC=CC=C2",
            "bk-2C-B": "COC1=C(C=C(C(=C1)Br)OC)C(=O)CN",
            "bk-IBP": "CCC(C(=O)C1=CC=C2CCCC2=C1)NCC",
            "bk-IMP": "CC(C(=O)C1=CC2=CC=C2C=C1)NC",
            "bk-IVP": "CCCC(C(=O)C1=CC=C2CCCC2=C1)NCC",
            "bk-PBDB": "CCCNC(CC)C(=O)C1=CC=C2C(=C1)OCO2",
            "Brephedrone (4-BMC)": "CC(C(=O)C1=CC=C(C=C1)Br)NC",
            "Buphedrone": "CCC(C(=O)C1=CC=CC=C1)NC",
            "Bupropion": "CC(C(=O)C1=CC(=CC=C1)Cl)NC(C)(C)C",
            "Butylone (bk-MBDB)": "CCC(C(=O)C1=CC=C2C(=C1)OCO2)NC",
            "Clephedrone (4-CMC)": "CC(C(=O)C1=CC=C(C=C1)Cl)NC",
            "Dibutylone (bk-MMBDB)": "CCC(C(=O)C1=CC=C2C(=C1)OCO2)N(C)C",
            "Dimethylone (bk-MDDMA)": "CC(C(=O)C1=CC=C2C(=C1)OCO2)N(C)C",
            "Dipentylone": "CCCC(C(=O)C1=CC=C2C(=C1)OCO2)N(C)C",
            "DL-4662": "CCCC(C(=O)C1=CC=C(C(=C1)OC)OC)NCC",
            "Ephylone": "CCCC(C(=O)C1=CC=C2C(=C1)OCO2)NCC",
            "Ethylcathinone": "CCNC(C)C(=O)C1=CC=CC=C1",
            "Ethylone (bk-MDEA)": "CCNC(C)C(=O)C1=CC=C2C(=C1)OCO2",
            "Eutylone": "CCC(C(=O)C1=CC=C2C(=C1)OCO2)NCC",
            "Flephedrone (4-FMC)": "CC(C(=O)C1=CC=C(C=C1)F)NC",
            "Hexedrone (β-propylmethcathinone)": "CCCCC(C(=O)C1=CC=CC=C1)NC",
            "Hexylone": "CCCCC(C(=O)C1=CC=C2C(=C1)OCO2)NC",
            "Isohexedrone": "CC(C)CC(C(=O)C1=CC=CC=C1)NC",
            "Isohexylone": "CC(C)CC(C(=O)C1=CC=C2C(=C1)OCO2)NC",
            "MDPEP": "CCCCCC(C(=O)C1=CC=C2C(=C1)OCO2)N3CCCC3",
            "MDPHiP": "CC(C)CC(C(=O)C1=CC=C2C(=C1)OCO2)N3CCCC3",
            "MDPHP": "CCCCC(C(=O)C1=CC=C2C(=C1)OCO2)N3CCCC3",
            "Mephedrone": "CC1=CC=C(C=C1)C(=O)C(C)NC",
            "Metamfepramone": "CC(C(=O)C1=CC=CC=C1)N(C)C",
            "Methedrone (bk-PMMA)": "O=C(c1ccc(OC)cc1)C(NC)C",
            "Methylone (bk-MDMA)": "CC(NC)C(=O)C1=CC=C(OCO2)C2=C1",
            "Mexedrone": "CC1=CC=C(C=C1)C(=O)C(COC)NC",
            "N,N-diethylpentylone": "CCCC(C(=O)C1=CC=C2C(=C1)OCO2)N(CC)CC",
            "Naphyrone": "CCCC(C(=O)C1=CC2=C(C=CC=C2)C=C1)N3CCCC3",
            "N-butylbutylone": "CCC(NCCCC)C(C1=CC=C(OCO2)C2=C1)=O",
            "N-butylhexedrone": "CCCCC(C(=O)C1=CC=CC=C1)NCCCC",
            "N-butylpentylone": "CCCCNC(CCC)C(=O)C1=CC=C2C(=C1)OCO2",
            "N-cyclohexyl methylone": "CC(C(=O)C1=CC=C2C(=C1)OCO2)NC3CCCCC3",
            "NEiH": "CCNC(CC(C)C)C(=O)C1=CC=CC=C1",
            "N-ethylbuphedrone": "CCC(C(=O)C1=CC=CC=C1)NCC",
            "N-ethylheptedrone": "CCCCCC(C(=O)C1=CC=CC=C1)NCC",
            "N-ethylheptylone": "CCCCCC(C(=O)C1=CC=C2C(=C1)OCO2)NCC",
            "N-ethylhexedrone": "CCCCC(C(=O)C1=CC=CC=C1)NCC",
            "N-ethylhexylone": "CCCCC(C(=O)C1=CC=C2C(=C1)OCO2)NCC",
            "N-ethylnorpentedrone": "CCCC(C(=O)C1=CC=CC=C1)NCC",
            "NiPH": "CCCCC(C(=O)C1=CC=CC=C1)NCCC",
            "NiPP": "CCCC(C(=O)C1=CC=CC=C1)NC(C)C",
            "N-methylbenzedrone": "CC1=CC=C(C=C1)C(=O)C(C)N(C)CC2=CC=CC=C2",
            "N-methyl-bk-MMDA-2": "CC(C(=O)C1=C(C=C2C(=C1)OCO2)OC)NC",
            "N-methyl-bk-MMDA-5": "CC(C(=O)C1=CC2=C(C(=C1)OC)OCO2)NC",
            "Nor-mephedrone": "CC1=CC=C(C=C1)C(=O)C(C)N",
            "N-propylnorpentedrone": "CCCC(C(=O)C1=CC=CC=C1)NCCC",
            "pentedrone (β-ethyl-methcathinone)": "CCCC(C(=O)C1=CC=CC=C1)NC",
            "Pentylone": "CCCC(C(=O)C1=CC=C2C(=C1)OCO2)NC",
            "Propylcathinone": "CCCNC(C)C(=O)C1=CC=CC=C1",
            "Propylone": "CCCNC(C)C(=O)C1=CC=C2C(=C1)OCO2",
            "tBuONE": "CC(C(=O)C1=CC=C2C(=C1)OCO2)NC(C)(C)C",
            "TH-PBP": "CCC(C(=O)C1=CC=C2CCCCC2=C1)N3CCCC3",
            "TH-PHP": "CCCCC(C(=O)C1=CC2=C(C=C1)[N+](=[O+])[N+]=[C-]C=N2)N3CCCC3",
            "TH-PVP": "CCCC(C(=O)C1=CC=C2CCCCC2=C1)N3CCCC3",
            "α-PBT": "CCC(C(=O)C1=CC=CS1)N2CCCC2",
            "α-PEP (PV8)": "CCCCCC(C(=O)C1=CC=CC=C1)N2CCCC2",
            "α-PHiP": "CC(C)CC(C(=O)C1=CC=CC=C1)N2CCCC2",
            "α-Piperidinobutiophenone (α-PipBP)": "CCC(C(=O)C1=CC=CC=C1)N2CCCCC2",
            "α-POP (PV9)": "CCCCCCC(C(=O)C1=CC=CC=C1)N2CCCC2",
            "α-PPP-MeO": "COCC(C(=O)C1=CC=CC=C1)N2CCCC2",
            "α-PVT": "CCCC(C(=O)C1=CC=CS1)N2CCCC2",
            "α-pyrrolidino-2-phenylacetophenone (α-D2PV)": "C1=CC=C(C=C1)C(C(=O)C2=CC=CC=C2)N3CCCC3",
            "α-Pyrrolidinobutyrophenone (α-PBP)": "CCC(C(=O)C1=CC=CC=C1)N2CCCC2",
            "α-pyrrolidinocyclohexylphenone (α-PCYP)": "C1CCC(CC1)C(C(=O)C2=CC=CC=C2)N3CCCC3",
            "α-pyrrolidinohexanophenone (α-PHP)": "CCCCC(C(=O)C1=CC=CC=C1)N2CCCC2",
            "α-Pyrrolidinopropiophenone (α-PPP)": "CC(C(=O)C1=CC=CC=C1)N2CCCC2",
            "α-Pyrrolidinovalerophenone (α-PVP)": "CCCC(C(=O)C1=CC=CC=C1)N2CCCC2",
            "1P-ETH-LAD": "CCC(=O)N1C=C2CC3C(=CC(CN3CC)C(=O)N(CC)CC)C4=C2C1=CC=C4",
            "2-Me-DMT": "CC1=C(CCN(C)C)C2=C(C=CC=C2)N1",
            "4-AcO-DALT": "CC(=O)OC1=CC=CC2=C1C(=CN2)CCN(CC=C)CC=C",
            "4-AcO-DET": "CCN(CC)CCC1=CNC2=CC=CC(=C12)OC(=O)C",
            "4-AcO-DIPT": "CC(C)N(CCC1=CNC2=C1C(=CC=C2)OC(=O)C)C(C)C",
            "4-AcO-DMT": "CC(=O)OC1=C2C(=CNC2=CC=C1)CCN(C)C",
            "4-AcO-DPT": "CCCN(CCC)CCC1=CNC2=CC=CC(=C12)OC(=O)C",
            "4-AcO-EPT": "CCCN(CC)CCC1=CNC2=CC=CC(=C12)OC(=O)C",
            "4-AcO-MALT": "CC(=O)OC1=C2C(=CNC2=CC=C1)CCN(C)[TeH]",
            "4-AcO-MET": "CCN(C)CCC1=CNC2=C1C(=CC=C2)OC(=O)C",
            "4-AcO-MIPT": "CC(C)N(C)CCC1=CNC2=C1C(=CC=C2)OC(=O)C",
            "4-AcO-MPT": "CCCN(C)CCC1=CNC2=CC=CC(=C12)OC(=O)C",
            "4-HO-DET": "CCN(CC)CCC1=CNC2=CC=CC(=C12)O",
            "4-HO-DIPT": "CC(C)N(CCC1=CNC2=C1C(=CC=C2)O)C(C)C",
            "4-HO-DPT": "CCCN(CCC)CCC1=CNC2=CC=CC(=C12)O",
            "4-HO-EPT": "CCCN(CC)CCC(CCC)O",
            "4-HO-MALT": "CN(CCC1=CNC2=C1C(=CC=C2)O)CC=C",
            "4-HO-McPT": "CN(CCC1=CNC2=CC=CC(=C12)O)C3CC3",
            "4-HO-MET": "CCN(C)CCC1=CNC2=C1C(=CC=C2)O",
            "4-HO-MIPT": "CC(C)N(C)CCC1=CNC2=C1C(=CC=C2)O",
            "4-HO-MPT": "CCCN(C)CCC1=CNC2=CC=CC(=C12)O",
            "4-MeO-MiPT": "CC(C)N(C)CCC1=CNC2=CC=CC(=C12)OC",
            "4-PrO-DMT": "CCC(=O)OC1=C2C(=CNC2=CC=C1)CCN(C)C",
            "5-Br-DMT": "CN(C)CCC1=CNC2=C1C=C(C=C2)Br",
            "5-Chloro-alpha-methyltryptamine": "CC(CC1=CNC2=C1C=C(C=C2)Cl)N",
            "5-Cl-DMT": "CN(C)CCC1=CNC2=C1C=C(C=C2)Cl",
            "5-HO-DMT": "CN(C)CCC1=CNC2=C1C=C(C=C2)O",
            "5-MeO-AMT": "CC(CC1=CNC2=C1C=C(C=C2)OC)N",
            "5-Meo-DALT": "C=CCN(CC=C)CCC1=CNC2=C1C=C(C=C2)OC",
            "5-MeO-DBT": "CCCCN(CCCC)CCC1=CNC2=C1C=C(C=C2)OC",
            "5-MeO-DET": "CCN(CC)CCC1=CNC2=C1C=C(C=C2)OC",
            "5-MeO-DIPT": "CC(C)N(CCC1=CNC2=C1C=C(C=C2)OC)C(C)C",
            "5-MeO-DMT": "CN(C)CCC1=CNC2=C1C=C(C=C2)OC",
            "5-MeO-DPT": "CCCN(CCC)CCC1=CNC2=C1C=C(C=C2)OC",
            "5-MeO-EIPT": "CCN(CCC1=CNC2=C1C=C(C=C2)OC)C(C)C",
            "5-MeO-MALT": "C=CCN(C)CCC1=CNC2=C1C=C(C=C2)OC",
            "5-MeO-MET": "CCN(C)CCC1=CNC2=C1C=C(C=C2)OC",
            "5-MeO-MiPT": "CC(C)N(C)CCC1=CNC2=C1C=C(C=C2)OC",
            "5-MeO-NiPT": "CC(C)NCCC1=CNC2=C1C=C(C=C2)OC",
            "5-MeO-pyr-T": "COC1=CC2=C(C=C1)NC=C2CCN3CCCC3",
            "5-MeO-TMT": "CC1=C(CCN(C)C)C2=C(C=CC(=C2)OC)N1",
            "5-MeO-tryptamine": "COC1=CC2=C(C=C1)NC=C2CCN",
            "AL-LAD": "CCN(CC)C(=O)C1CN(C2CC3=CNC4=CC=CC(=C34)C2=C1)CC=C",
            "AMT": "CC(CC1=CNC2=C1C=CC=C2)N",
            "BDMT": "CN(C)CCC1=C2C=CC=CC2=C(CCN(C)C)C3(C1)NC4=C(C=CC=C4)N3",
            "DALT": "C=CCN(CC=C)CCC1=CNC2=C1C=CC=C2",
            "DIPT": "CC(C)N(CCC1=CNC2=C1C=CC=C2)C(C)C",
            "DMT": "CN(C)CCC1=CNC2=C1C=CC=C2",
            "DPT": "CCCN(CCC)CCC1=CNC2=C1C=CC=C2",
            "EPT": "CCCN(CC)CCC1=CNC2=C1C=CC=C2",
            "ETH-LAD": "CCC1C[C@H](C=C2C3=C4C(=CNC4=CC=C3)C[C@H]12)C(=O)N(CC)CC",
            "Lysergic acid methyl ester": "CN1CC(C=C2C3=C4C(=CNC4=CC=C3)CC21)C(=O)OC",
            "MALT": "C=CCN(C)CCC1=CNC2=C1C=CC=C2",
            "McPT": "CN(CCC1=CNC2=C1C=CC=C2)C3CC3",
            "MET": "CCN(C)CCC1=CNC2=C1C=CC=C2",
            "MIPT": "CC(C)N(C)CCC1=CNC2=C1C=CC=C2",
            "N-methyltryptamine": "CNCCC1=CNC2=C1C=CC=C2",
            "α-TMT": "CC(CC1=CNC2=C1C=CC=C2)N(C)C",
            "(Iso)butyryl-F-fentanyl N-benzyl analogue": "CC(C)C(=O)N(C1=CC=C(C=C1)F)C2CCN(CC2)CC3=CC=CC=C3",
            "2-fluorofentanyl (ortho-fluorofentanyl)": "CCC(=O)N(C1=C(C=CC=C1)F)C2CCN(CCC3=CC=CC=C3)CC2",
            "2F-viminol": "CCC(C)N(CC(C1=CC=CN1CC2=C(C=CC=C2)F)O)C(C)CC",
            "2-methylacetylfentanyl": "CC1=C(C=CC=C1)N(C(=O)C)N(CCC2=CC=CC=C2)CCC3=CC=CC=C3",
            "2-methyl-AP-237": "CCCC(=O)N1CCN(CC=CC2=CC=CC=C2)CC1C",
            "3,4-methylenedioxy-U-47700": "CN(C)C1CCCCC1N(C)C(=O)C2=CC=C3C(=C2)OCO3",
            "3-fluorofentanyl (meta-fluorofentanyl)": "CCC(=O)N(C1=CC(=CC=C1)F)C2CCN(CCC3=CC=CC=C3)CC2",
            "3-fluoromethoxyacetylfentanyl": "COCC(=O)N(C1CCN(CCC2=CC=CC=C2)CC1)C3=CC(=CC=C3)F",
            "3-methylcrotonylfentanyl": "CC(=CC(=O)N(C1=CC=CC=C1)C2CCN(CCC3=CC=CC=C3)CC2)C",
            "3-phenylpropanoylfentanyl": "C1=CC=C(C=C1)CCC(=O)N(C2=CC=CC=C2)C3CCN(CCC4=CC=CC=C4)CC3",
            "4-(Trifluoromethyl) U-47700": "CNC1CCCCC1N(C)C(=O)C2=CC=C(C=C2)C(F)(F)F",
            "4-chloro-isobutyrfentanyl (4Cl-iBF)": "CC(C)C(=O)N(C1=CC=C(C=C1)Cl)C2CCN(CCC3=CC=CC=C3)CC2",
            "4F-furanylfentanyl": "CCN1CCC(CC1)N(C2=CC=C(C=C2)F)C(=O)C3=CC=CO3",
            "4-fluoro-butyrfentanyl (4F-BF)": "CCCC(=O)N(C1=CC=C(C=C1)F)N2CCC(CC2)CCC3=CC=CC=C3",
            "4-fluoro-cyclopropylbenzylfentanyl": "C1=CC=C(C=C1)CN2CCC(CC2)CN(C3=CC=C(C=C3)F)C(=O)C4CC4",
            "4-fluoro-isobutyrfentanyl (4F-iBF)": "CC(C)C(=O)N(C1=CC=C(C=C1)F)C2CCN(CCC3=CC=CC=C3)CC2",
            "4-hydroxybutyrfentanyl / 4-HO-BF": "CCCC(=O)N(C1=CC=C(C=C1)O)C2CCN(CCC3=CC=CC=C3)CC2",
            "4-methoxybutyrfentanyl (4-MeO-BF)": "CCCC(=O)N(C1CCN(CC1)CCC2=CC=CC=C2)C3=CC=C(C=C3)OC",
            "Acetylbenzylfentanyl": "CC(=O)N(C1=CC=CC=C1)N(CC2=CC=CC=C2)C3CCN(CC3)CC4=CC=CC=C4",
            "Acetylfentanyl": "CC(=O)N(C1=CC=CC=C1)C2CCN(CCC3=CC=CC=C3)CC2",
            "Acryloylfentanyl": "CCN1CCC(CC1)N(C2=CC=CC=C2)C(=O)C=O",
            "AH-7921": "CN(C)C1(CCCCC1)CNC(=O)C2=CC(=C(C=C2)Cl)Cl",
            "Alpha-methylfentanyl butanamide analogue": "CC(C)C(=O)N(C1=CC=CC=C1)C2CCN(CC2)C(C)CC3=CC=CC=C3",
            "AP-237": "CCCC(=O)N1CCN(CC=CC2=CC=CC=C2)CC1",
            "AP-238": "CCC(=O)N1C(C)CN(CC=CC2=CC=CC=C2)CC1C",
            "Benzodioxole-fentanyl": "C1=CC=C(C=C1)CCN2CCC(CC2)CN(C3=CC=CC=C3)C(=O)C4=CC=C5C(=C4)OCO5",
            "Benzoylbenzylfentanyl": "C1=CC=C(C=C1)CN2CCC(CC2)CN(C3=CC=CC=C3)C(=O)C4=CC=CC=C4",
            "Benzoylfentanyl": "C1=CC=C(C=C1)CCN2CCC(CC2)N(C3=CC=CC=C3)C(=O)C4=CC=CC=C4",
            "Benzylfentanyl": "CCC(=O)N(C1=CC=CC=C1)C2CCN(CC2)CC3=CC=CC=C3",
            "Bromadoline": "CN(C)C1CCCCC1NC(=O)C2=CC=C(C=C2)Br",
            "Brorphine": "CC(C1=CC=C(C=C1)Br)N2CCC(CC2)C3C4=C(C=CC=C4)NC3=O",
            "Butonitazene": "CCCCOC1=CC=C(C=C1)CC2=NC3=C(C=CC(=C3)[N+](=O)[O-])N2N(CC)CC",
            "Butorphanol": "C1CC(C1)CC2CCN(C(CO2)O)O",
            "Butyrfentanyl": "CCCC(=O)N(C1=CC=CC=C1)C2CCN(CCC3=CC=CC=C3)CC2",
            "Carbonyl-bromadol": "CCC1(CCC(CC1)(C(=O)C2=CC=C(C=C2)Br)N(C)C)O",
            "Carfentanil": "CCC(=O)N(C1=CC=CC=C1)C2(CCN(CC2)CCC3=CC=CC=C3)C(=O)OC",
            "Crotonylfentanyl": "CCC(CC)C(=O)N(C1=CC=CC=C1)N(CCC2=CC=CC=C2)C3CCN(CCC4=CC=CC=C4)CC3",
            "Cyclopentylfentanyl": "C1=CC=C(C=C1)CCN2CCC(CC2)N(C3=CC=CC=C3)C(=O)C4CCCC4",
            "Cyclopropylfentanyl": "C1=CC=C(C=C1)CCN2CCC(CC2)N(C3=CC=CC=C3)C(=O)C4CC4",
            "Desmethylmoramide": "C1=CC=C(C=C1)C(CCN2CCOCC2)(C3=CC=CC=C3)C(=O)N4CCCC4",
            "Despropionyl-2-fluoro fentanyl": "C1=CC=C(C=C1)CCN2CCC(CC2)NC3=C(C=CC=C3)F",
            "Dipyanone": "CCC(=O)C(CC(C)N1CCCC1)(C2=CC=CC=C2)C(=O)CC",
            "Etazene": "CCN(CC)C1C2=C(C=CC=C2)N=C1CC3=CC=C(C=C3)OCC",
            "Etonitazepipne": "CCOC1=CC=C(C=C1)CC2=NC3=C(C=CC(=C3)[N+](=O)[O-])N2CCN4CCCCC4",
            "Etonitazepyne": "CCOC1=CC=C(C=C1)CC2=NC3=C(C=CC(=C3)[N+](=O)[O-])N2CCN4CCCC4",
            "Fluonitazene (flunitazene)": "CCN(CC)CCN1C2=C(C=C(C=C2)[N+](=O)[O-])N=C1CC3=CC=C(C=C3)F",
            "Furanyl UF-17": "CN(C)C1CCCCC1N(C2=CC=CC=C2)C(=O)C3=CC=CO3",
            "Furanylbenzylfentanyl": "C1=CC=C(C=C1)CN2CCC(CC2)CN(C3=CC=CC=C3)C(=O)C4=CC=CO4",
            "Furanylfentanyl": "C1=CC=C(C=C1)CCN2CCC(CC2)N(C3=CC=CC=C3)C(=O)C4=CC=CO4",
            "Isobutyrfentanyl (iBF)": "CC(C)C(=O)N(C1=CC=CC=C1)C2CCN(CCC3=CC=CC=C3)CC2",
            "isopropyl-U-47700": "CC(C)N(C1CCCCC1N(C)C)C(=O)C2=CC=C(C(=C2)Cl)Cl",
            "isotonitazene": "CCN(CC)CCN1C2=C(C=C(C=C2)[N+](=O)[O-])N=C1CC3=CC=C(C=C3)OC(C)C",
            "Methoxyacetylfentanyl": "COCC(=O)N(C1=CC=CC=C1)C2CCN(CCC3=CC=CC=C3)CC2",
            "Metodesnitazene": "CCN(CC)CCN1C2=C(C=CC=C2)N=C1CC3=CC=C(C=C3)OC",
            "Metonitazene": "CCN(CC)CCN1C2=C(C=C(C=C2)[N+](=O)[O-])N=C1CC3=CC=C(C=C3)OC",
            "MT-45": "C1=CC=C(C=C1)CC(C2=CC=CC=C2)N3CCN(CC3)C4CCCCC4",
            "N-methyl U-47931E": "CN(C)C1CCCCC1N(C)C(=O)C2=CC=C(C=C2)Br",
            "Nortilidine": "CCOC(=O)C1(CCC=CC1NC)C2=CC=CC=C2",
            "O-AMKD": "CC(=O)C1(CCN(C)CC1)C2=CC=CC(=C2)OC(=O)C",
            "Ocfentanil (A-3217)": "COCC(=O)N(C1=C(C=CC=C1)F)C2CCN(CCC3=CC=CC=C3)CC2",
            "ODT": "CN(C)CC1CCCCC1(C2=CC(=CC=C2)O)O.Cl",
            "Piperidylthiambutene": "CC(C=C(C1=CC=CS1)C2=CC=CS2)N3CCCCC3",
            "Protonitazene": "CCCOC1=CC=C(C=C1)CC2=NC3=C(C=CC(=C3)[N+](=O)[O-])N2N(CC)CC",
            "Tetrahydrofuranylfentanyl (THF-F)": "C1=CC=C(C=C1)CCN2CCC(CC2)N(C3=CC=CC=C3)C(=O)C4=CCCO4",
            "Tetramethylcyclopropanefentanyl": "CC1(C)C(C(=O)N(C2=CC=CC=C2)[C+]3CCN(CCC4=CC=CC=C4)CC3)C1(C)C",
            "Thiophenefentanyl": "C1=CC=C(C=C1)CCN2CCC(CC2)N(C3=CC=CC=C3)C(=O)C4=CC=CS4",
            "Tianeptine": "CN1C2=C(C=CC=C2)C(C3=CC=C(C=C3S1(=O)=O)Cl)NCCCCCCC(=O)O",
            "Tramadol": "CN(C)C[C@H]1CCCC[C@@]1(C2=CC=CC(=C2)OC)O",
            "U-47700": "CN(C)C1CCCCC1N(C)C(=O)C2=CC=C(C(=C2)Cl)Cl",
            "U-48800": "CN(C)C1CCCCC1N(C)C(=O)CC2=CC=C(C=C2Cl)Cl",
            "U-49900": "CCN(CC)C1CCCCC1N(C)C(=O)C2=CC=C(C(=C2)Cl)Cl",
            "U-50488": "CN(C1CCCCC1N2CCCC2)C(=O)CC3=CC=C(C(=C3)Cl)Cl",
            "U-51754": "CN(C)C1CCCCC1N(C)C(=O)CC2=CC=C(C(=C2)Cl)Cl",
            "Valerylfentanyl": "CCCCC(=O)N(C1=CC=CC=C1)C2CCN(CCC3=CC=CC=C3)CC2",
            "1,4-DMAA": "CC(C)CCC(C)N.CC(C)CCC(C)N",
            "1-acetyl-LSD (ALD-52)": "CCN(CC)C(=O)[C@@H]1C=C2C3=C4C(=CN(C(=O)C)C4=CC=C3)C[C@H]2N(C)C1",
            "1B-LSD": "CCCCN1C=C2CC3C(=CC(CN3C)C(=O)N(CC)CC)C4=C2C1=CC=C4",
            "1cP-AL-LAD": "C=CCN1CC(C=C2C3=C4C(=CN(C4=CC=C3)C(=O)C5CC5)CC21)C(=O)N(CC)CC",
            "1cP-LSD": "CCN(CC)C(=O)C1C=C2C3=C4C(=CN(C4=CC=C3)C(=O)C5CC5)CC2N(C)C1",
            "1-cyclohexyl-x-methoxybenzene": "COC1=CC(=CC=C1)C2CCCCC2.COC1=C(C=CC=C1)C2CCCCC2.COC1=CC=C(C=C1)C2CCCCC2",
            "1-Ethynyl-cyclohexanol (ECX)": "C#CC1(CCCCC1)O",
            "1p-LSD": "CCC(=O)N1C=C2CC3C(=CC(CN3C)C(=O)N(CC)CC)C4=C2C1=CC=C4",
            "1V-LSD": "CCCCC(=O)N1C=C2CC3C(=CC(CN3C)C(=O)N(CC)CC)C4=C2C1=CC=C4",
            "2C-B aminorex": "COC1=C(C=C(C(=C1)Br)OC)C2CC=NN(N)O2",
            "2F-Phenmetrazine": "CC1C(C2=C(C=CC=C2)F)OCCN1",
            "2-MeO-diphenidine": "COC1=C(C=CC=C1)C(CC2=CC=CC=C2)N3CCCCC3",
            "3,4-DMAR": "CC1C(C2=CC=CC=C2)OC(=N)N1C",
            "3,6-DMPM": "CC1CNC(C)C(C2=CC=CC=C2)O1",
            "3-Chlorophenmetrazine": "CC1C(C2=CC=CC(=C2)Cl)OCCN1",
            "3-Fluoro-isomethcathinone (3-FiMC)": "CC(=O)C(C1=CC=CC(=C1)F)NC",
            "3F-Phenetrazine": "CCC1C(C2=CC=CC(=C2)F)OCCN1",
            "3F-Phenmetrazine": "CC1C(C2=CC=CC(=C2)F)OCCN1",
            "3-methoxyphenmetrazine": "CC1C(C2=CC=CC(=C2)OC)OCCN1",
            "3-methylphenmetrazine": "CC1=CC=CC(=C1)C2C(C)NCCO2",
            "4-Fluoroephedrine": "CC(C(C1=CC=C(C=C1)F)O)NC",
            "4-fluorophenibut": "C1=C(C=CC(=C1)F)C(CC(=O)O)CN",
            "4-methylpentan-2-amine (DMBA)": "CC(C)CC(C)N.CC(C)CC(C)N",
            "4-methylphendimetrazine": "CC1=CC=C(C=C1)C2C(C)N(C)CCO2",
            "4-MPH": "CC1=CC=C(C=C1)C2C(C)NCCO2",
            "5-HTP": "C1=CC2=C(C=C1O)C(=CN2)CC(C(=O)O)N",
            "Adrafinil": "C1=CC=C(C=C1)C(C2=CC=CC=C2)S(=O)CC(=O)NO",
            "Afloqualone": "CC1=C(C=CC=C1)N2C(=NC3=C(C=C(C=C3)N)C2=O)CF",
            "alpha-methylephedrine": "CC(C(C)(C1=CC=CC=C1)O)NC",
            "Amantadine": "C1C2CC3CC1CC(C2)(C3)N.C1C2CC3CC1CC(C2)(C3)N",
            "Baclofen": "C1=C(C=CC(=C1)Cl)C(CC(=O)O)CN",
            "Benzydamine": "CN(C)CCCOC1=NN(CC2=CC=CC=C2)C3=C1C=CC=C3",
            "Bisfluoromodafinil": "C1=C(C=CC(=C1)F)C(C2=CC=C(C=C2)F)S(=O)CC(=O)N",
            "Bromantane": "C1=C(C=CC(=C1)NC2C3CC4CC(C3)CC2C4)Br",
            "Camfetamine": "CNC1C2CCC(C2)C1C3=CC=CC=C3",
            "Citicoline": "C[N+](C)(C)CCOP(=O)([O-])OP(=O)(O)OCC1C(C(C(N2C=CC(=NC2=O)N)O1)O)O",
            "Clozapine": "CN1CCN(CC1)C2=NC3=C(C=CC(=C3)Cl)NC4=CC=CC=C42",
            "Cyproheptadine": "CN1CCC(=C2C=CC=CC3=C(C=CC=C3)C4=C2C=CC=C4)CC1",
            "Dichloropane (RTI-111)": "CN1C2CCC1C(C(C2)C3=CC=C(C(=C3)Cl)Cl)C(=O)OC",
            "Dimethocaine": "CCN(CC)CC(C)(C)COC(=O)C1=CC=C(C=C1)N",
            "Diphenhydramine": "CN(C)CCOC(C1=CC=CC=C1)C2=CC=CC=C2",
            "Diphenidine": "C1=CC=C(C=C1)CC(C2=CC=CC=C2)N3CCCCC3",
            "DMAA": "CCC(C)CC(C)N.CCC(C)CC(C)N",
            "DXM": "CN1CCC23CCCCC2C1CC4=C3C=C(C=C4)OC",
            "Embutramide": "CCC(CC)(CNC(=O)CCCO)C1=CC=CC(=C1)OC",
            "Ephenidine (NEDPA)": "CCNC(CC1=CC=CC=C1)C2=CC=CC=C2",
            "Ephinazone": "CCC1=NC2=C(C=CC=C2)C(=O)N1C3=CC=CC=C3",
            "Epirocaine": "CCCNC(C)(C)COC(=O)C1=CC=CC=C1",
            "Etaqualone": "CCC1=C(C=CC=C1)N2C(=NC3=C(C=CC=C3)C2=O)C",
            "Fenozolone": "CCNN1C=C(C(C2=CC=CC=C2)O1)C3=CC=CC=C3",
            "Fladrafinil": "C1=CC(=CC=C1C(C2=CC=C(C=C2)F)S(=O)CC(=O)NO)F",
            "Flibanserin": "C1CN(CCN1CCN2C3=CC=CC=C3NC2=O)C4=CC=CC(=C4)C(F)(F)F",
            "G-130": "CC1(C)COC(CN1)C2=CC=CC=C2",
            "Gabapentin": "CC(=O)O.CC(=O)O",
            "GHB": "C(CC(=O)O)CO.C(CC(=O)O)CO",
            "Iso-(meta-methyl-propcathinone)": "CCCNC(C(=O)C)C1=CC(=CC=C1)C",
            "Iso-3-CMC": "CC(=O)C(C1=CC=CC(=C1)Cl)NC",
            "Iso-ethcathinone": "CCNC(C(=O)C)C1=CC=CC=C1",
            "Iso-pentedrone": "CCCC(=O)C(C1=CC=CC=C1)NC",
            "Iso-phenmetrazine": "CC1COC(CN1)C2=CC=CC=C2",
            "Lysergic acid 2,4-dimethylazetidide (LSZ)": "C[C@H]1C[C@H](C)N1C(=O)[C@H]2C=C3C4=C5C(=CNC5=CC=C4)C[C@@H]3N(C)C2",
            "Mebroqualone": "CC1=NC2=C(C=CC=C2)C(=O)N1C3=C(C=CC=C3)Br",
            "Mephtetramine": "CNCC1CCC2=C(C=CC=C2)C1=O",
            "Mesembrine": "CN1CCC2(CCC(=O)CC21)C3=CC=C(C(=C3)OC)OC",
            "Methylmethaqualone": "CC1=CC=C(C(=C1)C)N2C(=NC3=C(C=CC=C3)C2=O)C",
            "Methylmorphenate": "COC(=O)C(C1=CC=CC=C1)C2COCCN2",
            "Modafiendz": "CNC(=O)CS(=O)C(C1=CC=C(C=C1)F)C2=CC=C(C=C2)F",
            "Modafinil": "C1=CC=C(C=C1)C(C2=CC=CC=C2)S(=O)CC(=O)N",
            "Modafinil sulphone": "C1=CC=C(C=C1)[C+](C2=CC=CC=C2)S(=O)(=O)CC(=O)N",
            "NDTDI": "CCN(CC)C(=O)CCN(C)[C@@H]1CC2=CC=CC3=C2C(=CN3)C1",
            "Nefiracetam": "CC1=CC=CC(=C1NC(=O)CN2CCCC2=O)C",
            "N-ethyl zolpidem": "CCNC(=O)CC1=C(C2=CC=C(C)C=C2)N=C3C=CC(=CN13)C",
            "Nitracaine": "CCN(CC)CC(C)(C)COC(=O)C1=CC=C(C=C1)[N+](=O)[O-]",
            "Nitromethaqualone": "CCOC1=CC(=CC=C1N2C(=NC3=C(C=CC=C3)C2=O)C)[N+](=O)[O-]",
            "N-methyl aminorex derivative": "CC1CC(C2=CC=CC=C2)ON1=N",
            "N-methyl-cyclazodone": "CN(C1CC1)N2C=C(C(C3=CC=CC=C3)O2)C",
            "N-methylephedrine": "CC(C(C1=CC=CC=C1)O)N(C)C",
            "NMP": "CN1CCCC1=O.CN1CCCC1=O",
            "Noopept": "CCOC(=O)CNC(=O)C1CCCN1C(=O)CC2=CC=CC=C2",
            "NPDPA": "CC(C)NC(CC1=CC=CC=C1)C2=CC=CC=C2",
            "Octodrine": "CC(C)CCCC(C)N.CC(C)CCCC(C)N",
            "Orphenadrine": "CC1=C(C=CC=C1)C(C2=CC=CC=C2)OCCN(C)C",
            "Ostarine": "CC(COC1=CC=C(C=C1)C#N)(C(=O)NC2=CC=C(C#N)C(=C2)C(F)(F)F)O",
            "Pagoclone": "CC(C)CCC(=O)CC1C2=C(C=CC=C2)C(=O)N1C3=NC4=C(C=CC(=N4)Cl)C=C3",
            "Para-bromo-4-methylaminorex (4Br-MAR)": "CC1C(OC(=N1)N)C2=CC=C(C=C2)Br",
            "Para-chloro-4-methylaminorex (4Cl-MAR)": "CC1C(OC(=N1)N)C2=CC=C(C=C2)Cl",
            "para-fluoro-4-methylaminorex / 4-FPO": "CC1C(C2=CC=C(C=C2)F)OC(=N1)N",
            "para-Methyl-4-methylaminorex (4,4'-DMAR)": "CC1=CC=C(C=C1)C2C(C)N=C(N)O2",
            "PDM-35": "CC1COC(C(C)N1)C2=CC=CC=C2",
            "pFBT": "CN1C2CCC1CC(C2)OC(=O)C3=CC=C(C=C3)F",
            "Phenetrazine": "CCC1C(C2=CC=CC=C2)OCCN1",
            "Phenibut": "C1=CC=C(C=C1)C(CC(=O)O)CN",
            "Phenmetetrazine": "CCN1CCOC(C1C)C2=CC=CC=C2",
            "Phenylpiracetam": "C1=CC=C(C=C1)C2CC(=O)N(C2)CC(=O)N",
            "Poppers": "CCCCCON=O",
            "PRE-084": "C1=CC=C(C=C1)C2(CCCCC2)C(=O)OCCN3CCOCC3",
            "Pregabalin": "CC(C)C[C@@H](CC(=O)O)CN",
            "Pregabalin methyl ester": "CC(C)CC(CC(=O)OC)CN",
            "Promethazine": "CC(CN1C2=C(C=CC=C2)SC3=C1C=CC=C3)N(C)C",
            "Quetiapine": "C1=CC=C2C(=C1)C=NC=CC=N2N3CCN(CC3)CCOCCO",
            "RH-34": "COC1=CC=CC=C1CNCCN2C(=O)C3=CC=CC=C3NC2=O",
            "Rilmazafone": "CN(C)C(=O)C1=NN(C2=CC=C(C=C2C(=O)C3=C(C=CC=C3)Cl)Cl)C(=N1)CNC(=O)C=N",
            "Rimonabant": "CC1=C(C2=CC=C(C=C2)Cl)N(C3=CC=C(C=C3Cl)Cl)N=C1C(=NN4CCCCC4)O",
            "Ru-28306": "CN(C)C1CC2=CC=CC3=C2C(=CN3)C1",
            "sibutramine": "CC(C)CC(C1(CCC1)C2=CC=C(C=C2)Cl)N(C)C",
            "SL-164": "CC1=CC(=CC=C1N2C(=NC3=C(C(=CC=C3)Cl)C2=O)C)Cl",
            "Troparil": "CN1C2CCC1C(C(C2)C3=CC=CC=C3)C(=O)OC",
            "Tropicamide": "CCN(CC1=CC=NC=C1)C(=O)C(CO)C2=CC=CC=C2",
            "Venlafaxine": "CN(C)CC(C1=CC=C(C=C1)OC)C2(CCCCC2)O",
            "Viloxazine": "CCOC1=C(C=CC=C1)OCC2CNCCO2",
            "W-15": "C1=CC=C(C=C1)CCN/2CCCC\C2=N/S(=O)(=O)C3=CC=C(C=C3)Cl",
            "W-18": "C1CCN(C(=NS(=O)(=O)C2=CC=C(C=C2)Cl)C1)CCC3=CC=C(C=C3)[N+](=O)[O-]",
            "WIN 35428": "CN1C2CCC1C(C(C2)C3=CC=C(C=C3)F)C(=O)OC",
            "Xylazine": "CC1=CC=CC(=C1NC2=NCCCS2)C",
            "Zaleplon": "CCN(C(=O)C)C1=CC=CC(=C1)C2=CC=NC3=C(C#N)C=NN23",
            "Zopiclone": "CN1CCN(CC1)C(=O)OC2C3=C(C(=O)N2C4=CC=C(C=N4)Cl)N=CC=N3",
            "1-phenethyl-4-hydroxypiperidine": "C1=CC=C(C=C1)CCN2CCC(CC2)O",
            "2-(2,3-dimethoxyphenyl)-N-(3,4,5-trimethoxybenzyl)ethanamine": "COC1=C(C(=CC=C1)CCNCC2=CC(=C(C(=C2)OC)OC)OC)OC",
            "2,4-DMA": "CC(CC1=CC=C(C=C1OC)OC)N",
            "2,6-Dibromomescaline": "COC1=C(C(=C(C(=C1OC)OC)Br)CCN)Br",
            "25B-N(BOMe)2": "COC1=C(C=CC=C1)CN(CCC2=C(C=C(C(=C2)OC)Br)OC)CC3=C(C=CC=C3)OC",
            "25B-NBF": "COC1=C(CCNCC2=C(C=CC=C2)F)C=C(C(=C1)Br)OC",
            "25B-NBOH": "COC1=C(CCNCC2=C(C=CC=C2)O)C=C(C(=C1)Br)OC",
            "25B-NBOMe": "COC1=C(C=CC=C1)CNCCC2=C(C=C(C(=C2)OC)Br)OC",
            "25C-NBF": "COC1=C(CCNCC2=C(C=CC=C2)F)C=C(C(=C1)Cl)OC",
            "25C-NBOH": "COC1=CC(=C(C=C1CCNCC2=CC=CC=C2O)OC)Cl",
            "25C-NBOMe": "COC1=C(C=CC=C1)CNCCC2=C(C=C(C(=C2)OC)Cl)OC",
            "25D-NBOMe": "CC1=C(C=C(CCNCC2=C(C=CC=C2)OC)C(=C1)OC)OC",
            "25E-NBOH": "CCC1=CC(=C(C=C1OC)CCNCC2=CC=CC=C2O)OC",
            "25E-NBOMe": "CCC1=C(C=C(CCNCC2=C(C=CC=C2)OC)C(=C1)OC)OC",
            "25G-NBOMe": "CC1=C(C)C=C(C(=C1)CCNCC2=C(C=CC=C2)OC)OC",
            "25H-NBOMe": "COC1=CC=C(C(=C1)CCNCC2=C(C=CC=C2)OC)OC",
            "25I-NB34MD": "COC1=C(CCNCC2=CC=C3C(=C2)OCO3)C=C(C(=C1)I)OC",
            "25I-NB4OMe": "COC1=CC=C(C=C1)CNCCC2=C(C=C(C(=C2)OC)I)OC",
            "25I-NBF": "COC1=C(CCNCC2=C(C=CC=C2)F)C=C(C(=C1)I)OC",
            "25I-NBMD": "COC1=C(CCNCC2=CC=CC3=C2OCO3)C=C(C(=C1)I)OC",
            "25I-NBOH": "COC1=C(CCNCC2=C(C=CC=C2)O)C=C(C(=C1)I)OC",
            "25I-NBOMe": "COC1=C(C=CC=C1)CNCCC2=C(C=C(C(=C2)OC)I)OC",
            "25iP-NBOMe": "CC(C)C1=CC(=C(CCNCC2=C(C=CC=C2)OC)C=C1OC)OC",
            "25N-NBOMe": "COC1=C(C=CC=C1)CNCCC2=C(C=C(C(=C2)OC)[N+](=O)[O-])OC",
            "2-Bromomescaline": "COC1=CC(=C(C(=C1OC)OC)Br)CCN",
            "2C-B": "COC1=C(CCN)C=C(C(=C1)Br)OC",
            "2C-C": "COC1=C(CCN)C=C(C(=C1)Cl)OC",
            "2C-D": "CC1=C(C=C(CCN)C(=C1)OC)OC",
            "2C-E": "CCC1=C(C=C(CCN)C(=C1)OC)OC",
            "2C-G": "CC1=C(C)C(=C(CCN)C=C1OC)OC",
            "2C-H": "COC1=CC=C(C(=C1)CCN)OC",
            "2-Chloro-4,5-MDMA": "CC(CC1=C(C=C2C(=C1)OCO2)Cl)NC",
            "2C-I": "COC1=C(CCN)C=C(C(=C1)I)OC",
            "2C-N": "COC1=C(CCN)C=C(C(=C1)[N+](=O)[O-])OC",
            "2C-P": "CCCC1=CC(=C(C=C1OC)CCN)OC",
            "2C-T-2": "CCSC1=CC(=C(CCN)C=C1OC)OC",
            "2C-T-21": "COC1=C(CCN)C=C(C(=C1)SCCF)OC",
            "2C-T-4": "CC(C)SC1=CC(=C(CCN)C=C1OC)OC",
            "2C-T-7": "CCCSC1=C(C=C(C(=C1)OC)CCN)OC",
            "2C-TFM": "COC1=C(CCN)C=C(C(=C1)C(F)(F)F)OC",
            "2-Fluoroamphetamine (2-FA)": "CC(CC1=C(C=CC=C1)F)N",
            "2-fluoroethamphetamine (2-FEA)": "CCNC(C)CC1=C(C=CC=C1)F",
            "2-FMA": "CC(CC1=C(C=CC=C1)F)NC",
            "2-methoxyamphetamine": "CC(CC1=C(C=CC=C1)OC)N",
            "2-methylamphetamine": "CC(C[18O])N",
            "2-PEA": "CCN.CCN",
            "3,4-DMA NBOMe": "CC(CC1=CC=C(C(=C1)OC)OC)NCC2=C(C=CC=C2)OC",
            "3,4-MDPA": "CCCNC(C)CC1=CC=C2C(=C1)OCO2",
            "30C-NBOMe": "COC1=C(C=C(C(=C1)NCC2=CC(=C(C(=C2)OC)OC)OC)OC)Cl",
            "3C-E": "CCOC1=C(C=C(CC(C)N)C=C1OC)OC",
            "3C-P": "CCCOC1=C(C=C(CC(C)N)C=C1OC)OC",
            "3-Fluoroethamphetamine (3-FEA)": "CCNC(C)CC1=CC=CC(=C1)F",
            "3-FMA": "CC(CC1=CC(=CC=C1)F)NC",
            "3-MeO-NBOMe": "CCOC1=CC(=CC=C1)CCNCC2=C(C=CC=C2)OC",
            "3-methylmethamphetamine (3-MMA)": "CC1=CC=CC(=C1)CC(C)NC",
            "4-bromoamphetamine (4-BA)": "CC(CC1=CC=C(C=C1)Br)N",
            "4C-D": "CCC(CC1=CC(=C(C)C=C1OC)OC)N",
            "4-chloroamphetamine (4-CA)": "CC(CC1=CC=C(C=C1)Cl)N.CC(CC1=CC=C(C=C1)Cl)N",
            "4-CMA": "CC(CC1=CC=C(C=C1)Cl)NC",
            "4-EA NBOMe": "CCC1=CC=C(C=C1)CC(C)NCC2=C(C=CC=C2)OC",
            "4F-deprenyl": "C#CCN(C)C(C)CC1=CC=C(C=C1)F",
            "4-Fluoroamphetamine (4-FA)": "CC(CC1=CC=C(C=C1)F)N.CC(CC1=CC=C(C=C1)F)N",
            "4-fluoroethamphetamine (4-FEA)": "CCNC(C)CC1=CC=C(C=C1)F",
            "4-FMA": "CC(CC1=CC=C(C=C1)F)NC",
            "4-Hydroxyamphetamine": "CC(CC1=CC=C(C=C1)O)N",
            "4-methylamphetamine (4-MA)": "CC1=CC=C(C=C1)CC(C)N",
            "4-methylmethamphetamine (4-MMA)": "CC1=CC=C(C=C1)CC(C)NC",
            "4-MMA NBOMe": "CC1=CC=C(C=C1)CC(C)N(C)CC2=C(C=CC=C2)OC",
            "4-MTA": "CC(CC1=CC=C(C=C1)SC)N",
            "6-BR-DMPEA": "COC1=CC(=C(C=C1OC)Br)N",
            "6-Bromo-MDMA": "CC(CC1=C(C=C2C(=C1)OCO2)Br)NC",
            "7-CDMeOPPAE": "CCN(C)CCN1C=NC2=C1C(=O)N(C)C(=O)N2C",
            "AL - allylescaline": "C=CCOC1=C(C=C(CCN)C=C1OC)OC",
            "BOD": "CC1=C(C=C(C(=C1)OC)C(CN)OC)OC",
            "Dimethylamphetamine": "CC(CC1=CC=CC=C1)N(C)C.CC(CC1=CC=CC=C1)N(C)C",
            "DMMA": "CC(CC1=CC=C(C(=C1)OC)OC)NC",
            "DOC": "CC(CC1=C(C=C(C(=C1)OC)Cl)OC)N",
            "DOF": "CC(CC1=CC(=C(C=C1OC)F)OC)N",
            "DOI": "CC(CC1=C(C=C(C(=C1)OC)I)OC)N",
            "DOIP": "CC(C)C1=CC(=C(CC(C)N)C=C1OC)OC",
            "DOM": "CC1=C(C=C(CC(C)N)C(=C1)OC)OC",
            "DOPR": "CCCC1=C(C=C(CC(C)N)C(=C1)OC)OC",
            "DOT": "CC(CC1=C(C=C(C(=C1)OC)SC)OC)N",
            "EFLEA": "CC(CC1=CC=C2C(=C1)OCCO2)N(C)O",
            "Escaline": "CCOC1=C(C=C(CCN)C=C1OC)OC",
            "MBDB": "CCC(CC1=CC=C2C(=C1)OCO2)NC",
            "MDDM": "CC(CC1=CC=C2C(=C1)OCO2)N(C)C",
            "MDHOET": "CC(CC1=CC2=C(C=C1)OCO2)NCCO",
            "Methallylescaline": "CC(=C)COC1=C(C=C(C=C1OC)CCN)OC",
            "Methoxyphenamine (OMMA)": "CC(CC1=C(C=CC=C1)OC)NC",
            "m-fluoroamphetamine (3-FA)": "CC(CC1=CC=CC(=C1)F)N",
            "N,N-dimethylphenethylamine": "CN(C)CCC1=CC=CC=C1.CN(C)CCC1=CC=CC=C1",
            "N-Acetyl-DOB": "CC(CC1=C(C=C(C(=C1)OC)Br)OC)NC(=O)C",
            "N-ethyl-1-phenyl-butane-2-amine": "CCC(CC1=CC=CC=C1)NCC",
            "N-ethyl-2C-B": "CCNCCC1=C(C=C(C(=C1)OC)Br)OC",
            "N-ethylamphetamine": "CCNC(C)CC1=CC=CC=C1",
            "N-hydroxy MDA": "CC(CC1=CC=C2C(=C1)OCO2)NO",
            "N-methyl-2C-B": "CNCCC1=C(C=C(C(=C1)OC)Br)OC",
            "NMPEA": "CNCCC1=CC=CC=C1.CNCCC1=CC=CC=C1",
            "N-Propylamphetamine (PA)": "CCCNC(C)CC1=CC=CC=C1",
            "PEAP": "CCCC(CC1=CC=CC=C1)NCC",
            "PMA": "CC(CC1=CC=C(C=C1)OC)N.CC(CC1=CC=C(C=C1)OC)N",
            "PMEA": "CCNC(C)CC1=CC=C(C=C1)OC",
            "PMMA": "CC(CC1=CC=C(C=C1)OC)NC",
            "PPAP": "CCCC(CC1=CC=CC=C1)NCCC",
            "Proscaline": "CCCOC1=C(C=C(CCN)C=C1OC)OC",
            "TMA-2": "CC(CC1=C(C=C(C(=C1)OC)OC)OC)N",
            "TMA-6": "CC(CC1=C(C=C(C=C1OC)OC)OC)N",
            "β-Me-PEA": "CC(CN)C1=CC=CC=C1.CC(CN)C1=CC=CC=C1",
            "1-(2,3-dichlorophenyl)-piperazine (2,3-XP)": "C1=CC(=C(C(=C1)Cl)Cl)N2CCNCC2",
            "1-(3-Methylbenzyl)piperazine": "CC1=CC=CC(=C1)CN2CCNCC2",
            "2C-B-BZP": "COC1=C(C=C(C(=C1)Br)OC)CN2CCNCC2",
            "3,4-CFP": "C1=C(C=C(C(=C1)F)Cl)N2CCNCC2",
            "4F-MBZP": "CN1CCN(CC1)CC2=CC=C(C=C2)F",
            "BZP": "C1=CC=C(C=C1)CN2CCNCC2.C1=CC=C(C=C1)CN2CCNCC2",
            "DB-MDBP": "C1=C(C=C2C(=C1)OC(F)(F)O2)CN3CCNCC3",
            "DBZP": "C1=CC=C(C=C1)CN2CCN(CC2)CC3=CC=CC=C3.C1=CC=C(C=C1)CN2CCN(CC2)CC3=CC=CC=C3",
            "Gelbes (CPCPP)": "C1=CC(=CC(=C1)Cl)N2CCN(CCCCl)CC2",
            "MBZP": "CN1CCN(CC1)CC2=CC=CC=C2.CN1CCN(CC1)CC2=CC=CC=C2",
            "mCPP": "C1=CC(=CC(=C1)Cl)N2CCNCC2",
            "Methoxypiperamide": "CN1CCN(CC1)C(=O)C2=CC=C(C=C2)OC",
            "NSI-189": "CC(C)CCNC1=C(C=CC=N1)C(=O)N2CCN(CC2)CC3=CC=CC=C3",
            "pBPP": "C1CN(CCN1)C2=CC=C(C=C2)Br",
            "pCPP": "C1CN(CCN1)C2=CC=C(C=C2)Cl",
            "pFPP": "C1CN(CCN1)C2=CC=C(C=C2)F",
            "pMeOPP": "COC1=CC=C(C=C1)N2CCNCC2",
            "TFMPP": "C1CN(CCN1)C2=CC=CC(=C2)C(F)(F)F",
            "Vanoxerine": "C1CN(CCN1CCCC2=CC=CC=C2)CCOC(C3=CC=C(C=C3)F)C4=CC=C(C=C4)F",
            "1-(1,3-diphenylpropan-2-yl)pyrrolidine": "C1CCN(C1)C(CC2=CC=CC=C2)CC3=CC=CC=C3",
            "2-DPMP": "C1CCNC(C1)C(C2=CC=CC=C2)C3=CC=CC=C3",
            "3,4-dichloromethylphenidate": "COC(=O)C(C1CCCCN1)C2=CC(=C(C=C2)Cl)Cl",
            "4,4-dimethyl-1-phenyl-1-pyrrolidin-1-yl-pentan-3-one": "CC(C)(C)C(=O)CC(C1=CC=CC=C1)N2CCCC2",
            "4-benzylpiperidine": "C1CNCCC1CC2=CC=CC=C2",
            "4-fluoroethylphenidate": "CCOC(=O)C(C1CCCCN1)C2=CC=C(C=C2)F",
            "4-fluoromethylphenidate (4F-MPH)": "COC(=O)C(C1CCCCN1)C2=CC=C(C=C2)F",
            "4-methylmethylphenidate": "CC1=CC=C(C=C1)C(C2CCCCN2)C(=O)OC",
            "D2PM": "C1CC(NC1)C(C2=CC=CC=C2)(C3=CC=CC=C3)O",
            "desoxy-D2PM": "C1CC(NC1)C(C2=CC=CC=C2)C3=CC=CC=C3",
            "Ethylnaphthidate": "CCOC(=O)C(C1CCCCN1)C2=CC3=CC=CC=C3C=C2",
            "Ethylphenidate": "CCOC(=O)C(C1CCCCN1)C2=CC=CC=C2",
            "HDMP-28 (methylnaphthidate)": "COC(=O)C(C1CCCCN1)C2=CC3=CC=CC=C3C=C2",
            "Isopropylphenidate": "CC(C)OC(=O)C(C1CCCCN1)C2=CC=CC=C2",
            "methyl 2-phenyl-2-(pyrrolidin-1-yl)acetate": "COC(=O)C(C1=CC=CC=C1)N2CCCC2",
            "Propylphenidate": "CCCOC(=O)C(C1CCCCN1)C2=CC=CC=C2",
            "Arecoline": "CN1CCC=C(C1)C(=O)OC",
            "Glaucine": "CN1CCC2=CC(=C(C3=C2C1CC4=CC(=C(C=C43)OC)OC)OC)OC",
            "Harmine": "CC1=NC=CC2=C1NC3=C2C=CC(=C3)OC",
            "Ibogaine": "CCC1CC2CC3C1N(C2)CCC4=C3NC5=C4C=C(C=C5)OC",
            "Kava": "COC1=CC(=O)OC(C1)C=CC2=CCCC=C2",
            "KRATOM": "CCC1CN2CCC3=C(C2CC1C(=COC)C(=O)OC)NC4=C3C(=CC=C4)OC",
            "LSA": "C1=CC=C2C(=C1)C(=O)NS2(=O)=O",
            "Salvinorin A": "CC(=O)OC1CC(C2(CCC3C(=O)OC(CC3(C2C1=O)C)C4=COC=C4)C)C(=O)OC",
        }

        return smiles
