#!/usr/bin/env python3
#
# GlobalChem - Constituents OfCannabisSativa
#
# -----------------------------------

class ConstituentsOfCannabisSativa(object):

    def __init__(self):

        self.name = 'constituents_of_cannabis_sativa'

    @staticmethod
    def get_smiles():

        '''

        Missing Entries

        'tetano-cannabine': '',
        'edestinase': '',
        'peptidase': '',
        '1-octene-3-01': '',

        '''

        smiles = {
            'cannabigerolic acid': r'CCCCCC1=CC(=C(C(=C1C(=O)O)O)C/C=C(\C)/CCC=C(C)C)O',
            'cannabigerolic acid monomethylether': r'CCCCCC1=CC(=C(C(=C1C(=O)O)O)C/C=C(\C)/CCC=C(C)C)OC',
            'cannabigerol': r'CCCCCC1=CC(=C(C(=C1)O)C/C=C(\C)/CCC=C(C)C)O',
            'cannabigerol monomethylether': r'CCCCCC1=CC(=C(C(=C1C(=O)O)O)C/C=C(\C)/CCC=C(C)C)OC',
            'cannabigerovarinic acid': 'CCCC1=CC(=C(C(=C1C(=O)O)O)CC=C(C)CCC=C(C)C)O',
            'cannabigerovarin': r'CCCC1=CC(=C(C(=C1)O)C/C=C(\C)/CCC=C(C)C)O',
            'cannabichromenic acid': 'CCCCCC1=CC2=C(C=CC(O2)(C)CCC=C(C)C)C(=C1C(=O)O)O',
            'cannabichromene': 'CCCCCC1=CC(=C2C=CC(OC2=C1)(C)CCC=C(C)C)O',
            'cannabichromevarinic acid': 'CCCC1=CC(=C2C=CC(OC2=C1)(C)CCC=C(C)C)O',
            'cannabichromevarin': 'CCCC1=CC(=C2C=CC(OC2=C1)(C)CCC=C(C)C)O',
            'cannabidiolic acid': 'CCCCCC1=CC(=C(C(=C1C(=O)O)O)C2C=C(CCC2C(=C)C)C)O',
            'cannabidiol': 'CCCCCC1=CC(=C(C(=C1)O)C2C=C(CCC2C(=C)C)C)O',
            'cannabidiol monomethylether': 'CCCCCC1=CC(=C(C(=C1)OC)C2C=C(CCC2C(=C)C)C)O',
            'cannabidiol c4': 'CCCCC1=CC2=C(C=C1)C(OC3=CC(=CC(=C32)O)C)(C)C',
            'cannabidivarinic acid': 'CCCC1=CC(=C(C(=C1C(=O)O)O)C2C=C(CCC2C(=C)C)C)O',
            'cannabidivarin': 'CCCC1=CC(=C(C(=C1)O)C2C=C(CCC2C(=C)C)C)O',
            'cannabidiorcol': 'CC1=CC(C(CC1)C(=C)C)C2=C(C=C(C=C2O)C)O',
            'delta-9 tetrahgdrocannabinolic acid a': 'CCCCCC1=CC2=C(C3C=C(CCC3C(O2)(C)C)C)C(=C1C(=O)O)O',
            'delta-9 tetrahgdrocannabinolic acid b': 'CCCCCC1=CC(=C2C3C=C(CCC3C(OC2=C1C(=O)O)(C)C)C)O',
            'delta-9 tetrahydrocannabinol': 'CCCCC1=CC(=C2C3C=C(CCC3C(OC2=C1)(C)C)C)O',
            'detla-9 tetrahvdrocannabinolic acid c': 'CCCCC1=CC2=C(C3C=C(CCC3C(O2)(C)C)C)C(=C1C(=O)O)O',
            'delta-9 tetrahydrocannabinol c4': 'CCCCC1=CC(=C2C3C=C(CCC3C(OC2=C1)(C)C)C)O',
            'delta-9 tetrahydrocannabivarinic acid': 'CCCC1=CC2=C(C3C=C(CCC3C(O2)(C)C)C)C(=C1C(=O)O)O',
            'delta-9 tetrahydrocannabivarin': 'CCCC1=CC(=C2C3C=C(CCC3C(OC2=C1)(C)C)C)O',
            'delta-9 tetrahydrocannabiorcolic acid': 'CC1=CC2=C(C3C=C(CCC3C(O2)(C)C)C)C(=C1C(=O)O)O',
            'detla-9 tetrahydrocannabiorcol': 'CC1=CC(=C2C3C=C(CCC3C(OC2=C1)(C)C)C)O',
            'detla-8 tetrahydrocannabinolic acid': 'CCCCCC1=CC2=C(C3CC(=CCC3C(O2)(C)C)C)C(=C1C(=O)O)O',
            'delta-8 tetrahydrocannabinol': 'CCCCCC1=CC(=C2C3CC(=CCC3C(OC2=C1)(C)C)C)O',
            'cannabicyclolic acid': 'CCCCCC1=CC2=C(C3C4C(C3(C)C)CCC4(O2)C)C(=C1C(=O)O)O',
            'cannabicyclol': 'CCCCCC1=CC(=C2C3C4C(C3(C)C)CCC4(OC2=C1)C)O',
            'cannabicyclovarin': 'CCCC1=CC(=C2C3C4C(C3(C)C)CCC4(OC2=C1)C)O',
            'cannabielsoic acid a': 'CCCCCC1=CC2=C(C3C(CCC(C3O2)(C)O)C(=C)C)C(=C1C(=O)O)O',
            'cannabielsoic acid b': 'CCCCCC1=CC(=C2C3C(CCC(C3OC2=C1C(=O)O)(C)O)C(=C)C)O',
            'cannabielsoin': 'CCCCCC1=CC(=C2C3C(CCC(C3OC2=C1)(C)O)C(=C)C)O',
            'cannabinolic acid a': 'CCCCCC1=CC2=C(C3=C(C=CC(=C3)C)C(O2)(C)C)C(=C1C(=O)O)O',
            'cannabinol': 'CCCCCC1=CC(=C2C(=C1)OC(C3=C2C=C(C=C3)C)(C)C)O',
            'cannabinol methylether': 'CCCCCC1=CC2=C(C(=C1)OC)C3=C(C=CC(=C3)C)C(O2)(C)C',
            'cannabinol c4': 'CCCCC1=CC2=C(C=C1)C(OC3=CC(=CC(=C32)O)C)(C)C',
            'cannabivarin': 'CCCC1=CC(=C2C(=C1)OC(C3=C2C=C(C=C3)C)(C)C)O',
            'cannabiorcol': 'CC1=CC2=C(C=C1)C(OC3=CC(=CC(=C32)O)C)(C)',
            'cannabinodiol': 'CCCCCC1=CC(=C(C(=C1)O)C2=C(C=CC(=C2)C)C(=C)C)O',
            'cannabinodivarin': 'CCCC1=CC(=C(C(=C1)O)C2=C(C=CC(=C2)C)C(=C)C)O',
            'cannabitriol': 'CCCCCC1=CC(=C2C(=C1)OC(C3=C2C(C(CC3)(C)O)O)(C)C)O',
            '9,10-dihydroxy-delta-6a,10a-tetrahydrocannabinol': 'CCCCCC1=CC(O)=C2C(OC(C)(C)C3=C2C(O)C(C)(O)CC3)=C1',
            '10-ethoxy-9-hydroxy-delta-6a,10a-tetrahydrocannabinol': 'CCCCCC1=CC(O)=C2C(OC(C)(C)C3=C2C(OCC)C(C)(O)CC3)=C1',
            '8,9-dihydroxy-delta-tetrahydrocannabinol': 'CCCCCC1=CC(O)=C2C(OC(C)(C)C3=C2CC(C)(O)C(O)C3)=C1',
            'cannabidiolic acid tetrahydrocannabitriol ester ': 'CCCCCC1=CC(=C2C(=C1)OC(C3=C2C(C(C(C3)OC(=O)C4=C(C(=C(C=C4CCCCC)O)C5C=C(CCC5C(=C)C)C)O)C)O)(C)C)O',
            'dehydrocannabifuran': 'CCCCCC1=CC(=C2C(=C1)OC3=C(C=CC(=C23)C(=C)C)C)O',
            'cannabifuran': 'CCCCCC1=CC(=C2C(=C1)OC3=C(C=CC(=C23)C(C)C)C)O',
            'cannabichromanon': 'CCCCCC1=CC(=C2C(=C1)OC(C(C2=O)CCC(=O)C)(C)C)O',
            'cannabicitran': 'CCCCCC1=CC2=C3C4CC(CCC4C(O2)(C)C)(OC3=C1)C',
            '10-oxo-delta-6a,10a-tetrahydrocannabinol': 'CCCCCC1=CC(O)=C2C(OC(C)(C)C3=C2C(=O)C(C)CC3)=C1',
            'delta-9 6a,10a-tetrahydrocannabinol': 'CCCCCC1=CC(O)=C2C(OC(C)(C)C3=C2CC(C)(O)C(O)C3)=C1',
            '3,4,5,6-tetrahydro-7-hydroxy-alpha,alpha-2-trimethyl-9-n-propyl-2,6-methano-2H-1-benzoxocin-5-methanol': 'CCCC1=CC(=C2C3CC(CCC3C(C)(C)O)(OC2=C1)C)O',
            '6a,9,10,10a-9,10-dihydroxyhexahydrocannabinol': 'CCCCCC1=CC(=C2C3C(CCC(C3O)(C)O)C(OC2=C1)(C)C)O',
            '6a,7,10a-trihydroxy-delta-9 tetrahydrocannabinol': 'CCCCCC1=CC(=C2C3(O)C=C(CC(O)C3(O)C(OC2=C1)(C)C)C)O',
            'choline': 'C[N+](C)(C)CCO',
            'trigonelline': 'C[N+]1=CC=CC(=C1)C(=O)[O-]',
            'muscarine': 'CC1C(CC(O1)C[N+](C)(C)C)O',
            'l-plus isoleucine betaine': 'C[N+](C)(C)CC(=O)[O-]',
            'neurine': 'C[N+](C)(C)C=C.[OH-]',
            'piperidine': 'C1CCNCC1',
            'hordenine': 'CN(C)CCC1=CC=C(C=C1)O',
            'ammonia': 'N',
            'methylamine': 'CN',
            'ethylamine': 'CCN',
            'n-propylamine': 'CCCN',
            'n-butylamine': 'CCCCN',
            'iso-butylamine': 'CC(C)CN',
            'secbutylamine': 'CCC(C)N',
            'dimethylamine': 'CNC',
            'pyrrolidine': 'C1CCNC1',
            'cannabisativine': 'CCCCCC(C(C1C=CCC2N1CCCNCCCCNC(=O)C2)O)O',
            'anhydrocannabisativine': 'CC1(C(C(O)C2CCCC2)O)C=CCC(C3)N1CCCNCCCCNC3=O',
            'alanine': 'CC(C(=O)O)N',
            'asparatic acid': 'C(C(C(=O)O)N)C(=O)O',
            'cystine': 'C(C(C(=O)O)N)SSCC(C(=O)O)N',
            'glutamic acid': 'CCC(O)=O',
            'glycine': 'C(C(=O)O)N',
            'serine': 'C(C(C(=O)O)N)O',
            'arginine': 'C(CC(C(=O)O)N)CN=C(N)N',
            'histidine': 'C1=C(NC=N1)CC(C(=O)O)N',
            'isoleucine': 'CCC(C)C(C(=O)O)N',
            'leucine': 'CC(C)CC(C(=O)O)N',
            'lysine': 'C(CCN)CC(C(=O)O)N',
            'methionine': 'CSCCC(C(=O)O)N',
            'phenylalanine': 'C1=CC=C(C=C1)CC(C(=O)O)N',
            'proline': 'C1CC(NC1)C(=O)O',
            'threonine': 'CC(C(C(=O)O)N)O',
            'tryptophan': 'C1=CC=C2C(=C1)C(=CN2)CC(C(=O)O)N',
            'tyrosine': 'C1=CC(=CC=C1CC(C(=O)O)N)O',
            'valine': 'CC(C)C(C(=O)O)N',
            'edestin': 'NC(CCSC)C(NC(C)C(NC(CC(N)=O)C(NC(C(C)([H])O)C(NC(CCCCN)C(NC(C)C(NC(CC(C)C)C(NC(CC(C)C)C(NC(CO)C(NC(CC(C)C)C(NC(CO)C(NC(CC1=CC=CC=C1)C(NC(CS)C(NC(CC1=CC=CC=C1)C(NC(CC1=CC=CC=C1)C(NC(CC(C)C)C(NC(CC(C)C)C(NC(CC(C)C)C(NC(CCC(N)=O)C(NC([H])C(NC(C(C)([H])O)C(NC(CO)C(NC(C)C(NC(C(CC)([H])C)C(NC(CO)C(NC(CCCCNC(N)=N)C(NC(CO)C(NC(CCCCNC(N)=N)C(NC(CO)C(NC(CCCCNC(N)=N)C(NC(CO)C(NC(CCC(N)=O)C(NC(CC(O)=O)C(NC(CCC(O)=O)C(NC(CO)C(NC(CC1=CC=C(O)C=C1)C(NC(CCCCNC(N)=N)C(NC(CCC(N)=O)C(NC(CCC(N)=O)C(NC(CC(N)=O)C(NC(CCC(N)=O)C(NC(CS)C(NC(CCC(N)=O)C(NC(C(CC)([H])C)C(NC(CC(O)=O)C(NC(CCCCNC(N)=N)C(NC(C(CC)([H])C)C(NC(CCC(O)=O)C(NC(C)C(NC(CCCCNC(N)=N)C(NC(CCC(O)=O)C(NC(C2CCCN2)C(NC(CC(O)=O)C(NC(C(C)([H])O)C(NC(CCCCNC(N)=N)C(NC(C(C)C)C(NC(CCC(O)=O)C(NC(C)C(NC(CCC(O)=O)C(NC(C)C(NC([H])C(NC(CC(C)C)C(NC(C(CC)([H])C)C(NC(CCC(O)=O)C(NC(CO)C(NC(CCC1=CNC2=C1C=CC=C2)C(NC(CC(N)=O)C(NC(C2CCCN2)C(NC(CC(N)=O)C(NC(CC1=CNC=N1)C(NC(CC(N)=O)C(NC(CCC(N)=O)C(NC(CC1=CC=CC=C1)C(NC(CCC(N)=O)C(NC(CS)C(NC(C)C(NC([H])C(NC(C(C)C)C(NC(C)C(NC(C(C)C)C(NC(C(C)C)C(NC(CCCCNC(N)=N)C(NC(CC1=CC=C(O)C=C1)C(NC(C(C)([H])O)C(NC(C(CC)([H])C)C(NC(CCC(N)=O)C(NC(CCC(N)=O)C(NC(CC(N)=O)C(NC([H])C(NC(CC(C)C)C(NC(CC1=CNC=N1)C(NC(CC(C)C)C(NC(C2CCCN2)C(NC(CO)C(NC(CC1=CC=C(O)C=C1)C(NC(C(C)([H])O)C(NC(CC(N)=O)C(NC(C(C)([H])O)C(NC(C2CCCN2)C(NC(CCC(N)=O)C(NC(CC(C)C)C(NC(C(C)C)C(NC(CC1=CC=C(O)C=C1)C(NC(C(CC)([H])C)C(NC(C(C)C)C(NC(CCCCN)C(NC([H])C(NC(CCCCNC(N)=N)C(NC([H])C(NC(C(CC)([H])C)C(NC(CC(C)C)C(NC([H])C(NC(C(C)C)C(NC(C(C)([H])O)C(NC(CC1=CC=CC=C1)C(NC(C2CCCN2)C(NC([H])C(NC(CS)C(NC(C2CCCN2)C(NC(CCC(O)=O)C(NC(C(C)([H])O)C(NC(CC1=CC=CC=C1)C(NC(CCC(O)=O)C(NC(CCC(O)=O)C(NC(CO)C(NC(CCC(N)=O)C(NC(CCCCNC(N)=N)C(NC([H])C(NC(CCC(N)=O)C(NC([H])C(NC(CCC(N)=O)C(NC([H])C(NC(CCC(N)=O)C(NC(CO)C(NC(CCC(N)=O)C(NC([H])C(NC(CO)C(NC(CCC(N)=O)C(NC(C2CCCN2)C(NC(CC(O)=O)C(NC(CCCCNC(N)=N)C(NC(CC1=CNC=N1)C(NC(CCC(N)=O)C(NC(CCCCN)C(NC(CC(C)C)C(NC(CCCCNC(N)=N)C(NC(CC1=CNC=N1)C(NC(C(C)C)C(NC(CCCCNC(N)=N)C(NC(CCC(O)=O)C(NC([H])C(NC(CC(O)=O)C(NC(C(CC)([H])C)C(NC(C(C)C)C(NC(C)C(NC(C(CC)([H])C)C(NC(C2CCCN2)C(NC(C)C(NC([H])C(NC(C(C)C)C(NC(C)C(NC(CC1=CC=C(O)C=C1)C(NC(CCC1=CNC2=C1C=CC=C2)C(NC(CO)C(NC(CC1=CC=C(O)C=C1)C(NC(CC(N)=O)C(NC(CC(N)=O)C(NC([H])C(NC(CC(O)=O)C(NC(CCC(N)=O)C(NC(CCC(N)=O)C(NC(CC(C)C)C(NC(C(C)C)C(NC(CC1=CC=CC=C1)C(NC(C(C)C)C(NC(CO)C(NC(CC(C)C)C(NC(CC(C)C)C(NC(CC(O)=O)C(NC(C(C)([H])O)C(NC(CO)C(NC(CC(N)=O)C(NC(C(C)C)C(NC(CC(N)=O)C(NC(CC(N)=O)C(NC(CCC(N)=O)C(NC(CC(C)C)C(NC(CC(O)=O)C(NC(CC(O)=O)C(NC(CC(N)=O)C(NC(C2CCCN2)C(NC(CCCCNC(N)=N)C(NC(CCCCNC(N)=N)C(NC(CC1=CC=CC=C1)C(NC(CC1=CC=C(O)C=C1)C(NC(CC(C)C)C(NC(C)C(NC([H])C(NC(CC(N)=O)C(NC(C2CCCN2)C(NC(CCC(O)=O)C(NC(CC(O)=O)C(NC(CCC(O)=O)C(NC(CC1=CC=CC=C1)C(NC(CCC(O)=O)C(NC(CCC(N)=O)C(NC(CC(C)C)C(NC(CCCCNC(N)=N)C(NC(CCCCNC(N)=N)C(NC(CCC(O)=O)C(NC([H])C(NC([H])C(NC(CCCCNC(N)=N)C(NC([H])C(NC(C)C(NC(CCCCNC(N)=N)C(NC(CC1=CC=CC=C1)C(NC(CC(O)=O)C(NC(CCC(O)=O)C(NC(CCCCNC(N)=N)C(NC(C(CC)([H])C)C(NC(CCCCNC(N)=N)C(NC(CCC(O)=O)C(NC(CCCCNC(N)=N)C(NC(CO)C(NC(CCC(O)=O)C(NC([H])C(NC(CCCCNC(N)=N)C(NC(CC1=CNC=N1)C(NC(CO)C(NC(CO)C(NC(CCC(O)=O)C(NC(CC(N)=O)C(NC(CC1=CC=C(O)C=C1)C(NC(CCCCNC(N)=N)C(NC(CC(N)=O)C(NC(C(CC)([H])C)C(NC(CC1=CC=CC=C1)C(NC(CCCCN)C(NC([H])C(NC(CC1=CC=CC=C1)C(NC(CC(N)=O)C(NC(CO)C(NC(CCCCNC(N)=N)C(NC(CC1=CC=C(O)C=C1)C(NC(CC(C)C)C(NC(CCC(O)=O)C(NC(CCC(O)=O)C(NC(C)C(NC(CC1=CC=CC=C1)C(NC(CC(N)=O)C(NC(C(C)C)C(NC(CC(O)=O)C(NC(CO)C(NC(CCC(O)=O)C(NC(C(C)([H])O)C(NC(C(C)C)C(NC(CCCCN)C(NC(CCCCNC(N)=N)C(NC(CC(C)C)C(NC(CCC(N)=O)C(NC([H])C(NC(CCC(N)=O)C(NC(CC(N)=O)C(NC(CC(O)=O)C(NC(CC(O)=O)C(NC(CCCCNC(N)=N)C(NC(CC(N)=O)C(NC(CO)C(NC(C(CC)([H])C)C(NC(C(CC)([H])C)C(NC(CCCCNC(N)=N)C(NC(C(C)C)C(NC(CCCCN)C(NC([H])C(NC(C(C)([H])O)C(NC(CC(C)C)C(NC(CC(O)=O)C(NC(CC(C)C)C(NC(C(C)C)C(NC(CO)C(NC(C2CCCN2)C(NC(CC(C)C)C(NC(CCCCNC(N)=N)C(NC(CO)C(NC(CO)C(NC(CCC(N)=O)C(NC(CCC(O)=O)C(NC(CC1=CNC=N1)C(NC(CCC(N)=O)C(NC(CCCCNC(N)=N)C(NC(CCC(O)=O)C(NC(CCC(O)=O)C(NC(CCCCNC(N)=N)C(NC(CC1=CC=C(O)C=C1)C(NC(CCC(O)=O)C(NC(CC(O)=O)C(NC(CCC(O)=O)C(NC(CCCCNC(N)=N)C(NC(CCC(N)=O)C(NC(CCCCNC(N)=N)C(NC(CCC(O)=O)C(NC(C(CC)([H])C)C(NC(CCC(O)=O)C(NC(CCC(N)=O)C(NC(CCC(O)=O)C(NC(CCCCNC(N)=N)C(NC(CCCCNC(N)=N)C(NC(CCCCNC(N)=N)C(NC(CCSC)C(NC(CO)C(NC(CCCCNC(N)=N)C(NC([H])C(NC([H])C(NC(CCCCNC(N)=N)C(NC(CC1=CC=C(O)C=C1)C(NC(CCC(O)=O)C(NC(C)C(NC(CC(N)=O)C(NC([H])C(NC(CC(C)C)C(NC(CCC(O)=O)C(NC(CCC(O)=O)C(NC(C(C)([H])O)C(NC(CC1=CC=CC=C1)C(NC(CS)C(NC(CO)C(NC(CCSC)C(NC(CCCCNC(N)=N)C(NC(CC(C)C)C(NC(CCCCNC(N)=N)C(NC(CCC(O)=O)C(NC(CC(N)=O)C(NC(C(CC)([H])C)C(NC([H])C(NC(CC(O)=O)C(NC(C2CCCN2)C(NC(CO)C(NC(CCCCNC(N)=N)C(NC(C)C(NC(CC(O)=O)C(NC(C(C)C)C(NC(CC1=CC=CC=C1)C(NC(C(C)([H])O)C(NC(C2CCCN2)C(NC(CCC(N)=O)C(NC(C)C(NC([H])C(NC(CCCCNC(N)=N)C(NC(C(CC)([H])C)C(NC(CO)C(NC(C(C)([H])O)C(NC(C(C)C)C(NC(CC(N)=O)C(NC(CO)C(NC(CC1=CC=C(O)C=C1)C(NC(CC(N)=O)C(NC(CC(C)C)C(NC(C2CCCN2)C(NC(C(CC)([H])C)C(NC(CC(C)C)C(NC(CCCCNC(N)=N)C(NC(CC1=CC=CC=C1)C(NC(CC(C)C)C(NC(CCC(N)=O)C(NC(CC(C)C)C(NC(CO)C(NC(C)C(NC(CCC(O)=O)C(NC(CCCCNC(N)=N)C(NC([H])C(NC(C(C)C)C(NC(CC(C)C)C(NC(CC1=CC=C(O)C=C1)C(NC(CCCCN)C(NC(CC(N)=O)C(NC(C)C(NC(C(CC)([H])C)C(NC(CC1=CC=C(O)C=C1)C(NC(C(C)([H])O)C(NC(C2CCCN2)C(NC(CC1=CNC=N1)C(NC(CCC1=CNC2=C1C=CC=C2)C(NC(CC(N)=O)C(NC(C(C)C)C(NC(CC(N)=O)C(NC(C)C(NC(CC1=CNC=N1)C(NC(CO)C(NC(C(C)C)C(NC(CCSC)C(NC(CC1=CC=C(O)C=C1)C(NC(C(C)C)C(NC(CC(C)C)C(NC(CCCCNC(N)=N)C(NC([H])C(NC(CCCCNC(N)=N)C(NC(C)C(NC(CCCCNC(N)=N)C(NC(C(C)C)C(NC(CCC(N)=O)C(NC(C(C)C)C(NC(C(C)C)C(NC(CC(N)=O)C(NC(CC1=CNC=N1)C(NC(CCSC)C(NC([H])C(NC(CCC(N)=O)C(NC(CCCCN)C(NC(CS)C(NC(CC1=CC=CC=C1)C(NC(CC(O)=O)C(NC([H])C(NC(CCC(O)=O)C(NC(C(C)C)C(NC(CCCCNC(N)=N)C(NC(CCC(N)=O)C(NC([H])C(NC(CCC(N)=O)C(NC(C(CC)([H])C)C(NC(C(C)C)C(NC(C(C)([H])O)C(NC(C(C)C)C(NC(C2CCCN2)C(NC(CCC(N)=O)C(NC(CC(N)=O)C(NC(CC1=CNC=N1)C(NC(C)C(NC(C(C)C)C(NC(C(C)C)C(NC(CCCCN)C(NC(CCC(N)=O)C(NC(C)C(NC(CO)C(NC(CO)C(NC(CC(O)=O)C(NC([H])C(NC(CC1=CC=CC=C1)C(NC(CCC(O)=O)C(NC(CCC1=CNC2=C1C=CC=C2)C(NC(C(C)C)C(NC(CO)C(NC(CC1=CC=CC=C1)C(NC(CCCCN)C(NC(C(C)([H])O)C(NC(CC(N)=O)C(NC(CC(O)=O)C(NC(CC(N)=O)C(NC(C)C(NC(CCC1=CNC2=C1C=CC=C2)C(NC(C(C)C)C(NC(CO)C(NC(C2CCCN2)C(NC(CC(C)C)C(NC(C)C(NC([H])C(NC(CCCCNC(N)=N)C(NC(C(C)([H])O)C(NC(CO)C(NC(C(C)C)C(NC(C(CC)([H])C)C(NC(CCCCNC(N)=N)C(NC(C)C(NC(CC(C)C)C(NC(C2CCCN2)C(NC(CCC(O)=O)C(NC(C)C(NC(C(C)C)C(NC(CC(C)C)C(NC(C)C(NC(CC(N)=O)C(NC(C)C(NC(CC1=CC=CC=C1)C(NC(CCC(N)=O)C(NC(C(CC)([H])C)C(NC(CO)C(NC(CCCCNC(N)=N)C(NC(CC(O)=O)C(NC(CCC(N)=O)C(NC(C)C(NC(CCCCNC(N)=N)C(NC(CC(N)=O)C(NC(CC(C)C)C(NC(CCCCN)C(NC(CC1=CC=C(O)C=C1)C(NC(CC(N)=O)C(NC(CCCCNC(N)=N)C(NC(CCC(O)=O)C(NC(CCC(O)=O)C(NC(C(C)([H])O)C(NC(C(C)C)C(NC(CC(C)C)C(NC(CC(C)C)C(NC(C(C)([H])O)C(NC(CO)C(NC(CO)C(NC(C(C)([H])O)C(NC(CO)C(NC(CO)C(NC(CCCCNC(N)=N)C(NC(CCCCNC(N)=N)C(NC(CCC(O)=O)C(NC(CC(O)=O)C(NC(CCCCNC(N)=N)C(NC(CC1=CC=C(O)C=C1)C(NC(CCC(O)=O)C(NC(CCCCNC(N)=N)C(NC(CCCCNC(N)=N)C(NC(C)C(NC(C(C)([H])O)C(NC(C)C(NCC(O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O',
            'zeatin': 'CC(=CCNC1=NC=NC2=C1NC=N2)CO',
            'zeatin nucleoside': 'CC(=CCNC1=C2C(=NC=N1)N(C=N2)C3C(C(C(O3)CO)O)O)CO',
            'glucosidase': 'NC(CCSC)C(NC(CCC(N)=O)C(NC(CC(O)=O)C(NC(CC(N)=O)C(NC(CCSC)C(NC(CCSC)C(NC(CCC1=CNC2=C1C=CC=C2)C(NC(CCC1=CNC2=C1C=CC=C2)C(NC(CCCCNC(N)=N)C(NC([H])C(NC([H])C(NC(C(C)C)C(NC(C(CC)([H])C)C(NC(CC1=CC=C(O)C=C1)C(NC(CCC(N)=O)C(NC(C(CC)([H])C)C(NC(CC1=CC=C(O)C=C1)C(NC(C2CCCN2)C(NC(CCCCNC(N)=N)C(NC(CO)C(NC(CC1=CC=CC=C1)C(NC(CC(C)C)C(NC(CC(O)=O)C(NC(CO)C(NC(CCCCNC(N)=N)C(NC([H])C(NC(CC(O)=O)C(NC([H])C(NC(C(C)C)C(NC([H])C(NC(CC(O)=O)C(NC(CC(C)C)C(NC(CC(N)=O)C(NC([H])C(NC(C(CC)([H])C)C(NC(C(C)([H])O)C(NC(CCC(O)=O)C(NC(CCCCN)C(NC(CC(C)C)C(NC(CC(O)=O)C(NC(CC1=CC=C(O)C=C1)C(NC(C(C)C)C(NC(C)C(NC(CO)C(NC(CC(C)C)C(NC(CC(N)=O)C(NC(C(C)C)C(NC(CC(O)=O)C(NC([H])C(NC(C(CC)([H])C)C(NC(CCC1=CNC2=C1C=CC=C2)C(NC(CC(C)C)C(NC(CO)C(NC(C2CCCN2)C(NC(CC1=CC=CC=C1)C(NC(CC1=CC=CC=C1)C(NC(C(C)([H])O)C(NC(CO)C(NC(C2CCCN2)C(NC(CCSC)C(NC(CC(C)C)C(NC(CC(O)=O)C(NC(CC1=CC=CC=C1)C(NC([H])C(NC(CC1=CC=C(O)C=C1)C(NC(CC(O)=O)C(NC(C(C)C)C(NC(CO)C(NC(CC(O)=O)C(NC(CC1=CC=C(O)C=C1)C(NC(CCCCNC(N)=N)C(NC(CC(O)=O)C(NC(C(C)C)C(NC(CC(O)=O)C(NC(C2CCCN2)C(NC(CCSC)C(NC(CC1=CC=CC=C1)C(NC([H])C(NC(C(C)([H])O)C(NC(CC(C)C)C(NC(CCC(O)=O)C(NC(CC(O)=O)C(NC(CC1=CC=CC=C1)C(NC(CCCCN)C(NC(C)C(NC(CC(C)C)C(NC(CC(C)C)C(NC(CCC(O)=O)C(NC(CCCCN)C(NC(C)C(NC(CC1=CNC=N1)C(NC(CO)C(NC(CC(C)C)C(NC([H])C(NC(CC(C)C)C(NC(CCCCN)C(NC(C(C)C)C(NC(CCSC)C(NC(C(CC)([H])C)C(NC(CC(O)=O)C(NC(CCC(N)=O)C(NC(C(C)C)C(NC(C(CC)([H])C)C(NC(CO)C(NC(CC1=CNC=N1)C(NC(C(C)([H])O)C(NC(CO)C(NC(CC(O)=O)C(NC(CCC(N)=O)C(NC(CC1=CNC=N1)C(NC(C2CCCN2)C(NC(CCC1=CNC2=C1C=CC=C2)C(NC(CC1=CC=CC=C1)C(NC(CCC(N)=O)C(NC(CCC(O)=O)C(NC(CO)C(NC(CCCCNC(N)=N)C(NC(CCC(N)=O)C(NC(CC(N)=O)C(NC(CCCCNC(N)=N)C(NC(C(C)([H])O)C(NC(CC(N)=O)C(NC(C2CCCN2)C(NC(CCCCN)C(NC(C)C(NC(CC(O)=O)C(NC(CCC1=CNC2=C1C=CC=C2)C(NC(CC1=CC=CC=C1)C(NC(C(C)C)C(NC(CCC1=CNC2=C1C=CC=C2)C(NC(C)C(NC(CC(O)=O)C(NC(C2CCCN2)C(NC(CCCCN)C(NC(C2CCCN2)C(NC(CC(O)=O)C(NC([H])C(NC(C(C)([H])O)C(NC(C2CCCN2)C(NC(C2CCCN2)C(NC(CC(N)=O)C(NC(CC(N)=O)C(NC(CCC1=CNC2=C1C=CC=C2)C(NC(CC(C)C)C(NC(CO)C(NC(C(CC)([H])C)C(NC(CC1=CC=CC=C1)C(NC([H])C(NC([H])C(NC(CO)C(NC(C)C(NC(CCC1=CNC2=C1C=CC=C2)C(NC(C(C)([H])O)C(NC(CC1=CC=CC=C1)C(NC(CC(O)=O)C(NC(CO)C(NC(CCCCNC(N)=N)C(NC(CCCCNC(N)=N)C(NC(CCC(N)=O)C(NC(CCC(N)=O)C(NC(CC1=CC=C(O)C=C1)C(NC(CC1=CC=C(O)C=C1)C(NC(CC(C)C)C(NC(CC1=CNC=N1)C(NC(CC(N)=O)C(NC(CC1=CC=CC=C1)C(NC(CC(C)C)C(NC(C(C)([H])O)C(NC(CO)C(NC(CCC(N)=O)C(NC(C2CCCN2)C(NC(CC(O)=O)C(NC(C(C)C)C(NC(CC(N)=O)C(NC(CC1=CC=CC=C1)C(NC(CC1=CNC=N1)C(NC(CC1=CNC=N1)C(NC(C2CCCN2)C(NC(CCC(O)=O)C(NC(C)C(NC(CCCCNC(N)=N)C(NC(CCC(N)=O)C(NC(C)C(NC(CCC(N)=O)C(NC(CC(C)C)C(NC(CC(O)=O)C(NC(CC(N)=O)C(NC(CCSC)C(NC(CCCCNC(N)=N)C(NC(CC1=CC=CC=C1)C(NC(CCC1=CNC2=C1C=CC=C2)C(NC(CC(C)C)C(NC(CC(O)=O)C(NC(CC(C)C)C(NC([H])C(NC(C(C)C)C(NC(CC(O)=O)C(NC([H])C(NC(CC1=CC=CC=C1)C(NC(CCCCNC(N)=N)C(NC(CC(C)C)C(NC(CC(O)=O)C(NC(C(C)([H])O)C(NC(C(C)C)C(NC(CC(N)=O)C(NC(CC1=CC=CC=C1)C(NC(CC1=CC=C(O)C=C1)C(NC(CC1=CC=CC=C1)C(NC(CC1=CNC=N1)C(NC(CC(O)=O)C(NC(C)C(NC(CCC(O)=O)C(NC(CC(C)C)C(NC(CCCCNC(N)=N)C(NC(CC(O)=O)C(NC(CC(N)=O)C(NC(C2CCCN2)C(NC(C2CCCN2)C(NC(C(C)C)C(NC(C2CCCN2)C(NC(CCCCN)C(NC([H])C(NC(CCC(O)=O)C(NC(C)C(NC(CCCCN)C(NC(C(C)([H])O)C(NC(CC(C)C)C(NC([H])C(NC(C)C(NC(C2CCCN2)C(NC(CCC(O)=O)C(NC(C)C(NC(CC(N)=O)C(NC(C2CCCN2)C(NC(CC1=CC=C(O)C=C1)C(NC(C(C)([H])O)C(NC(CCC1=CNC2=C1C=CC=C2)C(NC(CCC(N)=O)C(NC(CCCCNC(N)=N)C(NC(CC1=CNC=N1)C(NC(C(C)C)C(NC(CC1=CC=C(O)C=C1)C(NC(CC(O)=O)C(NC(CC(C)C)C(NC(CO)C(NC(CCCCNC(N)=N)C(NC(C2CCCN2)C(NC(CCC(O)=O)C(NC(CC(N)=O)C(NC(CC(C)C)C(NC(CC(O)=O)C(NC(CC1=CC=CC=C1)C(NC(CC(C)C)C(NC(CCCCN)C(NC(CC(O)=O)C(NC(CC(C)C)C(NC(CCCCNC(N)=N)C(NC(C)C(NC(CC(C)C)C(NC(CCSC)C(NC(CC(O)=O)C(NC(CCC(O)=O)C(NC(CC1=CC=C(O)C=C1)C(NC(C2CCCN2)C(NC([H])C(NC(C(C)([H])O)C(NC(C(C)([H])O)C(NC(C(C)([H])O)C(NC(C(C)C)C(NC([H])C(NC(CCC(O)=O)C(NC(C(CC)([H])C)C(NC([H])C(NC(CC(O)=O)C(NC(CC(O)=O)C(NC(CC(N)=O)C(NC(C2CCCN2)C(NC(CC(C)C)C(NC(CCC(O)=O)C(NC(CCCCNC(N)=N)C(NC(CCSC)C(NC(C)C(NC(CCC(O)=O)C(NC(CC1=CC=C(O)C=C1)C(NC(C(C)([H])O)C(NC(C)C(NC([H])C(NC([H])C(NC(CC(O)=O)C(NC(CCCCN)C(NC(CC(C)C)C(NC(CC1=CNC=N1)C(NC(CCSC)C(NC(C)C(NC(CC1=CC=C(O)C=C1)C(NC(C(C)([H])O)C(NC(CC1=CC=CC=C1)C(NC(CC(O)=O)C(NC(CC(C)C)C(NC(CC(C)C)C(NC(CC(N)=O)C(NC(CCSC)C(NC(C2CCCN2)C(NC(CC1=CNC=N1)C(NC(CO)C(NC(C)C(NC(CO)C(NC(CC1=CC=C(O)C=C1)C(NC(CC(C)C)C(NC(CCCCNC(N)=N)C(NC(CCC(O)=O)C(NC(C(C)C)C(NC(C(CC)([H])C)C(NC(CCC(O)=O)C(NC(CCCCNC(N)=N)C(NC(CC1=CC=CC=C1)C(NC(CCC(N)=O)C(NC(CCCCNC(N)=N)C(NC(CC(C)C)C(NC(C)C(NC([H])C(NC(CC(O)=O)C(NC(C)C(NC(CCC1=CNC2=C1C=CC=C2)C(NC(C2CCCN2)C(NC(CS)C(NC(CCC1=CNC2=C1C=CC=C2)C(NC(C)C(NC(C(C)([H])O)C(NC(CO)C(NC(CC(N)=O)C(NC(CC1=CNC=N1)C(NC(CC(O)=O)C(NC(C(C)C)C(NC(C(C)C)C(NC(CCCCNC(N)=N)C(NC(CO)C(NC(C)C(NC(C(C)([H])O)C(NC(CCCCNC(N)=N)C(NC(CCC1=CNC2=C1C=CC=C2)C(NC([H])C(NC(C)C(NC(CC(O)=O)C(NC(CCC(O)=O)C(NC(CC(O)=O)C(NC(C2CCCN2)C(NC(CC1=CNC=N1)C(NC(C)C(NC(CC1=CC=C(O)C=C1)C(NC(C2CCCN2)C(NC(CCCCN)C(NC(C(C)C)C(NC(CCSC)C(NC(CC(C)C)C(NC(C)C(NC(C(C)C)C(NC(CC(C)C)C(NC(CC1=CC=CC=C1)C(NC(CO)C(NC(CC(C)C)C(NC(CCCCNC(N)=N)C(NC([H])C(NC(CO)C(NC(C(C)C)C(NC(CS)C(NC(CC(C)C)C(NC(CC1=CC=C(O)C=C1)C(NC(CCC(N)=O)C(NC([H])C(NC(CCC(O)=O)C(NC(CCC(O)=O)C(NC(CC(C)C)C(NC([H])C(NC(CC(C)C)C(NC(C2CCCN2)C(NC(CCC(O)=O)C(NC(C)C(NC(CC(O)=O)C(NC(C(C)C)C(NC(C2CCCN2)C(NC(CC1=CC=CC=C1)C(NC(CCC(O)=O)C(NC(CCCCNC(N)=N)C(NC(C(CC)([H])C)C(NC(CCC(N)=O)C(NC(CC(O)=O)C(NC(C2CCCN2)C(NC(CC1=CC=C(O)C=C1)C(NC([H])C(NC(CCCCN)C(NC(C(C)C)C(NC(CC(C)C)C(NC(CCC1=CNC2=C1C=CC=C2)C(NC(C2CCCN2)C(NC(CCC(O)=O)C(NC(CC1=CC=CC=C1)C(NC(CCCCN)C(NC([H])C(NC(CCCCNC(N)=N)C(NC(CC(O)=O)C(NC([H])C(NC(CS)C(NC(CCCCNC(N)=N)C(NC(C(C)([H])O)C(NC(C2CCCN2)C(NC(CCSC)C(NC(C2CCCN2)C(NC(CCC1=CNC2=C1C=CC=C2)C(NC(C(C)([H])O)C(NC(CC(O)=O)C(NC([H])C(NC(CCC(O)=O)C(NC(CCC(N)=O)C(NC([H])C(NC([H])C(NC(CC1=CC=CC=C1)C(NC(CO)C(NC(C2CCCN2)C(NC(C(C)C)C(NC(CCC(O)=O)C(NC(C2CCCN2)C(NC(CCC1=CNC2=C1C=CC=C2)C(NC(CC(C)C)C(NC(C2CCCN2)C(NC(CCSC)C(NC(CCC(O)=O)C(NC(C)C(NC(CCCCNC(N)=N)C(NC(CC1=CNC=N1)C(NC(CC(C)C)C(NC(CCC(O)=O)C(NC(CC(C)C)C(NC(C)C(NC(C(C)C)C(NC(CO)C(NC(CCCCNC(N)=N)C(NC(CCC(N)=O)C(NC(CCC(N)=O)C(NC(CC(O)=O)C(NC(CC(O)=O)C(NC(C2CCCN2)C(NC(CC(N)=O)C(NC(C)C(NC(C(C)([H])O)C(NC(CC(C)C)C(NC(CC(N)=O)C(NC(C(C)([H])O)C(NC(C(C)C)C(NC(CCCCNC(N)=N)C(NC(C)C(NC(CC(C)C)C(NC(CC(C)C)C(NC(C)C(NC(CC1=CC=CC=C1)C(NC(CCCCNC(N)=N)C(NC(CCCCNC(N)=N)C(NC(CO)C(NC(CC1=CNC=N1)C(NC(C2CCCN2)C(NC(C)C(NC(CC(C)C)C(NC(CC1=CC=CC=C1)C(NC(CC(O)=O)C(NC([H])C(NC(CC(O)=O)C(NC(CC(C)C)C(NC(CO)C(NC(CC(C)C)C(NC(C(C)C)C(NC(CC(O)=O)C(NC(C(C)C)C(NC([H])C(NC(CC(O)=O)C(NC(CC(O)=O)C(NC(CC(C)C)C(NC(CC(C)C)C(NC([H])C(NC(CC1=CC=CC=C1)C(NC(C(C)([H])O)C(NC(CCCCNC(N)=N)C(NC(CCC(N)=O)C(NC(CCCCN)C(NC([H])C(NC(CC(O)=O)C(NC(CCC(O)=O)C(NC(C(C)([H])O)C(NC(CC(C)C)C(NC(CC(C)C)C(NC(CS)C(NC(C(C)C)C(NC(CC1=CC=CC=C1)C(NC(CC(N)=O)C(NC(CC(C)C)C(NC(C(C)([H])O)C(NC([H])C(NC(CCC(N)=O)C(NC(CCC(O)=O)C(NC(CCC(N)=O)C(NC(CCC(N)=O)C(NC(C(C)([H])O)C(NC(C(C)([H])O)C(NC(CC(C)C)C(NC(C2CCCN2)C(NC(C(C)C)C(NC(CCC(O)=O)C(NC(C(C)C)C(NC(C)C(NC(CO)C(NC(CC(O)=O)C(NC(CC(C)C)C(NC(C2CCCN2)C(NC(C(C)C)C(NC(C)C(NC(CC1=CNC=N1)C(NC(CC1=CC=CC=C1)C(NC(C(C)([H])O)C(NC(C)C(NC(C(C)([H])O)C(NC(CCCCNC(N)=N)C(NC(CC(O)=O)C(NC([H])C(NC(CO)C(NC(C(C)([H])O)C(NC(CC(C)C)C(NC(C(C)([H])O)C(NC(CC(C)C)C(NC(C2CCCN2)C(NC(C)C(NC(CC1=CC=C(O)C=C1)C(NC(CCC(N)=O)C(NC(C)C(NC(C)C(NC(CC1=CC=CC=C1)C(NC(CCSC)C(NC(CCC(N)=O)C(NC(C(C)C)C(NC(C)C(NCC(O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O',
            'polyphenol oxidase': 'NC(CCSC)C(NC(C)C(NC(C(C)([H])O)C(NC(CC(C)C)C(NC(CO)C(NC(CO)C(NC(C2CCCN2)C(NC(C(C)([H])O)C(NC(C(CC)([H])C)C(NC(C(CC)([H])C)C(NC(C(C)([H])O)C(NC(C(C)([H])O)C(NC(C(C)([H])O)C(NC(CO)C(NC(C(CC)([H])C)C(NC(CC(C)C)C(NC(CC(C)C)C(NC(CC(N)=O)C(NC(CC(N)=O)C(NC(C2CCCN2)C(NC(CC1=CC=CC=C1)C(NC(CC(C)C)C(NC(C2CCCN2)C(NC(CCCCN)C(NC(C(C)([H])O)C(NC(C2CCCN2)C(NC(CCC(N)=O)C(NC(CC(C)C)C(NC(CO)C(NC(C)C(NC(CC1=CNC=N1)C(NC(CC1=CNC=N1)C(NC(CC1=CNC=N1)C(NC(CCCCNC(N)=N)C(NC([H])C(NC(C(C)C)C(NC(CCCCNC(N)=N)C(NC(CO)C(NC(C(C)C)C(NC(CC(N)=O)C(NC([H])C(NC(CCCCN)C(NC(C(C)C)C(NC(CO)C(NC(CS)C(NC(CCC(N)=O)C(NC(C(C)([H])O)C(NC(CCCCN)C(NC(CC(N)=O)C(NC(CC(N)=O)C(NC(CC(N)=O)C(NC([H])C(NC(CC(N)=O)C(NC(CC(O)=O)C(NC(CC(O)=O)C(NC(CC(N)=O)C(NC(CC(N)=O)C(NC(CCC(N)=O)C(NC(CC1=CC=CC=C1)C(NC(CCC(N)=O)C(NC(CC(C)C)C(NC(C(CC)([H])C)C(NC(CCC(N)=O)C(NC(CC(N)=O)C(NC(C2CCCN2)C(NC(CC(N)=O)C(NC(C(C)([H])O)C(NC(CC(N)=O)C(NC(C(C)([H])O)C(NC(C2CCCN2)C(NC(CC1=CC=C(O)C=C1)C(NC(CC(C)C)C(NC(CC(C)C)C(NC(CC(O)=O)C(NC(CCCCNC(N)=N)C(NC(CCCCNC(N)=N)C(NC(CC(N)=O)C(NC(C(CC)([H])C)C(NC(CC(C)C)C(NC(CC(C)C)C(NC([H])C(NC(CC(C)C)C(NC([H])C(NC([H])C(NC(CCSC)C(NC(CC1=CC=C(O)C=C1)C(NC(C)C(NC(C)C(NC(CC(C)C)C(NC([H])C(NC(CO)C(NC(CCC(O)=O)C(NC([H])C(NC(C)C(NC(CC(N)=O)C(NC(CC1=CC=C(O)C=C1)C(NC(CC1=CC=C(O)C=C1)C(NC(CC(N)=O)C(NC(C(C)([H])O)C(NC(CC(C)C)C(NC(C)C(NC(C)C(NC(C2CCCN2)C(NC(C(CC)([H])C)C(NC(CC(C)C)C(NC(C2CCCN2)C(NC(CC(O)=O)C(NC(C(C)C)C(NC(CCC(O)=O)C(NC(CCCCN)C(NC(CS)C(NC(C(C)([H])O)C(NC(CC(C)C)C(NC(CO)C(NC(CC(O)=O)C(NC(C)C(NC(CC(C)C)C(NC(CCC1=CNC2=C1C=CC=C2)C(NC(CC(O)=O)C(NC([H])C(NC(CO)C(NC(C(C)C)C(NC([H])C(NC(CC(O)=O)C(NC(CC1=CNC=N1)C(NC(CS)C(NC(CS)C(NC(C2CCCN2)C(NC(C2CCCN2)C(NC(C2CCCN2)C(NC(CC1=CC=CC=C1)C(NC(CC(O)=O)C(NC(CC(C)C)C(NC(CC(N)=O)C(NC(C(CC)([H])C)C(NC(C(C)([H])O)C(NC(CCCCN)C(NC(CC(O)=O)C(NC(CC1=CC=CC=C1)C(NC(CCC(O)=O)C(NC(CC1=CC=CC=C1)C(NC(CCCCN)C(NC(CC(N)=O)C(NC(CC1=CC=C(O)C=C1)C(NC(CC1=CNC=N1)C(NC(CC(N)=O)C(NC(CC1=CNC=N1)C(NC(C(C)C)C(NC(CCCCN)C(NC(CCCCN)C(NC(C(C)C)C(NC(CCCCNC(N)=N)C(NC(CCCCNC(N)=N)C(NC(C2CCCN2)C(NC(C)C(NC(CC1=CNC=N1)C(NC(CCCCN)C(NC(C)C(NC(CC1=CC=C(O)C=C1)C(NC(CCC(O)=O)C(NC(CC(O)=O)C(NC(CCC(N)=O)C(NC(CCC(O)=O)C(NC(CCC1=CNC2=C1C=CC=C2)C(NC(CC(C)C)C(NC(CC(N)=O)C(NC(CC(O)=O)C(NC(CC1=CC=C(O)C=C1)C(NC(CCCCN)C(NC(CCCCNC(N)=N)C(NC(C)C(NC(C(CC)([H])C)C(NC(C)C(NC(C(CC)([H])C)C(NC(CCSC)C(NC(CCCCN)C(NC(CO)C(NC(CC(C)C)C(NC(C2CCCN2)C(NC(CCSC)C(NC(CO)C(NC(CC(O)=O)C(NC(C2CCCN2)C(NC(CCCCNC(N)=N)C(NC(CO)C(NC(CC1=CNC=N1)C(NC(CCSC)C(NC(CCC(N)=O)C(NC(CCC(N)=O)C(NC(C)C(NC(CCCCNC(N)=N)C(NC(C(C)C)C(NC(CC1=CNC=N1)C(NC(CS)C(NC(C)C(NC(CC1=CC=C(O)C=C1)C(NC(CS)C(NC(CC(O)=O)C(NC([H])C(NC(CO)C(NC(CC1=CC=C(O)C=C1)C(NC(C2CCCN2)C(NC(C(C)C)C(NC(CC(C)C)C(NC([H])C(NC(CC1=CNC=N1)C(NC(CC(N)=O)C(NC(CC(O)=O)C(NC(C(C)([H])O)C(NC(CCCCNC(N)=N)C(NC(CC(C)C)C(NC(CCC(O)=O)C(NC(C(C)C)C(NC(CC1=CNC=N1)C(NC(C)C(NC(CO)C(NC(CCC1=CNC2=C1C=CC=C2)C(NC(CC(C)C)C(NC(CC1=CC=CC=C1)C(NC(C2CCCN2)C(NC(CO)C(NC(CC1=CC=CC=C1)C(NC(CC1=CNC=N1)C(NC(CCCCNC(N)=N)C(NC(CCC1=CNC2=C1C=CC=C2)C(NC(CC1=CC=C(O)C=C1)C(NC(CC(C)C)C(NC(CC1=CC=C(O)C=C1)C(NC(CC1=CC=CC=C1)C(NC(CC1=CC=C(O)C=C1)C(NC(CCC(O)=O)C(NC(CCCCNC(N)=N)C(NC(C(CC)([H])C)C(NC(CC(C)C)C(NC([H])C(NC(CCCCN)C(NC(CC(C)C)C(NC(C(CC)([H])C)C(NC(CC(N)=O)C(NC(CCCCN)C(NC(C2CCCN2)C(NC(CC(O)=O)C(NC(CC1=CC=CC=C1)C(NC(C)C(NC(CC(C)C)C(NC(C2CCCN2)C(NC(CC1=CC=C(O)C=C1)C(NC(CCC1=CNC2=C1C=CC=C2)C(NC(CC(N)=O)C(NC(CCC1=CNC2=C1C=CC=C2)C(NC(CC(O)=O)C(NC(CC1=CNC=N1)C(NC(CCCCNC(N)=N)C(NC(CC(O)=O)C(NC([H])C(NC(CCSC)C(NC(CCCCNC(N)=N)C(NC(C(CC)([H])C)C(NC(C2CCCN2)C(NC(CCC(O)=O)C(NC(C(CC)([H])C)C(NC(CC1=CC=CC=C1)C(NC(CCCCN)C(NC(CCC(O)=O)C(NC(CCSC)C(NC(CC(O)=O)C(NC(CO)C(NC(C2CCCN2)C(NC(CC(C)C)C(NC(CC1=CC=CC=C1)C(NC(CC(O)=O)C(NC(C2CCCN2)C(NC(CC(N)=O)C(NC(CCCCNC(N)=N)C(NC(CC(N)=O)C(NC(C(C)([H])O)C(NC(CC(N)=O)C(NC(CC1=CNC=N1)C(NC(CC(C)C)C(NC(CC(O)=O)C(NC(CCCCN)C(NC(CCSC)C(NC(CCSC)C(NC(CC(N)=O)C(NC(CC(C)C)C(NC(CO)C(NC(CC1=CC=CC=C1)C(NC(C(C)C)C(NC(CO)C(NC(CC(O)=O)C(NC(CCC(O)=O)C(NC(CCC(O)=O)C(NC([H])C(NC(CO)C(NC(CC(O)=O)C(NC(C(C)C)C(NC(CC(N)=O)C(NC(CCC(O)=O)C(NC(CC(O)=O)C(NC(CC(O)=O)C(NC(CCC(N)=O)C(NC(CC1=CC=C(O)C=C1)C(NC(CCC(O)=O)C(NC(CCC(O)=O)C(NC(CC(N)=O)C(NC(C(CC)([H])C)C(NC(CC(C)C)C(NC(CC(C)C)C(NC(CCSC)C(NC(CCCCNC(N)=N)C(NC(CCCCN)C(NC(C)C(NC(CCSC)C(NC(C(C)C)C(NC(CC1=CC=C(O)C=C1)C(NC(C2CCCN2)C(NC(CO)C(NC(C(C)C)C(NC(CO)C(NC(CC(O)=O)C(NC(CC(O)=O)C(NC(C2CCCN2)C(NC(CC(N)=O)C(NC(CCCCN)C(NC(C)C(NC(CCC(O)=O)C(NC(CC(C)C)C(NC(CC1=CC=CC=C1)C(NC(CC(C)C)C(NC([H])C(NC(CO)C(NC(C2CCCN2)C(NC(CC1=CC=C(O)C=C1)C(NC(CCCCNC(N)=N)C(NC(C)C(NC([H])C(NC(CC(O)=O)C(NC(CCCCN)C(NC(CCSC)C(NC(CCC(O)=O)C(NC([H])C(NC(CC(O)=O)C(NC(C(C)C)C(NC(CO)C(NC([H])C(NC(C)C(NC([H])C(NC(C(CC)([H])C)C(NC(CC(C)C)C(NC(CCC(O)=O)C(NC(CCCCNC(N)=N)C(NC(CCSC)C(NC(C2CCCN2)C(NC(CC1=CNC=N1)C(NC(CC(N)=O)C(NC(CO)C(NC(C(C)C)C(NC(CC1=CNC=N1)C(NC(C(C)C)C(NC(CCC1=CNC2=C1C=CC=C2)C(NC(C(C)([H])O)C(NC(CCCCNC(N)=N)C(NC(CO)C(NC(CC(N)=O)C(NC(C(C)([H])O)C(NC(C(CC)([H])C)C(NC(CCCCN)C(NC([H])C(NC(CC(N)=O)C(NC(CCC(N)=O)C(NC(CC(O)=O)C(NC(CCSC)C(NC([H])C(NC(C)C(NC(CC1=CC=CC=C1)C(NC(CCC1=CNC2=C1C=CC=C2)C(NC(CO)C(NC(C)C(NC([H])C(NC(CCCCNC(N)=N)C(NC(CC(O)=O)C(NC(C2CCCN2)C(NC(CC(C)C)C(NC(CC1=CC=CC=C1)C(NC(CC1=CC=C(O)C=C1)C(NC(CS)C(NC(CC1=CNC=N1)C(NC(CC1=CNC=N1)C(NC(CO)C(NC(CC(N)=O)C(NC(C(C)C)C(NC(CC(O)=O)C(NC(CCCCNC(N)=N)C(NC(CCSC)C(NC(CCC1=CNC2=C1C=CC=C2)C(NC(CO)C(NC(CC(C)C)C(NC(CCC1=CNC2=C1C=CC=C2)C(NC(C(C)([H])O)C(NC(CC(O)=O)C(NC(C(C)C)C(NC(CC(C)C)C(NC(CC1=CNC=N1)C(NC([H])C(NC([H])C(NC(CC(N)=O)C(NC(CC1=CC=CC=C1)C(NC(C2CCCN2)C(NC(CCCCN)C(NC(C2CCCN2)C(NC(CCC(O)=O)C(NC(CC1=CC=C(O)C=C1)C(NC(CC(O)=O)C(NC(CC(O)=O)C(NC(CC1=CC=C(O)C=C1)C(NC(CCCCNC(N)=N)C(NC(CC(N)=O)C(NC(C)C(NC(CC1=CC=C(O)C=C1)C(NC(CC1=CC=CC=C1)C(NC(CC1=CC=C(O)C=C1)C(NC(CC1=CC=CC=C1)C(NC(CC1=CC=C(O)C=C1)C(NC(CC(O)=O)C(NC(CCC(O)=O)C(NC(CC(N)=O)C(NC(C)C(NC(CC(N)=O)C(NC(C2CCCN2)C(NC(C(C)C)C(NC(CCCCNC(N)=N)C(NC(C(C)C)C(NC(CC1=CC=C(O)C=C1)C(NC(C(C)C)C(NC(CCCCNC(N)=N)C(NC(CC(O)=O)C(NC(CO)C(NC(CC1=CC=CC=C1)C(NC(CC(O)=O)C(NC(C(C)([H])O)C(NC(CCC(O)=O)C(NC(CCCCNC(N)=N)C(NC(CC(C)C)C(NC([H])C(NC(CC1=CC=C(O)C=C1)C(NC(CCCCN)C(NC(CC1=CC=C(O)C=C1)C(NC(CCC(O)=O)C(NC(CC(O)=O)C(NC(CCC(N)=O)C(NC(CCC(O)=O)C(NC(CC(C)C)C(NC(C2CCCN2)C(NC(CCC1=CNC2=C1C=CC=C2)C(NC(CCSC)C(NC(CO)C(NC(C(CC)([H])C)C(NC(C(C)([H])O)C(NC(CCC(N)=O)C(NC(CCC(N)=O)C(NC(CCC(N)=O)C(NC(CCC(N)=O)C(NC(CCC(N)=O)C(NC(CCC(N)=O)C(NC(CCC(N)=O)C(NC(CCCCNC(N)=N)C(NC(CCC(N)=O)C(NC(CCC(N)=O)C(NC(CCC(N)=O)C(NC(CCCCNC(N)=N)C(NC(CCC(N)=O)C(NC(C2CCCN2)C(NC(CC(C)C)C(NC(CC(C)C)C(NC([H])C(NC([H])C(NC(CCCCNC(N)=N)C(NC(CC(C)C)C(NC(CCCCN)C(NC(C(C)([H])O)C(NC(CCCCNC(N)=N)C(NC(C(C)([H])O)C(NC(CC1=CC=CC=C1)C(NC(CO)C(NC(CC(C)C)C(NC(C(C)C)C(NC(CCCCN)C(NC(CCCCN)C(NC(C(C)C)C(NC(CC(C)C)C(NC(C(C)([H])O)C(NC(CCC(O)=O)C(NC(CC(C)C)C(NC(CCCCN)C(NC(C(C)C)C(NC(CCSC)C(NC(CC(C)C)C(NC(C2CCCN2)C(NC(CC(C)C)C(NC(C2CCCN2)C(NC(CC(C)C)C(NC(CCCCN)C(NC(CC1=CC=C(O)C=C1)C(NC(CO)C(NC(C(C)C)C(NC(C(CC)([H])C)C(NC(CCCCN)C(NC(C(C)([H])O)C(NC(CCCCN)C(NC(C(C)C)C(NC(CC(O)=O)C(NC(CCCCNC(N)=N)C(NC(C2CCCN2)C(NC(CCCCN)C(NC(CCCCN)C(NC(CO)C(NC(CCCCNC(N)=N)C(NC(C(C)([H])O)C(NC(CCCCN)C(NC(CCC(O)=O)C(NC(CC(O)=O)C(NC(CCCCN)C(NC(CC(C)C)C(NC(CCC(O)=O)C(NC(CC1=CNC=N1)C(NC(CCC(O)=O)C(NC(CCC(O)=O)C(NC(C(C)C)C(NC(CC(C)C)C(NC(C(C)C)C(NC(C(CC)([H])C)C(NC(CC(N)=O)C(NC(CC1=CC=CC=C1)C(NC(CCCCN)C(NC(CC(C)C)C(NC([H])C(NC(CCCCN)C(NC(C2CCCN2)C(NC(CCCCN)C(NC(CC(O)=O)C(NC(CC1=CC=CC=C1)C(NC(C(CC)([H])C)C(NC(CCCCN)C(NC(CC1=CC=CC=C1)C(NC(CC(O)=O)C(NC(C(C)C)C(NC(CC1=CC=C(O)C=C1)C(NC(C(CC)([H])C)C(NC(CC(N)=O)C(NC(CC(O)=O)C(NC([H])C(NC(C(C)([H])O)C(NC(CC(O)=O)C(NC(CC1=CC=C(O)C=C1)C(NC(CCCCN)C(NC(C2CCCN2)C(NC(CCC(O)=O)C(NC(CC(O)=O)C(NC(CCCCN)C(NC(C(C)([H])O)C(NC(CCCCN)C(NC(C(CC)([H])C)C(NC(CC(N)=O)C(NC(CC(C)C)C(NC(CCC(O)=O)C(NC(CC1=CC=C(O)C=C1)C(NC(C)C(NC([H])C(NC(CO)C(NC(CC1=CC=CC=C1)C(NC(C(C)([H])O)C(NC(CO)C(NC(CC(C)C)C(NC(C(C)([H])O)C(NC(CC1=CNC=N1)C(NC([H])C(NC([H])C(NC([H])C(NC([H])C(NC([H])C(NC([H])C(NC([H])C(NC(CC(O)=O)C(NC(CCSC)C(NC(CO)C(NC(CC1=CNC=N1)C(NC(CCSC)C(NC(C)C(NC(CCC(O)=O)C(NC(CCC(O)=O)C(NC(CC(O)=O)C(NC(CCSC)C(NC([H])C(NC(CCCCN)C(NC(CC(N)=O)C(NC(C(C)([H])O)C(NC(C(C)C)C(NC(CC(C)C)C(NC(CCCCN)C(NC(CC(C)C)C(NC(C)C(NC(CC(C)C)C(NC(CC(N)=O)C(NC(CCC(N)=O)C(NC(CC(C)C)C(NC(CC(C)C)C(NC(CCC(O)=O)C(NC(CC(O)=O)C(NC(CC(C)C)C(NC(CC(O)=O)C(NC(C)C(NC(C(C)([H])O)C(NC(CC(O)=O)C(NC(CC(O)=O)C(NC(CC(O)=O)C(NC(CO)C(NC(C(CC)([H])C)C(NC(CCC(N)=O)C(NC(C(C)C)C(NC(C(C)([H])O)C(NC(C(CC)([H])C)C(NC(C(C)C)C(NC(C2CCCN2)C(NC(CCCCN)C(NC(CO)C(NC([H])C(NC(C(C)([H])O)C(NC(CC(O)=O)C(NC(CO)C(NC(C(CC)([H])C)C(NC(C(C)C)C(NC(C(CC)([H])C)C(NC(C(C)([H])O)C(NC([H])C(NC(C(CC)([H])C)C(NC(CC(O)=O)C(NC(C(CC)([H])C)C(NC(CCC(O)=O)C(NCC(O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O',
            'peroxidase': 'NC(CCSC)C(NC(CC1=CNC=N1)C(NC(CC1=CC=CC=C1)C(NC(CO)C(NC(CO)C(NC(CO)C(NC(CO)C(NC(C(C)([H])O)C(NC(CC(C)C)C(NC(CC1=CC=CC=C1)C(NC(C(C)([H])O)C(NC(CS)C(NC(C(CC)([H])C)C(NC(C(C)([H])O)C(NC(CC(C)C)C(NC(C(CC)([H])C)C(NC(C2CCCN2)C(NC(CC(C)C)C(NC(C(C)C)C(NC(CS)C(NC(CC(C)C)C(NC(C(CC)([H])C)C(NC(CC(C)C)C(NC(CC1=CNC=N1)C(NC(C)C(NC(CO)C(NC(CC(C)C)C(NC(CO)C(NC(CC(O)=O)C(NC(C)C(NC(CCC(N)=O)C(NC(CC(C)C)C(NC(C(C)([H])O)C(NC(C2CCCN2)C(NC(C(C)([H])O)C(NC(CC1=CC=CC=C1)C(NC(CC1=CC=C(O)C=C1)C(NC(CC(O)=O)C(NC(CC(N)=O)C(NC(CO)C(NC(CS)C(NC(C2CCCN2)C(NC(CC(N)=O)C(NC(C(C)C)C(NC(CO)C(NC(CC(N)=O)C(NC(C(CC)([H])C)C(NC(C(C)C)C(NC(CCCCNC(N)=N)C(NC(CC(O)=O)C(NC(C(C)([H])O)C(NC(C(CC)([H])C)C(NC(C(C)C)C(NC(CC(N)=O)C(NC(CCC(O)=O)C(NC(CC(C)C)C(NC(CCCCNC(N)=N)C(NC(CO)C(NC(CC(O)=O)C(NC(C2CCCN2)C(NC(CCCCNC(N)=N)C(NC(C(CC)([H])C)C(NC(C)C(NC(C)C(NC(CO)C(NC(C(CC)([H])C)C(NC(CC(C)C)C(NC(CCCCNC(N)=N)C(NC(CC(C)C)C(NC(CC1=CNC=N1)C(NC(CC1=CC=CC=C1)C(NC(CC1=CNC=N1)C(NC(CC(O)=O)C(NC(CS)C(NC(CC1=CC=CC=C1)C(NC(C(C)C)C(NC(CC(N)=O)C(NC([H])C(NC(CS)C(NC(CC(O)=O)C(NC(C)C(NC(CO)C(NC(C(CC)([H])C)C(NC(CC(C)C)C(NC(CC(C)C)C(NC(CC(O)=O)C(NC(CC(N)=O)C(NC(C(C)([H])O)C(NC(C(C)([H])O)C(NC(CO)C(NC(CC1=CC=CC=C1)C(NC(CCCCNC(N)=N)C(NC(C(C)([H])O)C(NC(CCC(O)=O)C(NC(CCCCN)C(NC(CC(O)=O)C(NC(C)C(NC(CC1=CC=CC=C1)C(NC([H])C(NC(CC(N)=O)C(NC(C)C(NC(CC(N)=O)C(NC(CO)C(NC(C)C(NC(CCCCNC(N)=N)C(NC([H])C(NC(CC1=CC=CC=C1)C(NC(C2CCCN2)C(NC(C(C)C)C(NC(C(CC)([H])C)C(NC(CC(O)=O)C(NC(CCCCNC(N)=N)C(NC(CCSC)C(NC(CCCCN)C(NC(C)C(NC(C)C(NC(C(C)C)C(NC(CCC(O)=O)C(NC(CO)C(NC(C)C(NC(CS)C(NC(C2CCCN2)C(NC(CCCCNC(N)=N)C(NC(C(C)([H])O)C(NC(C(C)C)C(NC(CO)C(NC(CS)C(NC(C)C(NC(CC(O)=O)C(NC(CC(C)C)C(NC(CC(C)C)C(NC(C(C)([H])O)C(NC(C(CC)([H])C)C(NC(C)C(NC(C)C(NC(CCC(N)=O)C(NC(CCC(N)=O)C(NC(CO)C(NC(C(C)C)C(NC(C(C)([H])O)C(NC(CC(C)C)C(NC(C)C(NC([H])C(NC([H])C(NC(C2CCCN2)C(NC(CO)C(NC(CCC1=CNC2=C1C=CC=C2)C(NC(CCCCNC(N)=N)C(NC(C(C)C)C(NC(C2CCCN2)C(NC(CC(C)C)C(NC([H])C(NC(CCCCNC(N)=N)C(NC(CCCCNC(N)=N)C(NC(CC(O)=O)C(NC(CO)C(NC(CC(C)C)C(NC(CCC(N)=O)C(NC(C)C(NC(CC1=CC=CC=C1)C(NC(CC(C)C)C(NC(CC(O)=O)C(NC(CC(C)C)C(NC(C)C(NC(CC(N)=O)C(NC(C)C(NC(CC(N)=O)C(NC(CC(C)C)C(NC(C2CCCN2)C(NC(C)C(NC(C2CCCN2)C(NC(CC1=CC=CC=C1)C(NC(CC1=CC=CC=C1)C(NC(C(C)([H])O)C(NC(CC(C)C)C(NC(C2CCCN2)C(NC(CCC(N)=O)C(NC(CC(C)C)C(NC(CCCCN)C(NC(CC(O)=O)C(NC(CO)C(NC(CC1=CC=CC=C1)C(NC(CCCCNC(N)=N)C(NC(CC(N)=O)C(NC(C(C)C)C(NC([H])C(NC(CC(C)C)C(NC(CC(N)=O)C(NC(CCCCNC(N)=N)C(NC(CO)C(NC(CO)C(NC(CC(O)=O)C(NC(CC(C)C)C(NC(C(C)C)C(NC(C)C(NC(CC(C)C)C(NC(CO)C(NC([H])C(NC([H])C(NC(CC1=CNC=N1)C(NC(C(C)([H])O)C(NC(CC1=CC=CC=C1)C(NC([H])C(NC(CCCCN)C(NC(CC(N)=O)C(NC(CCC(N)=O)C(NC(CS)C(NC(CCCCNC(N)=N)C(NC(CC1=CC=CC=C1)C(NC(C(CC)([H])C)C(NC(CCSC)C(NC(CC(O)=O)C(NC(CCCCNC(N)=N)C(NC(CC(C)C)C(NC(CC1=CC=C(O)C=C1)C(NC(CC(N)=O)C(NC(CC1=CC=CC=C1)C(NC(CO)C(NC(CC(N)=O)C(NC(C(C)([H])O)C(NC([H])C(NC(CC(C)C)C(NC(C2CCCN2)C(NC(CC(O)=O)C(NC(C2CCCN2)C(NC(C(C)([H])O)C(NC(CC(C)C)C(NC(CC(N)=O)C(NC(C(C)([H])O)C(NC(C(C)([H])O)C(NC(CC1=CC=C(O)C=C1)C(NC(CC(C)C)C(NC(CCC(N)=O)C(NC(C(C)([H])O)C(NC(CC(C)C)C(NC(CCCCNC(N)=N)C(NC([H])C(NC(CC(C)C)C(NC(CS)C(NC(C2CCCN2)C(NC(CC(C)C)C(NC(CC(N)=O)C(NC([H])C(NC(CC(N)=O)C(NC(CC(C)C)C(NC(CO)C(NC(C)C(NC(CC(C)C)C(NC(C(C)C)C(NC(CC(O)=O)C(NC(CC1=CC=CC=C1)C(NC(CC(O)=O)C(NC(CC(C)C)C(NC(CCCCNC(N)=N)C(NC(C(C)([H])O)C(NC(C2CCCN2)C(NC(C(C)([H])O)C(NC(C(CC)([H])C)C(NC(CC1=CC=CC=C1)C(NC(CC(O)=O)C(NC(CC(N)=O)C(NC(CCCCN)C(NC(CC1=CC=C(O)C=C1)C(NC(CC1=CC=C(O)C=C1)C(NC(C(C)C)C(NC(CC(N)=O)C(NC(CC(C)C)C(NC(CCC(O)=O)C(NC(CCC(O)=O)C(NC(CCC(N)=O)C(NC(CCCCN)C(NC([H])C(NC(CC(C)C)C(NC(C(CC)([H])C)C(NC(CCC(N)=O)C(NC(CO)C(NC(CC(O)=O)C(NC(CCC(N)=O)C(NC(CCC(O)=O)C(NC(CC(C)C)C(NC(CC1=CC=CC=C1)C(NC(CO)C(NC(CO)C(NC(C2CCCN2)C(NC(CC(N)=O)C(NC(C)C(NC(C(C)([H])O)C(NC(CC(O)=O)C(NC(C(C)([H])O)C(NC(C(CC)([H])C)C(NC(C2CCCN2)C(NC(CC(C)C)C(NC(C(C)C)C(NC(CCCCNC(N)=N)C(NC(CO)C(NC(CC1=CC=CC=C1)C(NC(C)C(NC(CC(N)=O)C(NC(CO)C(NC(C(C)([H])O)C(NC(CCC(N)=O)C(NC(C(C)([H])O)C(NC(CC1=CC=CC=C1)C(NC(CC1=CC=CC=C1)C(NC(CC(N)=O)C(NC(C)C(NC(CC1=CC=CC=C1)C(NC(C(C)C)C(NC(CCC(O)=O)C(NC(C)C(NC(CCSC)C(NC(CC(O)=O)C(NC(CCCCNC(N)=N)C(NC(CCSC)C(NC([H])C(NC(CC(N)=O)C(NC(C(CC)([H])C)C(NC(C(C)([H])O)C(NC(C2CCCN2)C(NC(CC(C)C)C(NC(C(C)([H])O)C(NC([H])C(NC(C(C)([H])O)C(NC(CCC(N)=O)C(NC([H])C(NC(CCC(N)=O)C(NC(C(CC)([H])C)C(NC(CCCCNC(N)=N)C(NC(CC(C)C)C(NC(CC(N)=O)C(NC(CS)C(NC(CCCCNC(N)=N)C(NC(C(C)C)C(NC(C(C)C)C(NC(CC(N)=O)C(NC(CO)C(NC(CC(N)=O)C(NC(CO)C(NC(CC(C)C)C(NC(CC(C)C)C(NC(CC1=CNC=N1)C(NC(CC(O)=O)C(NC(CCSC)C(NC(C(C)C)C(NC(CCC(O)=O)C(NC(C(C)C)C(NC(C(C)C)C(NC(CC(O)=O)C(NC(CC1=CC=CC=C1)C(NC(C(C)C)C(NC(CO)C(NC(CO)C(NC(CCSC)C(NCC(O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O)=O',
            'adenosine-5-triphosphatase': 'C1=NC(=C2C(=N1)N(C=N2)C3C(C(C(O3)COP(=O)(O)OP(=O)(O)OP(=O)(O)O)O)O)N',
            'arabinose': 'C1C(C(C(C(O1)O)O)O)O',
            'fructose': 'C1C(C(C(C(O1)(CO)O)O)O)O',
            'galactose': 'C(C1C(C(C(C(O1)O)O)O)O)O',
            'galacturonic acid': 'C1(C(C(OC(C1O)O)C(=O)O)O)O',
            'alpha and beta d-glucose': 'C(C(C(C(C(C=O)O)O)O)O)O',
            'altro-heptulose': 'C(C1C(C(C(C(O1)(CO)O)O)O)O)O',
            'd-manno-heptulose': 'C(C(C(C(C(C(=O)CO)O)O)O)O)O',
            'mannose': 'C(C1C(C(C(C(O1)O)O)O)O)O',
            'd-glycerol-d-manno-octulose': 'C(C(C(C(C(C(C(=O)CO)O)O)O)O)O)O',
            'rhamnose': 'CC1C(C(C(C(O1)O)O)O)O',
            'ribose': 'C1C(C(C(C(O1)O)O)O)O',
            'xylose': 'C1C(C(C(C(O1)O)O)O)O',
            'sucrose': 'C(C1C(C(C(C(O1)OC2(C(C(C(O2)CO)O)O)CO)O)O)O)O',
            'maltose': 'C(C1C(C(C(C(O1)OC2C(OC(C(C2O)O)O)CO)O)O)O)O',
            'raffinose': 'C(C1C(C(C(C(O1)OCC2C(C(C(C(O2)OC3(C(C(C(O3)CO)O)O)CO)O)O)O)O)O)O)O',
            'cellulose': 'C(C1C(C(C(C(O1)OC2C(OC(C(C2O)O)O)CO)O)O)O)O',
            'hemicellulose': 'CC(C(C1=CC=CC=C1)O)NC.CC(C(C1=CC=CC=C1)O)NC',
            'pectin': 'C1(C(C(OC(C1O)O)C(=O)O)O)O',
            'xylan': 'C1C(C(C(C(O1)O)O)O)O',
            'arabitol': 'C(C(C(C(CO)O)O)O)O',
            'erythritol': 'C(C(C(CO)O)O)O',
            'galactitol': 'C(C(C(C(C(CO)O)O)O)O)O',
            'glycerol': 'C(C(CO)O)O',
            'mannitol': 'C(C(C(C(C(CO)O)O)O)O)O',
            'ribitol': 'C(C1C(C(C(O1)C(C(C(C(CO)O)O)O)O)O)O)O',
            'sorbitol': 'C(C(C(C(C(CO)O)O)O)O)O',
            'xylitol': 'C(C(C(C(CO)O)O)O)O',
            'd-minus bornesitol': 'OC1C(O)C(O)C(OC)C(O)C1O',
            'plus inositol': 'C1(C(C(C(C(C1O)O)O)O)O)O',
            'myo inositol': 'C1(C(C(C(C(C1O)O)O)O)O)O',
            'plus quebrachitol': 'COC1C(C(C(C(C1O)O)O)O)O',
            'galactosamine': 'C(C1C(C(C(C(O1)O)N)O)O)O',
            'glucosamine': 'C(C1C(C(C(C(O1)O)N)O)O)O',
            'n-nonane': 'CCCCCCCCC',
            'n-decane': 'CCCCCCCCCC',
            'n-undecane': 'CCCCCCCCCCC',
            'n-dodecane': 'CCCCCCCCCCCC',
            'n-tridecane': 'CCCCCCCCCCCCC',
            'd-tetradecane': 'CCCCCCCCCCCCCC',
            '3,6-dimethyl-tridecane': 'CCCCC(C)CCC(C)CC',
            'n-pentadecane': 'CCCCCCCCCCCCCCC',
            '2,6-dimethyl tetradecane': 'CCCCCCCCC(C)CCCC(C)C',
            'n-hexadecane': 'CCCCCCCCCCCCCCCC',
            'n-heptadecane': 'CCCCCCCCCCCCCCCCC',
            '2,6-dimethyl hexadecane': 'CCCCCCCCCCCC(C)CCC(C)C',
            'n-octadecane': 'CCCCCCCCCCCCCCCCCC',
            '3,6-dimethyl heptadecane': 'CCCCCCCCCCCC(C)CC(C)CC',
            '3,7-dimethyl heptadecane': 'CCCCCCCCCCC(C)CCC(C)CC',
            'n-nonadecane': 'CCCCCCCCCCCCCCCCCCC',
            '3,6-dimethyl octadecane': '',
            '3,7-dimethyl octadecane': '',
            'n-eicosane': 'CCCCCCCCCCCCCCCCCCCC',
            'n-heneicosane': 'CCCCCCCCCCCCCCCCCCCCC',
            '3-methyl tricosane': 'CCCCCCCCCCCCCCCCCCCCC(C)CC',
            'n-tetracosane': 'CCCCCCCCCCCCCCCCCCCCCCCC',
            '2-methyl tetracosane': 'CCCCCCCCCCCCCCCCCCCCCCC(C)C',
            'n-pentacosane': 'CCCCCCCCCCCCCCCCCCCCCCCCC',
            'n-hexacosane': 'CCCCCCCCCCCCCCCCCCCCCCCCCC',
            '3-methyl-pentacosane': 'CCCCCCCCCCCCCCCCCCCCCCC(C)CC',
            '2-methyl hexacosane': 'CCCCCCCCCCCCCCCCCCCCCCCCC(C)C',
            'n-heptacosane': 'CCCCCCCCCCCCCCCCCCCCCCCCCCC',
            '3-methyl heptacosane': 'CCCCCCCCCCCCCCCCCCCCCCCCC(C)CC',
            'n-octacosane': 'CCCCCCCCCCCCCCCCCCCCCCCCCCCC',
            '2-methyl octacosane': 'CCCCCCCCCCCCCCCCCCCCCCCCCCC(C)C',
            '9-methyl octacosane': 'CCCCCCCCCCCCCCCCCCCC(C)CCCCCCCC',
            'n-nonacosane': 'CCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
            '3-methyl triacontane': 'CCCCCCCCCCCCCCCCCCCCCCCCCCCC(C)CC',
            'n-triacotane': '',
            '2-methyl hentriacontane': 'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC(C)C',
            'n-hentriacontane': 'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
            '3-methyl hentriacontane': 'CCCCCCCCCCCCCCCCCCCCCCCCCCCCC(C)CC',
            'n-dotriacontane': 'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
            '2-methyl dotriacontane': 'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC(C)C',
            'n-tritriacontane': 'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
            'tetra-triacontane': '',
            'pentatriacontane': 'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
            'hexatriacontane': 'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
            'heptatriacontane': 'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
            'octatriacontane': 'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
            'nonatriacontane': 'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
            'methanol': 'CO',
            'ethanol': 'CCO',
            'octanol-1': 'CCCCCCCC(O)',
            'octanol-3': 'CCCCCC(O)CC',
            'nonanol-1': 'CCCCCCCCC(O)',
            'hexadecanol-1': 'CCCCCCCC(O)CCCCCC',
            'acetaldehyde': 'CC=O',
            'isobutyraldehyde': 'CC(C)C=O',
            'pentanal': 'CCCCC=O',
            'hexanal': 'CCCCCC=O',
            'heptanal': 'CCCCCCC=O',
            'octanal': 'CCCCCCCC=O',
            'nonanal': 'CCCCCCCCC=O',
            'decanal': 'CCCCCCCCCC=O',
            'undecanal': 'CCCCCCCCCCC=O',
            'dodecanal': 'CCCCCCCCCCCC=O',
            'tridecanal': 'CCCCCCCCCCCCC=O',
            'p-ethylbenzaldehyde': 'CCc1ccc(C=O)cc1',
            'acetone': 'CC(C)=O',
            'heptanone-2': '',
            '2-methyl-2heptene-6-one': 'CC(C)=CCCC(C)=O',
            'decanone-2': '',
            'undecanone-2': '',
            'dodecanone-2': '',
            'pentadecanone-2': '',
            'octanone-3': '',
            '2,2,6-trimethyl cyclohexanone': 'CC1CCCC(C)(C)C1=O',
            '2,2,6-trimethyl-5-cyclohexenone': 'CC1=CCCC(C)(C)C1=O',
            '3-decene-5-one': 'CCCCCC(=O)C=CCC',
            '6,10-dimethyl undecanone-2': '',
            '6,10,14-trimethyl pentadecanone-2': '',
            'ahrabinic': '',
            'aizelaic': '',
            'cinnamic': '',
            'citric': '',
            'glucaric': '',
            'gluconic': '',
            'glyceric': '',
            'para hydroxybenzoic': '',
            'para hydroxycinnamic': '',
            'isocitric': '',
            'malic': '',
            'malonic': '',
            '2-c-methylaldotetronic': '',
            '3-methyoxy-4-hydroxycinnamic': '',
            'phosphoric': '',
            'pyroglutamic': '',
            'quinic': '',
            'succininc': '',
            'threonic': '',
            'vanillic': '',
            'arachidic': '',
            'behenic': '',
            'eicosadienic': '',
            'eicosemic': '',
            'linoleic': r'CCCCC/C=C/C/C=C/CCCCCCCC(O)=O',
            'linolenic': '',
            'myristic': '',
            'oleic': '',
            'palmitic': '',
            'palmitoleic': '',
            'sativic': '',
            'stearic': '',
            'benzyl acetate': 'CC(=O)OCc1ccccc1',
            'para ethyl benzyl acetate': '',
            '3-hexenyl caproate': 'CCCCCC(=O)OCCC=CCC',
            'hexyl acetate': 'CCCCCCOC(C)=O',
            'hexyl butyrate': 'CCCCCCOC(=O)CCC',
            'hexyl isobutyrate': 'CCCCCCOC(=O)C(C)C',
            'methyl acetate': 'COC(C)=O',
            '2-c-methyl aldotetronolactone': '',
            'methyl linoleate': r'CCCCC/C=C\C\C=C/CCCCCCCC(=O)OC',
            'methyl palmitate': 'CCCCCCCCCCCCCCCC(=O)OC',
            'methyl salicylate': 'COC(=O)c1ccccc1O',
            'octyl caproate': 'CCCCCCCCOC(=O)CCCCC',
            'campesterol': 'CC(C)C(C)CCC(C)C1CCC2C3CC=C4CC(O)CCC4(C)C3CCC12C',
            'campest-5-en-3beta-ol-7-one': '',
            'campes-4-en-3-one': '',
            'ergosterol': r'CC(C)C(C)/C=C/C(C)C1CCC2C3=CC=C4CC(O)CCC4(C)C3CCC12C',
            'beta-sitosterol': 'CCC(CCC(C)C1CCC2C3CC=C4CC(O)CCC4(C)C3CCC12C)C(C)C',
            '5alpha-stigmasta-7,24-dien-3beta-ol': 'CCC(CCC(C)C1CCC2C3=CCC4CC(O)CCC4(C)C3CCC12C)=C(C)C',
            'stigmasta-5,22-dien-3beta-ol-7-one': '',
            'stigmast-5-en-3beta-ol-7-one': '',
            'stigmast-4-en-3-one': 'CCC(CCC(C)C1CCC2C3CCC4=CC(=O)CCC4(C)C3CCC12C)C(C)C',
            'stigmasterol': r'CCC(/C=C/C(C)C1CCC2C3CC=C4CC(O)CCC4(C)C3CCC12C)C(C)C',
            'borneol': 'CC1(C)C2CCC1(C)C(O)C2',
            'bornyl acetate': 'CC(=O)OC1CC2CCC1(C)C2(C)C',
            'camphene': 'CC1(C)C2CCC(C2)C1=C',
            'camphenehydrate': '',
            'camphor': 'CC1(C)C2CCC1(C)C(=O)C2',
            'delta-3 carene': '',
            'delta-4 carene': '',
            'carvacrol': 'CC(C)c1ccc(C)c(O)c1',
            'carvone': 'CC(=C)C1CC=C(C)C(=O)C1',
            'beta-cyclocitral': 'CC1=C(C=O)C(C)(C)CCC1',
            '1,4-cineol': 'CC(C)C12CCC(C)(CC1)O2',
            '1,8-cineol': 'CC12CCC(CC1)C(C)(C)O2',
            'citral b': 'CC(C)=CCC\C(C)=C/C=O',
            'citronellol': 'CC(CCO)CCC=C(C)C',
            'para cymene': 'CC(C)c1ccc(C)cc1',
            'para cymene-8-ol': '',
            'dihydrocarveyl acetate': 'CC1CCC(CC1OC(C)=O)C(C)=C',
            'dihydrocarvone': 'CC1CCC(CC1=O)C(C)=C',
            'fenchyl alcohol': 'CC1(C)C2CCC(C)(C2)C1O',
            'fenchone': 'CC1(C)C2CCC(C)(C2)C1=O',
            'geraniol': r'CC(C)=CCC\C(C)=C\CO',
            'geranyl acetone': r'CC(C)=CCCC(/C)=C/CCC(C)=O',
            'limonene': 'CC(=C)C1CCC(=CC1)C',
            'linalool': 'CC(C)=CCCC(C)(O)C=C',
            'linalool oxide': 'CC(C)=CCCC(C)(O)C1CO1',
            'meta mentha-1,8-dien-5-ol': '',
            '1-methyl-4-iso-propenylbenzene': 'CC(=C)c1ccc(C)cc1',
            'myrcene': 'CC(C)=CCCC(=C)C=C',
            'nerol':r'CC(C)=CCC\C(C)=C/CO',
            'nerolidol': 'CC(C)=CCCC(C)=CCCC(C)(O)C=C',
            'beta-ocimene': 'CC(C)=CCC=C(C)C=C',
            'perillene': 'CC(C)=CCCc1cocc1',
            'alpha-phellandrene': 'CC(C)C1CC=C(C)C=C1',
            'beta-phellandrene': 'CC(C)C1CCC(=C)C=C1',
            '3-phenyl-2-methyl-prop-1-ene': 'CC(=C)Cc1ccccc1',
            'alpha-pinene': 'CC1=CCC2CC1C2(C)C',
            'beta-pinene': 'CC1(C)C2CCC(=C)C1C2',
            'alpha-pinene oxide': 'CC1(C)C2CC3OC3(C)C1C2',
            'pinocarveol': 'CC1(C)C2CC(O)C(=C)C1C2',
            'pinocarvone': 'CC1(C)C2CC1C(=C)C(=O)C2',
            'piperitenone': 'CC(C)=C1CCC(=CC1=O)C',
            'piperitone oxide': 'CC(C)C1CCC2(C)OC2C1=O',
            'piperitenone oxide': 'CC(C)=C1CCC2(C)OC2C1=O',
            'pulegone': 'CC1CCC(=C(C)C)C(=O)C1',
            'sabinene': 'CC(C)C12CCC(=C)C1C2',
            'sabiene hydrate': '',
            'sabinol': 'CC(C)C12CC(O)C(=C)C1C2',
            'safranal': 'CC1=C(C=O)C(C)(C)CC=C1',
            'alpha thujene': '',
            'alpha terpinene': '',
            'gamma terpinene': '',
            'alpha terpiene-4-ol': '',
            'alpha terpinolene': '',
            'alpha terpineol': '',
            'beta terpineol': '',
            'thujyl alcohol': 'CC(C)C12CC1C(C)CC2O',
            'allo-aromadendrene': '',
            'alpha-bergamotene': 'CC(C)=CCCC1(C)C2CC=C(C)C1C2',
            'beta bisabolene': '',
            'alpha bisabolol': '',
            'calamenene': 'CC(C)C1CCC(C)c2ccc(C)cc12',
            'caryophyllene': r'C\C1=C/CCC(=C)C2CC(C)(C)C2CC1',
            'alpha caryophyllene': '',
            'beta caryophyllene': '',
            'alpha caryophyllene alcohol': '',
            'isocarophyllene': '',
            'caryophyllene oxide': 'CC1(C)CC2C1CCC3(C)OC3CCC2=C',
            'alpha cedrene': '',
            'gamma cadinene': '',
            'delta cadinene': '',
            'alpha copaene': '',
            'alpha cubebene': '',
            'alpha curcumene': '',
            'beta cucumene': '',
            'gamma elemene': '',
            'gamma eudesmol': '',
            'beta farnesene': '',
            'z beta farnesene': '',
            'alpha farnesene': '',
            'farnesol': 'CC(C)=CCCC(C)=CCCC(C)=CCO',
            'farnesyl acetone': 'CC(C)=CCCC(C)=CCCC(C)=CCCC(C)=O',
            'alpha gurjunene': '',
            'guaiol': 'CC1CCC(CC2=C1CCC2C)C(C)(C)O',
            'beta humulene': '',
            'humelene epoxide I': '',
            'humelene epoxide II': '',
            'ledol': 'CC1CCC2C1C3C(CCC2(C)O)C3(C)C',
            'longifolene': 'CC1(C)CCCC2(C)C3CCC(C13)C2=C',
            'epi-beta-sanalene': '',
            'alpha selinene': '',
            'beta selinene': '',
            'selina-3,7-diene': 'CC(C)C1=CC[C@@]2(C)CCC=C(C)C2C1',
            'selina-4.7-diene': '',
            'friedelin': 'CC1C(=O)CCC2C1(C)CCC3C2(C)CCC4(C)C5CC(C)(C)CCC5(C)CCC34C',
            'epifriedelanol': 'CC1C(O)CCC2C1(C)CCC3C2(C)CCC4(C)C5CC(C)(C)CCC5(C)CCC34C',
            'vomifoliol': r'CC(O)/C=C/C1(O)C(=CC(=O)CC1(C)C)C',
            'dihydrovomifoliol': 'CC1(C)CCCC2(C)OC(=O)C=C12',
            'beta ionone': '',
            'dihydroactinidiolide': '',
            'acetylcannabispirol': '',
            'cannabispiradienone': '',
            'beta cannabispiranol': '',
            'cannabispirenone': '',
            'cannabispirenone-isomer': '',
            'cannabispirone': '',
            '3-[2-(4-hydroxyphenyl)ethyl]-5-methoxyphenol': 'COc1cc(O)cc(CCc2ccc(O)cc2)c1',
            '3-[2-(3-hydroxy-4-methoxyphenyl)ethyl]-5-methoxyphenol': 'COc1cc(O)cc(CCc2ccc(OC)c(O)c2)c1',
            '3-[2-(3-isoprenyl-4-hydroxy-5-methoxy-phenyl)ethyl]-5-methoxyphenol': 'COc1cc(O)cc(CCc2cc(OC)c(O)c(C=CC(C)=C)c2)c1',
            'canniprene': '',
            'cannabidhydrophenanthrene': '',
            'eugenol': 'COc1cc(CC=C)ccc1O',
            'isoeugenol': 'COc1cc(C=CC)ccc1O',
            'anethol': 'COc1ccc(C=CC)cc1',
            'methyleugenol': 'COc1ccc(CC=C)cc1OC',
            'apigenin-7-O-para coumarylglucoside': '',
            'cosmosioside': 'OCC1OC(Oc2cc(O)c3C(=O)C=C(Oc3c2)c4ccc(O)cc4)C(O)C(O)C1O',
            'Apigenin-O-glycoside': '',
            'isovitesin-7-O-giucoara binoside': '',
            'isovitexin-O-glucoside': '',
            'isovitesin-7-O-rhamnoglucoside': '',
            'kaempferol-O-glycoside': '',
            'luteolin-O-glycoside': '',
            'orientin': 'OCC1OC(C(O)C(O)C1O)c2c(O)cc(O)c3C(=O)C=C(Oc23)c4ccc(O)c(O)c4',
            'orientin-7-O-glucoside': '',
            'orientin-O-glucoside': '',
            'orientin-7-O-rhamnoglucoside': '',
            'quercetin-O-glucoside': '',
            'vitexin-7-O-g"-glucoside': '',
            'vitexin-O-glucoside': '',
            'vitexin-O-rhamnoglucoside': '',
            '2"-O-glucopyranosylorientin': '',
            '2"-O-glucopyranosylvitexin': '',
            'vitamin k': 'CC(C)CCCC(C)CCCC(C)CCC/C(C)=C/CC1=C(C)C(=O)c2ccccc2C1=O',
            'carotene': '',
            'zanthophylls': '',
            'cannabichromanone c3': '',
            'cannabielsoin c3': '',
            'cannabielsoin acid b-c3': '',
            'cannabicurmaronone': '',
        }

        return smiles

    @staticmethod
    def get_smarts():

        smarts = {
        }

        return smarts