#!/usr/bin/env python3
#
# GlobalChem - Schedule Five
#
# -----------------------------------

class Pihkal(object):

    def __init__(self):

        self.name = 'pihkal'

    @staticmethod
    def get_smiles():

        smiles = {
            'alpha-ETHYLMESCALINE': 'CCC(N)CC1=CC(=C(OC)C(=C1)OC)OC',
            '4-ALLYLOXY-3,5-DIMETHOXYPHENETHYLAMINE': 'COC1=CC(=CC(=C1OCC=C)OC)CCN',
            '2,5-DIMETHOXY-4-METHYLTHIOAMPHETAMINE': 'COC1=CC(=C(OC)C=C1CC(C)N)SC',
            '2,5-DIMETHOXY-4-ETHYLTHIOAMPHETAMINE': 'CCSC1=C(OC)C=C(CC(C)N)C(=C1)OC',
            '2,5-DIMETHOXY-4-(i)-PROPYLTHIOAMPHETAMINE': 'COC1=CC(=C(OC)C=C1CC(C)N)SC(C)C',
            '2,5-DIMETHOXY-4-PHENYLTHIOAMPHETAMINE': 'COC1=CC(=C(OC)C=C1CC(C)N)SC2=CC=CC=C2',
            '2,5-DIMETHOXY-4-(n)-PROPYLTHIOAMPHETAMINE': 'CCCSC1=C(OC)C=C(CC(C)N)C(=C1)OC',
            'DIMOXAMINE': 'CCC(N)CC1=CC(=C(C)C=C1OC)OC',
            'ASYMBESCALINE': 'CCOC1=CC(=CC(=C1OCC)OC)CCN',
            'BUSCALINE': 'CCCCOC1=C(OC)C=C(CCN)C=C1OC',
            '2,5-DIMETHOXY-4,N-DIMETHYLAMPHETAMINE': 'CNC(C)CC1=CC(=C(C)C=C1OC)OC',
            '4-METHYL-2,5-bis-(METHYLTHIO)AMPHETAMINE': 'CSC1=C(C)C=C(SC)C(=C1)CC(C)N',
            '4-BROMO-2,5-beta-TRIMETHOXYPHENETHYLAMINE': 'COC(CN)C1=CC(=C(Br)C=C1OC)OC',
            '4-METHYL-2,5,beta-TRIMETHOXYPHENETHYLAMINE': 'COC(CN)C1=CC(=C(C)C=C1OC)OC',
            'beta-METHOXY-3,4-METHYLENEDIOXYPHENETHYLAMINE': 'COC(CN)C1=CC(=C(C)C=C1OC)OC',
            '2,5-DIMETHOXY-beta-HYDROXY-4-METHYLPHENETHYLAMINE': 'CC1=C(O)C=C(C(O)CN)C(=C1)Br',
            'beta-METHOXYMESCALINE': 'COC(CN)C1=CC(=C(OC)C(=C1)OC)OC',
            '3,5-DIMETHOXY-4-BROMOAMPHETAMINE': 'COC1=C(Br)C(=CC(=C1)CC(C)N)OC',
            '2-BROMO-4,5-METHYLENEDIOXYAMPHETAMINE': 'CC(N)CC1=C(Br)C=C2OCOC2=C1',
            '4-BROMO-2,5-DIMETHOXYPHENETHYLAMINE': '[CH3:20][O:13][C:6]1=[CH:5][C:4](=[C:3]([O:16][CH3:11])[CH:2]=[C:1]1[Br:12])[CH2:8][CH2:9][NH2:10]', # Edit but works
            '4-BENZYLOXY-3,5-DIMETHOXYAMPHETAMINE': 'COC1=C(OCC2=CC=CC=C2)C(=CC(=C1)CC(C)N)OC',
            '2,5-DIMETHOXY-4-CHLOROPHENETHYLAMINE': 'COC1=CC(=C(OC)C=C1Cl)CCN',
            '2,5-DIMETHOXY-4-METHYLPHENETHYLAMINE': '[CH3:20][O:13][C:6]1=[CH:5][C:4](=[C:3]([O:16][CH3:11])[CH:2]=[C:1]1[CH3:12])[CH2:8][CH2:9][NH2:10]', # Edit but works
            '2,5-DIMETHOXY-4-ETHYLPHENETHYLAMINE': 'CCC1=CC(=C(CCN)C=C1OC)OC',
            '3,5-DIMETHOXY-4-ETHOXYAMPHETAMINE': 'CCOC1=C(OC)C=C(CC(C)N)C=C1OC',
            '2,5-DIMETHOXY-4-FLUOROPHENETHYLAMINE': 'COC1=CC(=C(OC)C=C1F)CCN',
            '2,5-DIMETHOXY-3,4-DIMETHYLPHENETHYLAMINE': 'COC1=CC(=C(OC)C(=C1C)C)CCN',
            '2,5-DIMETHOXY-3,4-(TRIMETHYLENE)PHENETHYLAMINE': 'COC1=CC(=C(OC)C2=C1CCC2)CCN',
            '2,5-DIMETHOXY-3,4-(TETRAMETHYLENE)PHENETHYLAMINE': 'COC1=CC(=C(OC)C2=C1CCCC2)CCN',
            '3,6-DIMETHOXY-4-(2-AMINOETHYL)BENZONORBORNANE': 'COC1=CC(=C(OC)C2=C1C3CCC2C3)CCN',
            '1,4-DIMETHOXYNAPHTHYL-2-ETHYLAMINE': 'COC1=CC(=C(OC)C2=C1C=CC=C2)CCN',
            '2,5-DIMETHOXYPHENETHYLAMINE': 'COC1=CC(=C(OC)C=C1)CCN',
            '2,5-DIMETHOXY-4-IODOPHENETHYLAMINE': '[CH3:20][O:13][C:6]1=[CH:5][C:4](=[C:3]([O:16][CH3:11])[CH:2]=[C:1]1[I:12])[CH2:8][CH2:9][NH2:10]',
            '2,5-DIMETHOXY-4-NITROPHENETHYLAMINE': 'COC1=C(CCN)C=C(OC)C(=C1)[N](=O)=O',
            '2,5-DIMETHOXY-4-(i)-PROPOXYPHENETHYLAMINE': 'COC1=C(CCN)C=C(OC)C(=C1)OC(C)C',
            '2,5-DIMETHOXY-4-(n)-PROPYLPHENETHYLAMINE': 'CCCOC1=CC(=C(CCN)C=C1OC)OC',
            'CYCLOPROPYLMESCALINE': 'COC1=C(CCN)C=C(OC)C(=C1)OCC2CC2',
            '2,5-DIMETHOXY-4-METHYLSELENEOPHENETHYLAMINE': 'COC1=C(CCN)C=C(OC)C(=C1)[Se]C',
            '2,5-DIMETHOXY-4-METHYLTHIOPHENETHYLAMINE': 'COC1=C(CCN)C=C(OC)C(=C1)SC',
            '2,5-DIMETHOXY-4-ETHYLTHIOPHENETHYLAMINE': '[CH3:30][CH2:29][S:12][C:1]1=[CH:2][C:3](=[C:4]([CH2:8][CH2:9][NH2:10])[CH:5]=[C:6]1[O:13][CH3:20])[O:16][CH3:11]',
            '2,5-DIMETHOXY-4-(i)-PROPYLTHIOPHENETHYLAMINE': 'COC1=C(CCN)C=C(OC)C(=C1)SC(C)C',
            '2,6-DIMETHOXY-4-(i)-PROPYLTHIOPHENETHYLAMINE)': 'COC1=C(CCN)C(=CC(=C1)SC(C)C)OC',
            '2,5-DIMETHOXY-4-(n)-PROPYLTHIOPHENETHYLAMINE': '[CH3:33][CH2:30][CH2:29][S:12][C:1]1=[CH:2][C:3](=[C:4]([CH2:8][CH2:9][NH2:10])[CH:5]=[C:6]1[O:13][CH3:20])[O:16][CH3:11]',
            '2,5-DIMETHOXY-4-CYCLOPROPYLMETHYLTHIOPHENETHYLAMINE': 'COC1=C(CCN)C=C(OC)C(=C1)SCC2CC2',
            '2,5-DIMETHOXY-4-(t)-BUTYLTHIOPHENETHYLAMINE': 'COC1=C(CCN)C=C(OC)C(=C1)SC(C)(C)C',
            '2,5-DIMETHOXY-4-(2-METHOXYETHYLTHIO)PHENETHYLAMINE': 'COCCSC1=CC(=C(CCN)C=C1OC)OC',
            '2,5-DIMETHOXY-4-CYCLOPROPYLTHIOPHENETHYLAMINE': 'COC1=C(CCN)C=C(OC)C(=C1)SC2CC2',
            '2,5-DIMETHOXY-4-(s)-BUTYLTHIOPHENETHYLAMINE': 'CCC(C)SC1=CC(=C(CCN)C=C1OC)OC',
            '2,5-DIMETHOXY-4-(2-FLUOROETHYLTHIO)PHENETHYLAMINE': 'COC1=C(CCN)C=C(OC)C(=C1)SCCF',
            '3,5-DIMETHOXY-4-TRIDEUTEROMETHOXY-PHENETHYLAMINE': 'COC1=CC(=CC(=C1OC)OC)CCN',
            '3,4,5-TRIMETHOXY-beta,beta-DIDEUTEROPHENETHYLAMINE': 'COC1=CC(=CC(=C1OC)OC)CCN',
            '3,5-DIMETHOXY-4-METHYLPHENETHYLAMINE': 'COC1=CC(=CC(=C1C)OC)CCN',
            '2,4-DIMETHOXYAMPHETAMINE': 'COC1=CC=C(CC(C)N)C(=C1)OC',
            '2,5-DIMETHOXYAMPHETAMINE': 'COC1=CC=C(OC)C(=C1)CC(C)N',
            '3,4-DIMETHOXYAMPHETAMINE': 'COC1=CC=C(CC(C)N)C=C1OC',
            '2-(2,5-DIMETHOXY-4-METHYLPHENYL)CYCLOPROPYLAMINE': 'COC1=CC(=C(OC)C=C1C)C2CC2N',
            '3,4-DIMETHOXY-beta-HYDROXYPHENETHYLAMINE': 'COC1=CC=C(C=C1OC)C(O)CN',

        }

        return smiles

    @staticmethod
    def smarts():

        smarts = {

        }

        return smarts
