name: GlobalChemExtensions Graphing API

on: [pull_request, push, workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.7", "3.8", "3.9"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Requirements
        run: |
           
           python -m pip install -r global_chem_extensions/requirements.txt
           
      - name: InstallGraphing Library
        run: |
          
          cd global_chem_extensions
          python -m pip install -e .[graphing]

