import { useState } from "react";
import Head from "next/head";

const { Octokit } = require('@octokit/rest');

export default function Home() {

  const [smilesList, setSmilesList] = useState("");

  const handleSubmit = async () => {
    const octokit = new Octokit({
      auth: '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'
    })
    try {
      const response = await octokit.request(`POST /repos/Global-Chem/workers/issues`, {
        title: 'PCA Smiles Test',
        body: `${smilesList}`,
        labels: ['pca_analysis']
      })
      
    } catch (error) {
      console.log(error);
    }
  };

  const handleChange = (e) => {
    const input = e.target.value;
    const inputNoWhitespace = input.replace(/\s/g, "");
    const smilesArray = inputNoWhitespace.split(",");

    setSmilesList(smilesArray);
  };


  return (
    <>
      <Head>
        <title>Global Chem - PCA Analysis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav className="bg-gray-100 border-gray-200 px-4 lg:px-6 py-2">
          <div className="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl">
            <a href="https://www.globalchemistry.org/" className="flex items-center">
              <img
                src="/globalchemlogo.png"
                className="mr-3 h-12 py-1"
                alt="Global Chem Logo"
              /> 
            </a>
          </div>
        </nav>
      </header>
      <main>
        <div className="mx-auto max-w-2xl py-20">
          <div className="text-center">
            <div className="">
              <a
                href="https://github.com/Global-Chem"
                className="inline-flex justify-between items-center py-1 pl-4 pr-2 mb-7 text-sm text-gray-700 bg-gray-100 rounded-full hover:bg-gray-200"
                role="alert"
              >
                <span className="text-sm font-medium">Follow us on GitHub</span>
                <svg
                  className="ml-1 w-5 h-5"
                  fill="currentColor"
                  viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    fillRule="evenodd"
                    d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                    clipRule="evenodd"
                  ></path>
                </svg>
              </a>
            </div>
            <h1 className="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">
              Principle Component Analysis
            </h1>
          </div>
          <div className="mt-10">
            <div className="grid grid-cols-1 gap-y-10 gap-x-6 sm:grid-cols-2">
              <div className="sm:col-span-2">
                <label
                  htlmFor="smilesList"
                  className="block text-sm font-medium text-gray-700"
                >
                  SMILES
                </label>
                <div className="mt-1">
                  <textarea
                    id="smilesList"
                    name="smilesList"
                    rows="3"
                    className="shadow-sm focus:ring-indigo-500 focus:border-indigo-500 mt-1 block w-full sm:text-sm rounded-md p-4 border border-gray-200"
                    placeholder="Enter SMILES here"
                    value={smilesList}
                    onChange={handleChange}
                  ></textarea>
                  <button
                    type="button"
                    className="inline-flex items-center float-right px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 mt-4"
                    onClick={handleSubmit}
                  >
                    Submit
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
